import { test } from 'node:test';
import assert from 'node:assert/strict';
import { spawn } from 'node:child_process';
import { mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { once } from 'node:events';

test('production: login, uploads, persistence, permissions and order workflow', async () => {
  const dir=await mkdtemp(path.join(tmpdir(),'printlink-test-'));
  let child, base;
  // Ask the OS for an unused port, then start the isolated app.
  const net=await import('node:net');const reserve=net.createServer();reserve.listen(0,'127.0.0.1');await once(reserve,'listening');const port=reserve.address().port;await new Promise(r=>reserve.close(r));
  const launch=async()=>{child=spawn(process.execPath,['cloud/server.mjs'],{cwd:process.cwd(),env:{...process.env,APP_MODE:'production',COLLECTOR_TOKEN:'isolated-test-token-with-at-least-32-characters',DATA_DIR:dir,HOST:'127.0.0.1',PORT:String(port),ADMIN_PASSWORD:'test-admin-secret-123',COOKIE_SECURE:'false'},stdio:['ignore','pipe','pipe']});base=`http://127.0.0.1:${port}`;await new Promise((resolve,reject)=>{child.stdout.once('data',resolve);child.once('exit',code=>reject(Error('server exited '+code)));child.stderr.on('data',b=>{if(!String(b).includes('ExperimentalWarning')&&!String(b).includes('trace-warnings'))process.stderr.write(b);});});};
  const stop=async()=>{if(child&&child.exitCode===null){child.kill();await once(child,'exit');}};
  const request=async(route,options={},auth)=>{const res=await fetch(base+route,{...options,headers:{...(auth?{Cookie:auth.cookie,'X-CSRF-Token':auth.csrf}:{}),...(options.body&&typeof options.body==='string'?{'Content-Type':'application/json'}:{}),...options.headers}});return {res,data:await res.json()};};
  const login=async(username,password)=>{const {res,data}=await request('/api/login',{method:'POST',body:JSON.stringify({username,password})});assert.equal(res.status,200);assert.ok(!/; Secure/i.test(res.headers.get('set-cookie')));assert.match(res.headers.get('set-cookie'),/HttpOnly/);return {cookie:res.headers.get('set-cookie').split(';')[0],csrf:data.csrf};};
  try {
    await launch();
    assert.equal((await request('/api/orders')).res.status,401);
    assert.equal((await request('/api/login',{method:'POST',body:JSON.stringify({username:'admin',password:'wrong'})})).res.status,401);
    let admin=await login('admin','test-admin-secret-123');
    assert.deepEqual((await request('/api/orders',{},admin)).data,[]);
    assert.equal((await request('/api/users',{method:'POST',body:'{}',headers:{'X-CSRF-Token':'bad'}},admin)).res.status,403);
    assert.equal((await request('/api/users',{method:'POST',body:JSON.stringify({username:'shortpw',name:'测试',password:'test123',factory:'湖南',role:'member'})},admin)).res.status,400);
    for(const [username,factory] of [['hunan','湖南'],['heyuan','河源']]) assert.equal((await request('/api/users',{method:'POST',body:JSON.stringify({username,name:username,password:'test1234',factory,role:'member'})},admin)).res.status,201);
    const hn=await login('hunan','test1234'),hy=await login('heyuan','test1234');
    const bytes=Buffer.from('ISO-10303-21;\nDATA;\nENDSEC;\nEND-ISO-10303-21;');
    const upload=async(name,auth=hn)=>request('/api/uploads',{method:'POST',headers:{'Content-Type':'application/octet-stream','X-File-Name':encodeURIComponent(name)},body:bytes},auth);
    assert.equal((await upload('evil.html')).res.status,400);
    assert.equal((await upload('../test.stp')).res.status,400);
    const file=await upload('呼吸灯.stp');assert.equal(file.res.status,201);
    const input={factory:'湖南',workshop:'A',customer:'测试客户',sku:'TEST-1',product:'测试模型',quantity:10,material:'硬胶',color:'白色',engineer:'测试工程师',dueDate:'2026-10-06',priority:'普通',fileIds:[file.data.id]};
    const post=d=>request('/api/orders',{method:'POST',body:JSON.stringify(d)},hn);
    assert.equal((await post({...input,factory:'河源'})).res.status,403);
    assert.equal((await post({...input,quantity:-1})).res.status,400);
    assert.equal((await post({...input,dueDate:'2026-02-30'})).res.status,400);
    const created=await post(input);assert.equal(created.res.status,201);const id=created.data.id;
    assert.equal((await post(input)).res.status,400,'attached file cannot be reused');
    assert.equal((await request('/api/orders',{},hn)).data.length,1);
    assert.equal((await request('/api/orders',{},hy)).data.length,0);
    assert.equal((await request('/api/files/'+file.data.id,{},hy)).res.status,404);
    const downloaded=await fetch(base+'/api/files/'+file.data.id,{headers:{Cookie:hn.cookie}});assert.equal(downloaded.status,200);assert.deepEqual(Buffer.from(await downloaded.arrayBuffer()),bytes);
    assert.equal((await request('/api/orders/'+id,{method:'PATCH',body:JSON.stringify({status:'待排产'})},hn)).res.status,403);
    const sendFeedback=(auth, content='表面有层纹，希望改善打磨')=>request('/api/orders/'+id+'/feedback',{method:'POST',body:JSON.stringify({category:'质量问题',rating:'一般',content})},auth);
    assert.equal((await sendFeedback(hn)).res.status,400,'unfinished order cannot receive feedback');
    const update=d=>request('/api/orders/'+id,{method:'PATCH',body:JSON.stringify(d)},admin);
    assert.equal((await update({status:'已完成'})).res.status,400);
    assert.equal((await update({status:'待排产'})).res.status,400);
    for(const status of ['待排产','打印中','待交付','已完成']) assert.equal((await update({status,follower:'打印工程师',replyDate:'2026-10-07'})).res.status,200);
    assert.equal((await update({status:'打印中',follower:'打印工程师',replyDate:'2026-10-07'})).res.status,400);
    assert.equal((await sendFeedback(hy)).res.status,404);
    assert.equal((await sendFeedback(admin)).res.status,403,'admin cannot impersonate order owner');
    assert.equal((await sendFeedback(hn,'   ')).res.status,400);
    const feedbackResult=await sendFeedback(hn);assert.equal(feedbackResult.res.status,201);
    const fid=feedbackResult.data.feedback[0].id;
    assert.equal(feedbackResult.data.feedback[0].authorName,'hunan');
    const respond=auth=>request('/api/feedback/'+fid,{method:'PATCH',body:JSON.stringify({status:'已处理',reply:'已安排重新打磨，并调整后续工艺'})},auth);
    assert.equal((await respond(hn)).res.status,403);
    assert.equal((await respond(admin)).res.status,200);
    await stop();await launch();admin=await login('admin','test-admin-secret-123');
    const saved=(await request('/api/orders',{},admin)).data;assert.equal(saved.length,1);assert.equal(saved[0].status,'已完成');assert.equal(saved[0].feedback[0].status,'已处理');assert.equal(saved[0].feedback[0].content,'表面有层纹，希望改善打磨');assert.equal(saved[0].events.length,7);assert.equal(saved[0].files.length,1);
    const accounts=(await request('/api/users',{},admin)).data;
    const memberId=accounts.find(x=>x.username==='hunan').id;
    const reset=(auth,id,password='newpass8',confirmation=password)=>request('/api/users/'+id+'/password',{method:'PATCH',body:JSON.stringify({password,confirmation})},auth);
    assert.equal((await reset(hn,memberId)).res.status,403);
    assert.equal((await reset(admin,memberId,'short')).res.status,400);
    assert.equal((await reset(admin,memberId,'newpass8','different')).res.status,400);
    assert.equal((await reset(admin,memberId)).res.status,200);
    assert.equal((await request('/api/me',{},hn)).res.status,401,'password reset revokes existing sessions');
    assert.equal((await request('/api/login',{method:'POST',body:JSON.stringify({username:'hunan',password:'test1234'})})).res.status,401);
    await login('hunan','newpass8');
    assert.equal((await request('/api/logout',{method:'POST'},admin)).res.status,200);
    assert.equal((await request('/api/orders',{},admin)).res.status,401);
    admin=await login('admin','test-admin-secret-123');
    const adminId=accounts.find(x=>x.username==='admin').id;
    assert.equal((await reset(admin,adminId,'adminnew8')).data.signedOut,true);
    assert.equal((await request('/api/me',{},admin)).res.status,401);
    await stop();await launch();
    await login('admin','adminnew8');
    const memberSession=await login('hunan','newpass8');
    admin=await login('admin','adminnew8');
    const edit=(auth,id,overrides={})=>request('/api/users/'+id,{method:'PATCH',body:JSON.stringify({name:'更新姓名',username:'hunan',role:'member',factory:'湖南',...overrides})},auth);
    assert.equal((await edit(memberSession,memberId)).res.status,403);
    assert.equal((await edit(admin,memberId,{username:'admin'})).res.status,409);
    assert.equal((await edit(admin,memberId,{factory:'无效厂区'})).res.status,400);
    assert.equal((await edit(admin,adminId,{username:'admin',role:'member'})).res.status,400,'last admin protected');
    const edited=await edit(admin,memberId,{username:'hunan@example.com',factory:'清溪'});assert.equal(edited.res.status,200);
    assert.equal(edited.data.user.name,'更新姓名');
    assert.equal((await request('/api/me',{},memberSession)).res.status,401);
    let moved=await login('hunan@example.com','newpass8');
    assert.equal((await request('/api/orders',{},moved)).data.length,0,'new factory scope takes effect');
    assert.equal((await edit(admin,memberId,{username:'hunan@example.com',factory:'清溪',role:'admin'})).res.status,200);
    moved=await login('hunan@example.com','newpass8');
    assert.equal((await request('/api/orders',{},moved)).data.length,1,'admin sees all factories');
    assert.equal((await edit(admin,memberId,{username:'hunan@example.com',factory:'清溪',role:'member'})).res.status,200);
    assert.equal((await request('/api/users',{},moved)).res.status,401,'demotion invalidates admin sessions');
    await stop();await launch();
    const persisted=await login('hunan@example.com','newpass8');
    assert.equal((await request('/api/me',{},persisted)).data.user.factory,'清溪');
    admin=await login('admin','adminnew8');
    const makeMulti=d=>request('/api/users',{method:'POST',body:JSON.stringify({username:'multisite',name:'多厂区测试',password:'multi1234',role:'member',factories:['湖南','河源'],...d})},admin);
    assert.equal((await makeMulti({factories:[]})).res.status,400);
    assert.equal((await makeMulti({factories:['湖南','无效']})).res.status,400);
    const multiCreated=await makeMulti({});assert.equal(multiCreated.res.status,201);
    let multi=await login('multisite','multi1234');
    assert.deepEqual((await request('/api/me',{},multi)).data.user.factories,['湖南','河源']);
    assert.equal((await request('/api/orders',{},multi)).data.length,1);
    assert.equal((await fetch(base+'/api/files/'+file.data.id,{headers:{Cookie:multi.cookie}})).status,200);
    const multiFile=await upload('多厂区模型.stp',multi);
    const multiOrder={...input,fileIds:[multiFile.data.id],factory:'河源'};
    assert.equal((await request('/api/orders',{method:'POST',body:JSON.stringify({...multiOrder,factory:'印尼'})},multi)).res.status,403);
    assert.equal((await request('/api/orders',{method:'POST',body:JSON.stringify(multiOrder)},multi)).res.status,201);
    const scopes=fs=>request('/api/users/'+multiCreated.data.id,{method:'PATCH',body:JSON.stringify({name:'多厂区测试',username:'multisite',role:'member',factories:fs})},admin);
    assert.equal((await scopes(['清溪','湖南','河源','印尼'])).res.status,200);
    multi=await login('multisite','multi1234');assert.equal((await request('/api/me',{},multi)).data.user.factories.length,4);
    assert.equal((await request('/api/users',{},multi)).res.status,403,'all factories is not admin');
    assert.equal((await scopes(['河源'])).res.status,200);
    assert.equal((await request('/api/orders',{},multi)).res.status,401);
    await stop();await launch();multi=await login('multisite','multi1234');
    assert.deepEqual((await request('/api/me',{},multi)).data.user.factories,['河源']);
    assert.equal((await request('/api/files/'+file.data.id,{},multi)).res.status,404);
    assert.equal((await request('/api/orders',{},multi)).data.length,1);


  } finally {await stop();await rm(dir,{recursive:true,force:true});}
});
