import {test} from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {createRequire} from 'node:module';
const {init,apply}=createRequire(import.meta.url)('../production/source-inventory.cjs');
function fixture(){const db=new DatabaseSync(':memory:');init(db,Date.parse('2026-10-10T00:00:00Z'));const item={_id:'one',sourceRecordId:'source',autoRecord:true,inventoryReview:true,printStartTime:'2026-10-10T01:00:00Z',material:'PLA',weight:40,qty:2};return {db,item,data:{records:{today:{items:[item]}},inventory:{PLA:{stockG:200}}}};}
test('fresh record deducts once and durable cutover/ledger survive reinitialization and snapshot marker loss',()=>{const {db,item,data}=fixture();apply(db,data);assert.equal(data.inventory.PLA.stockG,120);assert.equal(item.inventoryReview,false);init(db,Date.now()+100000);item.inventoryReview=true;delete item.inventoryDeduction;apply(db,data);assert.equal(data.inventory.PLA.stockG,120);assert.equal(item.inventoryDeduction.grams,80);db.close();});
test('history, missing timestamp, linked orders and deleted records never auto deduct',()=>{for(const fields of [{printStartTime:'2026-10-09T23:59:59Z'},{printStartTime:undefined},{cloudJobId:'job'},{_deleted:true}]){const {db,item,data}=fixture();Object.assign(item,fields);apply(db,data);assert.equal(data.inventory.PLA.stockG,200);assert.equal(item.inventoryReview,true);db.close();}});
test('missing material, quantity and insufficient stock defer without blocking other records and retry after correction',()=>{for(const fields of [{material:'unknown'},{weight:0},{qty:0},{weight:300}]){const {db,item,data}=fixture();Object.assign(item,fields);apply(db,data);assert.equal(data.inventory.PLA.stockG,200);assert.equal(item.inventoryReview,true);Object.assign(item,{material:'PLA',weight:40,qty:2});apply(db,data);assert.equal(data.inventory.PLA.stockG,120);db.close();}});
test('ledger and stock transaction roll back together; settled quality not overridden',()=>{const {db,item,data}=fixture();db.exec('BEGIN');apply(db,data);db.exec('ROLLBACK');assert.equal(db.prepare('SELECT COUNT(*) n FROM source_inventory_ledger').get().n,0);item.inventoryReview=true;delete item.inventoryDeduction;data.inventory.PLA.stockG=200;apply(db,data);item.qualitySettled=true;delete item.inventoryDeduction;apply(db,data);assert.equal(item.inventoryDeduction,undefined);assert.equal(data.inventory.PLA.stockG,120);db.close();});
