# Generated by Django 5.2.12 on 2026-03-25 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(blank=True, max_length=500)),
                ('subject', models.CharField(blank=True, max_length=500)),
                ('sender', models.CharField(blank=True, max_length=200)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('body_text', models.TextField(blank=True)),
                ('parsed_data', models.JSONField(blank=True, default=dict)),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('unprocessed', '未处理'), ('parsed', '已解析'), ('shipment_created', '已创建出货单'), ('parse_failed', '解析失败')], default='unprocessed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '邮件记录',
                'verbose_name_plural': '邮件记录',
                'ordering': ['-created_at'],
            },
        ),
    ]
