-- 印尼走货明细：分批入库、出库装柜分配与操作审计
-- PostgreSQL 16 / 非破坏性迁移：仅新增缺失表、字段、约束和索引。

CREATE SCHEMA IF NOT EXISTS indo_shipping;
SET search_path TO indo_shipping;

CREATE TABLE IF NOT EXISTS po_receipts (
    id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    po_item_id      INT NOT NULL,
    receipt_date    DATE NOT NULL,
    qty             DECIMAL(18,4) NOT NULL,
    batch_no        VARCHAR(64),
    notes           TEXT,
    created_at      TIMESTAMP(0) NOT NULL DEFAULT now(),
    CONSTRAINT "CK_po_receipts_qty_positive" CHECK (qty > 0),
    CONSTRAINT "FK_po_receipts_item"
        FOREIGN KEY (po_item_id) REFERENCES po_items(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS "IX_po_receipts_item" ON po_receipts(po_item_id);
CREATE INDEX IF NOT EXISTS "IX_po_receipts_date" ON po_receipts(receipt_date);

ALTER TABLE outbound ADD COLUMN IF NOT EXISTS po_item_id INT;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'FK_outbound_po_item'
          AND conrelid = 'indo_shipping.outbound'::regclass
    ) THEN
        ALTER TABLE outbound
            ADD CONSTRAINT "FK_outbound_po_item"
            FOREIGN KEY (po_item_id) REFERENCES po_items(id);
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'CK_outbound_qty_positive'
          AND conrelid = 'indo_shipping.outbound'::regclass
    ) THEN
        ALTER TABLE outbound
            ADD CONSTRAINT "CK_outbound_qty_positive"
            CHECK (qty > 0) NOT VALID;
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS "IX_outbound_po_item" ON outbound(po_item_id);

ALTER TABLE shipment_items ADD COLUMN IF NOT EXISTS outbound_id INT;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'FK_shipment_items_outbound'
          AND conrelid = 'indo_shipping.shipment_items'::regclass
    ) THEN
        ALTER TABLE shipment_items
            ADD CONSTRAINT "FK_shipment_items_outbound"
            FOREIGN KEY (outbound_id) REFERENCES outbound(id);
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS "IX_shipment_items_outbound"
    ON shipment_items(outbound_id);

CREATE TABLE IF NOT EXISTS audit_logs (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    occurred_at     TIMESTAMP(0) NOT NULL DEFAULT now(),
    user_id         INT,
    username        VARCHAR(64) NOT NULL DEFAULT '',
    module          VARCHAR(32) NOT NULL,
    action          VARCHAR(32) NOT NULL,
    entity_type     VARCHAR(64) NOT NULL,
    entity_id       VARCHAR(64) NOT NULL DEFAULT '',
    summary         VARCHAR(512) NOT NULL DEFAULT '',
    details         JSONB,
    ip_address      VARCHAR(64) NOT NULL DEFAULT ''
);
CREATE INDEX IF NOT EXISTS "IX_audit_logs_time"
    ON audit_logs(occurred_at DESC);
CREATE INDEX IF NOT EXISTS "IX_audit_logs_entity"
    ON audit_logs(entity_type, entity_id);
CREATE INDEX IF NOT EXISTS "IX_audit_logs_user"
    ON audit_logs(user_id, occurred_at DESC);
