"use client";
import { useEffect,useMemo,useRef,useState } from "react";
import { useRouter } from "next/navigation";
import { FunnelIcon } from "@heroicons/react/24/outline";
import { useComplaintData } from "@/components/data-provider";
import { ChartCard,DataTable,StatusBadge } from "@/components/ui";
import { customerOf,emptyFilters,filterComplaints,groupCount,lastMonths,parseFilters,percent,queryFor,recurrentRecords,RISK_RULES,riskRows,STATUS_COLORS,statusOf,type ComplaintFilters } from "@/lib/stats";

export default function QualityIntelligence(){
  const router=useRouter();const {records,issueTypeLabel,primarySeriesLabel}=useComplaintData();const initial=useRef<ComplaintFilters|null>(null);if(initial.current===null)initial.current=typeof window==="undefined"?emptyFilters:parseFilters(window.location.search);const [filters,setFilters]=useState<ComplaintFilters>(initial.current);const set=(key:keyof ComplaintFilters,value:string)=>setFilters(current=>({...current,[key]:value}));
  const scoped=useMemo(()=>filterComplaints(records,filters),[records,filters]);const risks=riskRows(scoped);const recurrent=recurrentRecords(scoped);const statuses=groupCount(scoped,statusOf);
  const issues=groupCount(scoped,record=>record.issueType||"未分类").slice(0,10);const series=groupCount(scoped,record=>record.primarySeries).slice(0,10);const customers=groupCount(scoped,customerOf).slice(0,10);const trend=lastMonths(scoped,12);
  const highSeries=new Set(risks.filter(row=>row.level==="高").map(row=>row.series)).size;const highSkus=new Set(risks.filter(row=>row.level==="高").map(row=>row.sku)).size;const classified=scoped.filter(record=>record.issueType).length;
  const seriesOptions=groupCount(records,record=>record.primarySeries);const skuOptions=groupCount(records,record=>record.productSku);const issueOptions=groupCount(records,record=>record.issueType||"未分类");const customerOptions=groupCount(records,customerOf);
  const go=(more:Partial<ComplaintFilters>)=>router.push(`/complaints${queryFor({...filters,...more})}`);
  const dateText=filters.from||filters.to?`${filters.from||"最早"} 至 ${filters.to||"最新"}`:"最近 12 个月";const scopeText=`${dateText} · ${filters.series?primarySeriesLabel(filters.series):"全部系列"} · ${filters.customer||"全部客户"}`;
  useEffect(()=>{window.history.replaceState(null,"",`${window.location.pathname}${queryFor(filters)}${window.location.hash}`)},[filters]);
  return <div className="dashboard-glass min-w-0 max-w-full overflow-x-clip">
    <section className="glass-strong mb-3 overflow-visible rounded-[18px] p-3"><div className="flex min-w-0 flex-wrap items-center gap-2"><span className="mr-1 inline-flex items-center gap-1.5 text-xs font-bold text-neutral-600"><FunnelIcon className="h-4 w-4 text-accent"/>统一分析范围</span><input aria-label="开始日期" type="date" value={filters.from} onChange={event=>set("from",event.target.value)} className="field h-8 py-0 text-xs"/><input aria-label="结束日期" type="date" value={filters.to} onChange={event=>set("to",event.target.value)} className="field h-8 py-0 text-xs"/><select aria-label="系列" className="field h-8 min-w-36 py-0 text-xs" value={filters.series} onChange={event=>set("series",event.target.value)}><option value="">全部系列</option>{seriesOptions.map(item=><option key={item.name} value={item.name}>{primarySeriesLabel(item.name)}</option>)}</select><select aria-label="客户" className="field h-8 min-w-36 py-0 text-xs" value={filters.customer} onChange={event=>set("customer",event.target.value)}><option value="">全部客户</option>{customerOptions.map(item=><option key={item.name}>{item.name}</option>)}</select><select aria-label="SKU" className="field h-8 min-w-32 py-0 text-xs" value={filters.sku} onChange={event=>set("sku",event.target.value)}><option value="">全部 SKU</option>{skuOptions.map(item=><option key={item.name}>{item.name}</option>)}</select><select aria-label="问题类型" className="field h-8 min-w-32 py-0 text-xs" value={filters.issue} onChange={event=>set("issue",event.target.value)}><option value="">全部问题</option>{issueOptions.map(item=><option key={item.name} value={item.name}>{item.name==="未分类"?"未分类":issueTypeLabel(item.name)}</option>)}</select><select aria-label="状态" className="field h-8 min-w-32 py-0 text-xs" value={filters.status} onChange={event=>set("status",event.target.value)}><option value="">全部状态</option><option>待分类</option><option>待处理</option><option>处理中</option><option>已关闭</option><option>未设置状态</option></select><button className="btn-secondary h-8 text-xs" onClick={()=>setFilters(emptyFilters)}>重置</button></div><p className="mt-2 truncate text-[11px] text-neutral-500" title={scopeText}>当前范围：{scopeText} · {scoped.length} / {records.length} 条投诉</p></section>
    <div className="grid min-w-0 gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric label="范围内投诉" value={scoped.length} detail="当前统一筛选"/><Metric label="高风险系列" value={highSeries} detail="触发高风险规则" bad={highSeries>0}/><Metric label="高风险 SKU" value={highSkus} detail="触发高风险规则" bad={highSkus>0}/><Metric label="重复投诉" value={recurrent.length} detail={`近 ${RISK_RULES.repeatedWindowDays} 天重复`}/><Metric label="待分类" value={scoped.length-classified} detail={percent(scoped.length-classified,scoped.length)} bad={scoped.length>classified}/><Metric label="已分类" value={classified} detail={percent(classified,scoped.length)}/><Metric label="风险组合" value={risks.length} detail="系列 + SKU + 问题"/><Metric label="客户数" value={customers.length} detail="未设置单独列示"/></div>
    <div className="mt-3 grid min-w-0 gap-3 xl:grid-cols-[minmax(0,1.35fr)_minmax(300px,1fr)]"><ChartCard className="glass-surface" title="投诉趋势" subtitle={`${scopeText} · 最近 12 个月，无数据月份补零`}><QualityTrend data={trend} onClick={key=>go({from:`${key}-01`,to:`${key}-31`})}/></ChartCard><ChartCard className="glass-surface" title="状态分布" subtitle={`${scopeText} · 缺失状态单独列示`}><QualityStatus data={statuses} total={scoped.length} onClick={status=>go({status})}/></ChartCard></div>
    <div className="mt-3 grid min-w-0 gap-3 xl:grid-cols-2"><ChartCard className="glass-surface" title="问题类型 Top 10" subtitle={`${scopeText} · 数量及真实占比`}><IssueRanking data={issues.map(item=>({key:item.name,label:item.name==="未分类"?"未分类":issueTypeLabel(item.name),value:item.count}))} total={scoped.length} onClick={issue=>go({issue})}/></ChartCard><ChartCard className="glass-surface" title="主要系列 Top 10" subtitle={`${scopeText} · 最高系列重点展示，其余系列增强对比`}><SeriesRanking data={series.map(item=>({key:item.name,label:primarySeriesLabel(item.name),value:item.count}))} total={scoped.length} onClick={seriesName=>go({series:seriesName})}/></ChartCard></div>
    <section className="glass-surface mt-3 p-4"><h2 className="font-bold">风险判定规则</h2><p className="mt-2 text-xs leading-6 text-neutral-600">重复投诉：同一 SKU（缺失时使用系列）与同一问题类型，在最近 {RISK_RULES.repeatedWindowDays} 天达到 {RISK_RULES.repeatedCount} 条；高风险：同一系列 + SKU + 问题组合达到 {RISK_RULES.highCount} 条，或相对上一等长周期增长达到 {RISK_RULES.growthHigh*100}%；中风险：达到重复阈值，或增长达到 {RISK_RULES.growthWarning*100}%。缺失问题类型不参与风险组合，除数为零时占比为 0。</p></section>
    <div id="risk-actions" className="mt-3"><DataTable pageSize={10} columns={["风险","系列","SKU","问题类型","本期","上期","变化","建议操作"]} rows={risks.map(row=>[<StatusBadge key={`${row.key}-risk`} tone={row.level==="高"?"bad":"warning"}>{row.level}</StatusBadge>,primarySeriesLabel(row.series),row.sku,issueTypeLabel(row.issue),row.count,row.previous,row.growth===null?"新增":`${row.growth>=0?"+":""}${(row.growth*100).toFixed(1)}%`,<button key={`${row.key}-action`} className="font-semibold text-accent hover:underline" onClick={()=>go({series:row.series,sku:row.sku,issue:row.issue})}>查看投诉明细</button>])}/></div>
  </div>
}

function Metric({label,value,detail,bad=false}:{label:string;value:number;detail:string;bad?:boolean}){return <div className="glass-surface min-h-[88px] p-3"><div className="label">{label}</div><div className={`mt-1 text-2xl font-bold ${bad?"text-red-600":"text-ink"}`}>{value}</div><div className="mt-0.5 text-[10px] text-neutral-500">{detail}</div></div>}
function QualityTrend({data,onClick}:{data:{label:string;value:number;key:string}[];onClick:(key:string)=>void}){if(!data.length)return <Empty text="当前范围暂无趋势数据"/>;const width=760,height=210,pad={x:34,y:26};const max=Math.max(1,...data.map(item=>item.value));const x=(index:number)=>pad.x+index/Math.max(1,data.length-1)*(width-pad.x*2);const y=(value:number)=>height-pad.y-value/max*(height-pad.y*2);const points=data.map((item,index)=>`${x(index)},${y(item.value)}`).join(" ");const area=`${pad.x},${height-pad.y} ${points} ${x(data.length-1)},${height-pad.y}`;return <div className="relative h-[224px] w-full min-w-0"><svg className="h-full w-full" viewBox={`0 0 ${width} ${height}`} preserveAspectRatio="none" role="img" aria-label="质量情报投诉趋势">{[0,.25,.5,.75,1].map(step=><line key={step} x1={pad.x} y1={y(max*step)} x2={width-pad.x} y2={y(max*step)} stroke="#e5e7eb" strokeDasharray="3 4"/>)}<polygon points={area} fill="#f36b21" opacity=".10"/><polyline points={points} fill="none" stroke="#f36b21" strokeWidth="3" vectorEffect="non-scaling-stroke"/>{data.map((item,index)=><g key={item.key}><circle cx={x(index)} cy={y(item.value)} r="4" fill="white" stroke="#f36b21" strokeWidth="2.5" vectorEffect="non-scaling-stroke"/><text x={x(index)} y={height-4} textAnchor="middle" fontSize="9" fill="#737373">{item.label.slice(5)}</text>{item.value>0&&<text x={x(index)} y={Math.max(13,y(item.value)-10)} textAnchor="middle" fontSize="10" fontWeight="700" fill="#171717">{item.value}</text>}</g>)}</svg><div className="absolute inset-x-[4%] top-[7%] bottom-[12%] flex">{data.map(item=><button key={`${item.key}-hit`} onClick={()=>onClick(item.key)} title={`${item.label}：${item.value} 条`} aria-label={`${item.label} ${item.value} 条`} className="h-full min-w-0 flex-1 rounded hover:bg-orange-100/20"/>)}</div></div>}
function QualityStatus({data,total,onClick}:{data:{name:string;count:number}[];total:number;onClick:(status:string)=>void}){if(!data.length)return <Empty text="当前范围暂无状态数据"/>;if(data.length===1){const item=data[0],color=STATUS_COLORS[item.name]||STATUS_COLORS["未设置状态"];return <div className="solid-data-layer flex h-[224px] flex-col justify-center rounded-xl p-6"><div className="grid grid-cols-[minmax(0,1fr)_auto_auto] items-center gap-5"><span className="flex min-w-0 items-center gap-3 font-semibold"><i className="h-4 w-4 shrink-0 rounded-full" style={{background:color}}/><span className="truncate">{item.name}</span></span><b className="text-4xl tabular-nums">{item.count}</b><span className="text-right text-xs text-neutral-500">占比<br/><b className="text-base text-ink">{percent(item.count,total)}</b></span></div><div className="mt-6 h-3 overflow-hidden rounded-full bg-neutral-100"><i className="block h-full rounded-full" style={{width:percent(item.count,total),background:color}}/></div><button onClick={()=>onClick(item.name)} className="mt-5 self-end text-xs font-semibold text-accent hover:underline">查看相关投诉 →</button></div>}return <div className="solid-data-layer space-y-3 rounded-xl p-4">{data.map(item=><button key={item.name} onClick={()=>onClick(item.name)} className="block w-full rounded-lg p-1 text-left hover:bg-orange-50"><div className="mb-1 flex justify-between text-xs"><span className="flex items-center gap-2 font-semibold"><i className="h-2.5 w-2.5 rounded-full" style={{background:STATUS_COLORS[item.name]||STATUS_COLORS["未设置状态"]}}/>{item.name}</span><span>{item.count} · {percent(item.count,total)}</span></div><div className="h-2 overflow-hidden rounded-full bg-neutral-100"><i className="block h-full rounded-full" style={{width:percent(item.count,total),background:STATUS_COLORS[item.name]||STATUS_COLORS["未设置状态"]}}/></div></button>)}</div>}
function IssueRanking({data,total,onClick}:{data:{key:string;label:string;value:number}[];total:number;onClick:(key:string)=>void}){if(!data.length)return <Empty text="当前范围暂无问题类型数据"/>;const max=Math.max(1,...data.map(item=>item.value));return <div className="solid-data-layer space-y-1 rounded-xl p-2">{data.map((item,index)=><button key={item.key} onClick={()=>onClick(item.key)} className="ranking-row grid w-full grid-cols-[1.5rem_minmax(110px,1fr)_minmax(110px,1.35fr)_3rem_3.5rem] items-center gap-2 rounded-lg px-2 py-1.5 text-left text-xs"><span className="grid h-5 w-5 place-items-center rounded bg-orange-50 font-bold text-orange-800">{index+1}</span><span className="break-words font-semibold">{item.label}</span><span className="h-2 overflow-hidden rounded-full bg-neutral-100"><i className="ranking-progress block h-full rounded-full bg-orange-500/90" style={{width:`${item.value/max*100}%`}}/></span><b className="text-right tabular-nums">{item.value}</b><span className="text-right tabular-nums text-neutral-500">{percent(item.value,total)}</span></button>)}</div>}
function SeriesRanking({data,total,onClick}:{data:{key:string;label:string;value:number}[];total:number;onClick:(key:string)=>void}){if(!data.length)return <Empty text="当前范围暂无系列数据"/>;const [leader,...rest]=data;const restMax=Math.max(1,...rest.map(item=>item.value));return <div><button onClick={()=>onClick(leader.key)} className="glass-attention mb-3 grid w-full grid-cols-[minmax(0,1fr)_auto_auto] items-center gap-4 rounded-xl border border-orange-200 p-4 text-left hover:border-orange-400"><span><small className="block text-[10px] font-bold text-accent">投诉最高系列</small><b className="mt-1 block truncate text-lg">{leader.label}</b></span><b className="text-3xl text-accent tabular-nums">{leader.value}</b><b className="text-sm text-orange-700">{percent(leader.value,total)}</b></button><div className="solid-data-layer space-y-1 rounded-xl p-2">{rest.map((item,index)=><button key={item.key} onClick={()=>onClick(item.key)} className="ranking-row grid w-full grid-cols-[1.5rem_minmax(90px,1fr)_minmax(90px,1fr)_3rem_3.5rem] items-center gap-2 rounded-lg px-2 py-1 text-left text-xs"><span className="font-bold text-neutral-500">{index+2}</span><span className="truncate font-semibold">{item.label}</span><span className="h-2 overflow-hidden rounded-full bg-neutral-100"><i className="ranking-progress block h-full rounded-full bg-orange-700/65" style={{width:`${item.value/restMax*100}%`}}/></span><b className="text-right tabular-nums">{item.value}</b><span className="text-right text-neutral-500">{percent(item.value,total)}</span></button>)}</div></div>}
function Empty({text}:{text:string}){return <div className="grid h-[224px] place-items-center rounded-xl border border-dashed border-line bg-white/70 text-xs text-neutral-400">{text}</div>}
