"use client";
import { useEffect,useMemo,useRef,useState,type KeyboardEvent } from "react";
import { createPortal } from "react-dom";
import { useRouter } from "next/navigation";
import { ArrowPathIcon,ChevronRightIcon,FunnelIcon,PencilSquareIcon } from "@heroicons/react/24/outline";
import { useComplaintData } from "@/components/data-provider";
import { ChartCard,DataTable,StatusBadge } from "@/components/ui";
import { customerOf,dashboardDateRange,emptyFilters,filterComplaints,groupCount,MISSING,percent,queryFor,repeatSummary,RISK_RULES,riskRows,STATUS_COLORS,statusOf,trendForRange,type DashboardRange,type RiskRow,type TrendPoint } from "@/lib/stats";

const rangeLabels:Record<DashboardRange,string>={month:"本月","prev-month":"上月","3m":"最近 3 个月","6m":"最近 6 个月",year:"本年度",custom:"自定义月份"};
type DashboardFilters={range:DashboardRange;series:string;customer:string;from:string;to:string};
const defaults:DashboardFilters={range:"6m",series:"",customer:"",from:"",to:""};
const dashboardFilterStorageKey="toyqms_dashboard_filters";
const monthStart=(month:string)=>month?`${month}-01`:"";
const monthEnd=(month:string)=>{if(!/^\d{4}-\d{2}$/.test(month))return "";const [year,index]=month.split("-").map(Number);return `${month}-${String(new Date(year,index,0).getDate()).padStart(2,"0")}`};
const currentMonth=()=>{const today=new Date();return `${today.getFullYear()}-${String(today.getMonth()+1).padStart(2,"0")}`};
function readDashboardFilters(){
  if(typeof window==="undefined")return defaults;const params=new URLSearchParams(window.location.search);const hasUrl=["range","series","customer","from","to"].some(key=>params.has(key));
  if(hasUrl){const range=params.get("range") as DashboardRange;return {range:Object.hasOwn(rangeLabels,range)?range:"6m",series:params.get("series")||"",customer:params.get("customer")||"",from:params.get("from")||"",to:params.get("to")||""}}
  try{const saved=JSON.parse(window.localStorage.getItem(dashboardFilterStorageKey)||"null") as Partial<DashboardFilters>|null;const range=saved?.range as DashboardRange;if(saved)return {range:Object.hasOwn(rangeLabels,range)?range:"6m",series:typeof saved.series==="string"?saved.series:"",customer:typeof saved.customer==="string"?saved.customer:"",from:typeof saved.from==="string"?saved.from:"",to:typeof saved.to==="string"?saved.to:""}}catch{}
  return defaults;
}

export default function Dashboard(){
  const router=useRouter();const {records,loading,refresh,issueTypeLabel,primarySeriesLabel}=useComplaintData();const initial=useRef<DashboardFilters|null>(null);if(initial.current===null)initial.current=readDashboardFilters();
  const [filters,setFilters]=useState<DashboardFilters>(initial.current);const [notice,setNotice]=useState("");const [riskOpen,setRiskOpen]=useState(false);const resetting=useRef(false);const set=<K extends keyof DashboardFilters>(key:K,value:DashboardFilters[K])=>setFilters(current=>({...current,[key]:value}));
  const setRange=(range:DashboardRange)=>setFilters(current=>{if(range!=="custom")return {...current,range};const month=current.from.slice(0,7)||current.to.slice(0,7)||currentMonth();return {...current,range,from:monthStart(month),to:monthEnd(month)}});
  const period=useMemo(()=>dashboardDateRange(records,filters.range,filters.from,filters.to),[records,filters.range,filters.from,filters.to]);
  const seriesOptions=useMemo(()=>groupCount(records,record=>record.primarySeries),[records]);const customerOptions=useMemo(()=>groupCount(records,customerOf),[records]);
  const selectedSeriesRaw=seriesOptions.find(item=>item.name===filters.series||primarySeriesLabel(item.name)===filters.series)?.name||filters.series;
  const base={...emptyFilters,series:selectedSeriesRaw,customer:filters.customer};const scoped=useMemo(()=>filterComplaints(records,{...base,from:period.from,to:period.to}),[records,selectedSeriesRaw,filters.customer,period.from,period.to]);
  const previous=useMemo(()=>filterComplaints(records,{...base,from:period.previousFrom,to:period.previousTo}),[records,selectedSeriesRaw,filters.customer,period.previousFrom,period.previousTo]);
  const trends=useMemo(()=>trendForRange(scoped,period.from,period.to,period.grain),[scoped,period.from,period.to,period.grain]);
  const issues=useMemo(()=>groupCount(scoped,record=>record.issueType||"未分类").slice(0,10),[scoped]);const seriesRanking=useMemo(()=>groupCount(scoped,record=>record.primarySeries).slice(0,10),[scoped]);
  const statuses=useMemo(()=>groupCount(scoped,statusOf),[scoped]);const repeat=useMemo(()=>repeatSummary(scoped,period.to),[scoped,period.to]);const risks=useMemo(()=>riskRows(scoped),[scoped]);
  const highRisks=risks.filter(row=>row.level==="高");const highSeries=new Set(highRisks.map(row=>row.series)).size;const classified=scoped.filter(record=>!record.issueType).length;const pending=scoped.filter(record=>statusOf(record)==="待处理").length;const unset=scoped.filter(record=>statusOf(record)==="未设置状态").length;const closed=scoped.filter(record=>statusOf(record)==="已关闭").length;
  const change=previous.length?(scoped.length-previous.length)/previous.length:null;const rapidGrowth=risks.filter(row=>row.growth!==null&&row.growth>=RISK_RULES.growthHigh).length;
  const hasOperationalStatus=scoped.some(record=>["待处理","处理中","已关闭"].includes(statusOf(record)));const longTerm=hasOperationalStatus?scoped.filter(record=>["待处理","处理中"].includes(statusOf(record))&&(new Date(`${period.to}T00:00:00`).getTime()-new Date(`${record.contactDate}T00:00:00`).getTime())/86400000>30).length:null;
  const recent=useMemo(()=>scoped.slice().sort((a,b)=>b.contactDate.localeCompare(a.contactDate)||b.updatedAt.localeCompare(a.updatedAt)).slice(0,10),[scoped]);
  const sourceCoverage=useMemo(()=>{const dates=scoped.map(record=>record.contactDate).filter(Boolean).sort();if(!dates.length)return "当前筛选范围暂无数据";const first=dates[0],last=dates[dates.length-1];return first===last?`数据覆盖 ${first}`:`数据覆盖 ${first} 至 ${last}`},[scoped]);
  const detailFilters={from:period.from,to:period.to,series:selectedSeriesRaw,customer:filters.customer};const go=(more:Record<string,string>={})=>router.push(`/complaints${queryFor({...detailFilters,...more})}`);
  const qualityUrl=`/quality-intelligence${queryFor(detailFilters)}#risk-actions`;const flash=(text:string)=>{setNotice(text);window.setTimeout(()=>setNotice(""),2200)};
  const periodName=rangeLabels[filters.range];const seriesName=filters.series||"全部系列";const customerName=filters.customer||"全部客户";const rangeText=`${period.from} 至 ${period.to}`;const scopeText=`${periodName} · ${rangeText} · ${seriesName} · ${customerName}`;const comparisonText=`对比 ${period.previousFrom} 至 ${period.previousTo}`;
  const reset=()=>{resetting.current=true;window.localStorage.removeItem(dashboardFilterStorageKey);window.history.replaceState(null,"",window.location.pathname);setFilters(defaults)};
  useEffect(()=>{if(resetting.current){resetting.current=false;window.localStorage.removeItem(dashboardFilterStorageKey);window.history.replaceState(null,"",window.location.pathname);return}const params=new URLSearchParams();params.set("range",filters.range);if(filters.series)params.set("series",filters.series);if(filters.customer)params.set("customer",filters.customer);if(filters.range==="custom"){if(filters.from)params.set("from",filters.from);if(filters.to)params.set("to",filters.to)}window.localStorage.setItem(dashboardFilterStorageKey,JSON.stringify(filters));window.history.replaceState(null,"",`${window.location.pathname}?${params}`)},[filters]);
  return <div className="dashboard-glass min-w-0 max-w-full overflow-x-clip"><div className="mb-3 flex min-w-0 flex-col justify-between gap-2 md:flex-row md:items-center"><p className="min-w-0 truncate text-xs text-neutral-500" title={`统一统计范围：${scopeText}`}>统一统计范围：{scopeText}</p><div className="glass-action-group glass-strong flex shrink-0 flex-wrap justify-end gap-2 rounded-2xl p-1.5"><button className="btn-accent h-8 text-xs" onClick={async()=>{await refresh();flash("数据已刷新")}}><ArrowPathIcon className="h-3.5 w-3.5"/>刷新数据</button><button className="btn-secondary h-8 text-xs" onClick={()=>router.push(qualityUrl)}>查看详细质量情报<ChevronRightIcon className="h-3.5 w-3.5"/></button></div></div>
    <section className="glass-strong mb-3 overflow-visible rounded-[18px] p-3"><div className="flex min-w-0 flex-wrap items-center gap-2">
      <span className="mr-1 inline-flex items-center gap-1.5 text-xs font-bold text-neutral-600"><FunnelIcon className="h-4 w-4 text-accent"/>全局筛选</span>
      <select aria-label="统计周期" className="field h-8 min-w-32 py-0 text-xs font-semibold" value={filters.range} onChange={event=>setRange(event.target.value as DashboardRange)}>{Object.entries(rangeLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select>
      <SearchCombobox ariaLabel="产品系列" value={filters.series} allLabel="全部系列" options={seriesOptions.map(item=>({value:item.name===MISSING?MISSING:primarySeriesLabel(item.name),label:item.name===MISSING?"未填写":primarySeriesLabel(item.name)}))} onChange={value=>set("series",value)}/>
      <SearchCombobox ariaLabel="客户" value={filters.customer} allLabel="全部客户" options={customerOptions.map(item=>({value:item.name,label:item.name===MISSING?"未填写":item.name}))} onChange={value=>set("customer",value)}/>
      {filters.range==="custom"&&<><label className="inline-flex items-center gap-1 text-[11px] text-neutral-500"><span>从</span><input aria-label="自定义开始月份" type="month" className="field h-8 py-0 text-xs" value={filters.from.slice(0,7)} onChange={event=>set("from",monthStart(event.target.value))}/></label><label className="inline-flex items-center gap-1 text-[11px] text-neutral-500"><span>至</span><input aria-label="自定义结束月份" type="month" className="field h-8 py-0 text-xs" value={filters.to.slice(0,7)} onChange={event=>set("to",monthEnd(event.target.value))}/></label></>}
      <button className="btn-secondary h-8 text-xs" onClick={reset}>重置</button>
    </div><p className="mt-2 truncate text-[11px] text-neutral-500" title={scopeText}>当前范围：{scopeText}</p></section>
    {!records.length&&!loading&&<div className="mb-3 rounded-xl border border-orange-200 bg-orange-50 p-4 text-sm text-orange-900">尚未导入投诉数据。请前往“导入中心”上传工作簿，或在投诉数据页新增记录。</div>}
    <div className="grid min-w-0 gap-3 sm:grid-cols-2 xl:grid-cols-4">
      <MainMetric label="投诉总数" value={scoped.length} detail={scopeText} onClick={()=>go()}/>
      <MainMetric label="本期投诉" value={scoped.length} detail={`${periodName} · ${rangeText}`} onClick={()=>go()}/>
      <StatusMetric classified={classified} pending={pending} unset={unset} onClick={()=>go()}/>
      <MainMetric label="高风险问题组合" value={`${highRisks.length}组`} detail={`${scopeText} · ${highSeries} 个系列`} tone={highRisks.length?"bad":"default"} onClick={()=>setRiskOpen(true)}/>
    </div>
    <div className="glass-surface mt-3 grid min-w-0 divide-y divide-line sm:grid-cols-2 sm:divide-x sm:divide-y-0 xl:grid-cols-4">
      <Summary className="summary-closed" label="已关闭" value={closed} onClick={()=>go({status:"已关闭"})}/>
      <Summary label="重复问题" value={`${repeat.groups.length}组`} detail={`涉及 ${repeat.records.length} 条投诉 · SKU ${repeat.skuGroups} / 系列备用 ${repeat.seriesFallbackGroups}`} onClick={()=>router.push(qualityUrl)}/>
      <Summary label="环比变化" value={change===null?(scoped.length?"新增":"—"):`${change>=0?"+":""}${(change*100).toFixed(1)}%`} detail={`${comparisonText} · ${previous.length} → ${scoped.length}`} tone={change!==null&&change>0?"bad":"default"} onClick={()=>go()}/>
      <Summary label="高风险系列" value={`${highSeries}个`} detail="高风险组合所在系列" tone={highSeries?"bad":"default"} onClick={()=>router.push(qualityUrl)}/>
    </div>
    <div className="mt-3 grid min-w-0 gap-3 xl:grid-cols-[minmax(0,1.85fr)_minmax(280px,1fr)]">
      <ChartCard className="glass-surface" title="投诉趋势" subtitle={`${scopeText} · 按${period.grain==="day"?"日":period.grain==="week"?"周":"月"}显示 · ${sourceCoverage}`}><LineTrend data={trends} onClick={point=>go({from:point.from,to:point.to})}/></ChartCard>
      <ChartCard className="glass-surface" title="投诉状态分布" subtitle={`${scopeText} · 缺失状态单独列示`}><StatusDistribution data={statuses} total={scoped.length} onClick={status=>go({status})}/></ChartCard>
    </div>
    <div className="mt-3 grid min-w-0 gap-3 xl:grid-cols-2">
      <ChartCard className="glass-surface" title="问题类型 Top 10" subtitle={`${scopeText} · 数量及占比`}><HorizontalRanking data={issues.map(item=>({key:item.name,label:item.name==="未分类"?"未分类":issueTypeLabel(item.name),value:item.count}))} total={scoped.length} color="#f36b21" onClick={key=>go({issue:key})}/></ChartCard>
      <ChartCard className="glass-surface" title="产品系列 Top 10" subtitle={`${scopeText} · 按投诉数量降序`}><SeriesRanking data={seriesRanking.map(item=>({key:item.name,label:primarySeriesLabel(item.name),value:item.count}))} total={scoped.length} onClick={key=>go({series:key})}/></ChartCard>
    </div>
    <section className="glass-surface mt-3 p-3"><div className="mb-2 flex items-center justify-between gap-3"><div><h2 className="text-sm font-bold">重点风险摘要</h2><p className="text-[10px] text-neutral-500">{scopeText} · 无法可靠计算时显示 —</p></div></div><div className="grid min-w-0 divide-y divide-line sm:grid-cols-2 sm:divide-x sm:divide-y-0 xl:grid-cols-5"><RiskItem label="高风险系列" value={`${highSeries}个`} onClick={()=>router.push(qualityUrl)}/><RiskItem label="重复问题组合" value={`${repeat.groups.length}组`} onClick={()=>router.push(qualityUrl)}/><RiskItem label="涉及重复投诉" value={`${repeat.records.length}条`} onClick={()=>router.push(qualityUrl)}/><RiskItem label="长期未处理" value={longTerm??"—"} onClick={()=>router.push(qualityUrl)}/><RiskItem label="快速增长问题" value={rapidGrowth} tone={rapidGrowth?"bad":"default"} onClick={()=>router.push(qualityUrl)}/></div></section>
    <div className="mt-3 min-w-0"><ChartCard className="glass-surface" title="最近投诉" subtitle={`${scopeText} · 最近 ${recent.length} 条`}><DataTable pageSize={10} columns={["日期","客户","产品系列","SKU","问题类型","状态","操作"]} rows={recent.map(record=>[record.contactDate,customerOf(record),primarySeriesLabel(record.primarySeries),record.productSku,record.issueType?issueTypeLabel(record.issueType):"未分类",<StatusPill key={`status-${record.id}`} status={statusOf(record)}/>,<button key={`edit-${record.id}`} onClick={()=>go({q:record.sourceSubmissionId||record.id})} className="inline-flex items-center gap-1 whitespace-nowrap rounded-md border border-line px-2 py-1 text-[11px] font-semibold hover:border-accent hover:text-accent"><PencilSquareIcon className="h-3.5 w-3.5"/>查看／编辑</button>])}/></ChartCard></div>
    {riskOpen&&<RiskDrawer rows={highRisks} recordsTotal={scoped.length} scopeText={scopeText} primarySeriesLabel={primarySeriesLabel} issueTypeLabel={issueTypeLabel} close={()=>setRiskOpen(false)} openComplaints={row=>go({series:row.series,sku:row.sku,issue:row.issue})}/>}
    {notice&&<div className="glass-floating glass-strong fixed right-6 top-20 z-50 rounded-xl px-4 py-3 text-sm font-semibold text-ink shadow-xl">{notice}</div>}
  </div>
}

type ComboOption={value:string;label:string};
function SearchCombobox({ariaLabel,value,allLabel,options,onChange}:{ariaLabel:string;value:string;allLabel:string;options:ComboOption[];onChange:(value:string)=>void}){
  const root=useRef<HTMLDivElement>(null);const menu=useRef<HTMLDivElement>(null);const input=useRef<HTMLInputElement>(null);const [open,setOpen]=useState(false);const [query,setQuery]=useState("");const [active,setActive]=useState(0);const [rect,setRect]=useState<DOMRect|null>(null);
  const selected=options.find(option=>option.value===value);const display=value?(selected?.label||value):allLabel;const allOptions=[{value:"",label:allLabel},...options];const filtered=allOptions.filter(option=>!query||option.label.toLocaleLowerCase("zh-CN").includes(query.toLocaleLowerCase("zh-CN")));
  const openMenu=()=>{setRect(root.current?.getBoundingClientRect()||null);setQuery("");setActive(Math.max(0,allOptions.findIndex(option=>option.value===value)));setOpen(true)};
  const close=()=>{setOpen(false);setQuery("")};const choose=(option:ComboOption)=>{onChange(option.value);close();input.current?.focus()};
  useEffect(()=>{if(!open)return;const outside=(event:MouseEvent)=>{const target=event.target as Node;if(!root.current?.contains(target)&&!menu.current?.contains(target))close()};const reposition=()=>setRect(root.current?.getBoundingClientRect()||null);document.addEventListener("mousedown",outside);window.addEventListener("resize",reposition);window.addEventListener("scroll",reposition,true);return()=>{document.removeEventListener("mousedown",outside);window.removeEventListener("resize",reposition);window.removeEventListener("scroll",reposition,true)}},[open]);
  const keyDown=(event:KeyboardEvent<HTMLInputElement>)=>{if(event.key==="Escape"){event.preventDefault();close();return}if(event.key==="ArrowDown"){event.preventDefault();if(!open)openMenu();else setActive(index=>Math.min(filtered.length-1,index+1));return}if(event.key==="ArrowUp"){event.preventDefault();setActive(index=>Math.max(0,index-1));return}if(event.key==="Enter"&&open&&filtered[active]){event.preventDefault();choose(filtered[active])}};
  return <div ref={root} className="relative min-w-0"><input ref={input} role="combobox" aria-label={ariaLabel} aria-expanded={open} aria-autocomplete="list" className={`field h-8 w-44 min-w-0 py-0 pr-8 text-xs ${value?"is-filtered":""}`} value={open?query:display} onFocus={openMenu} onClick={()=>!open&&openMenu()} onChange={event=>{setQuery(event.target.value);setActive(0);if(!open)openMenu()}} onKeyDown={keyDown}/><button type="button" tabIndex={-1} aria-label={`展开${ariaLabel}`} onMouseDown={event=>event.preventDefault()} onClick={()=>open?close():openMenu()} className="absolute inset-y-0 right-0 grid w-8 place-items-center text-neutral-400"><ChevronRightIcon className={`h-3.5 w-3.5 transition ${open?"rotate-90":"rotate-90"}`}/></button>{open&&rect&&createPortal(<div ref={menu} role="listbox" className="glass-dropdown glass-strong fixed z-[100] max-h-64 overflow-y-auto rounded-2xl p-1.5" style={{left:rect.left,top:rect.bottom+6,width:Math.max(rect.width,220)}}>{filtered.length?filtered.map((option,index)=><button key={`${option.value}-${index}`} role="option" aria-selected={option.value===value} onMouseDown={event=>event.preventDefault()} onClick={()=>choose(option)} onMouseEnter={()=>setActive(index)} className={`flex w-full items-center justify-between rounded-xl px-3 py-2 text-left text-xs ${index===active?"bg-orange-50 text-orange-800":option.value===value?"font-semibold text-accent":"text-neutral-700 hover:bg-neutral-50"}`}><span className="truncate">{option.label}</span>{option.value===value&&<span className="text-accent">✓</span>}</button>):<div className="px-3 py-6 text-center text-xs text-neutral-500">未找到匹配数据</div>}</div>,document.body)}</div>
}
function RiskDrawer({rows,recordsTotal,scopeText,primarySeriesLabel,issueTypeLabel,close,openComplaints}:{rows:RiskRow[];recordsTotal:number;scopeText:string;primarySeriesLabel:(value:string)=>string;issueTypeLabel:(value:string)=>string;close:()=>void;openComplaints:(row:RiskRow)=>void}){
  useEffect(()=>{const key=(event:globalThis.KeyboardEvent)=>{if(event.key==="Escape")close()};window.addEventListener("keydown",key);return()=>window.removeEventListener("keydown",key)},[close]);
  return <div className="fixed inset-0 z-[90] flex justify-end bg-black/25 p-3 backdrop-blur-[2px]" onMouseDown={close}><section role="dialog" aria-modal="true" aria-label="高风险问题组合明细" className="glass-modal glass-strong flex h-full w-full max-w-6xl flex-col overflow-hidden rounded-[18px]" onMouseDown={event=>event.stopPropagation()}><header className="flex items-start justify-between gap-4 border-b border-white/60 px-5 py-4"><div><h2 className="text-lg font-bold">高风险问题组合明细 · {rows.length}组</h2><p className="mt-1 text-[11px] text-neutral-600">{scopeText} · 当前筛选共 {recordsTotal} 条投诉</p><p className="mt-0.5 text-[11px] text-neutral-600">组合口径：有 SKU 时使用 SKU + 问题类型；SKU 缺失时使用产品系列 + 问题类型。</p></div><button onClick={close} className="rounded-full border border-white/70 bg-white/80 px-3 py-1.5 text-xs font-semibold hover:bg-white">关闭</button></header><div className="min-h-0 flex-1 overflow-auto p-4"><table className="w-full min-w-[1280px] overflow-hidden rounded-xl bg-white text-left text-xs"><thead className="sticky top-0 z-10 bg-neutral-100 text-[10px] uppercase tracking-wide text-neutral-600"><tr>{["风险","客户","产品系列","SKU／备用组合","问题类型","本期","上期","近90天","增长率","最近发生","触发规则","涉及投诉","操作"].map(label=><th key={label} className="whitespace-nowrap px-3 py-2">{label}</th>)}</tr></thead><tbody className="divide-y divide-line">{rows.map(row=><tr key={row.key} className="hover:bg-orange-50/40"><td className="px-3 py-2"><StatusBadge tone={row.level==="高"?"bad":"warning"}>{row.level}风险</StatusBadge></td><td className="max-w-64 px-3 py-2"><CustomerScope customers={row.customers}/></td><td className="whitespace-nowrap px-3 py-2 font-semibold">{primarySeriesLabel(row.series)}</td><td className="px-3 py-2">{row.strategy==="sku"?row.sku:<span><b>SKU缺失</b><br/><small className="text-neutral-600">系列 + 问题类型</small></span>}</td><td className="whitespace-nowrap px-3 py-2">{issueTypeLabel(row.issue)}</td><td className="px-3 py-2 text-center font-bold">{row.count}</td><td className="px-3 py-2 text-center">{row.previous}</td><td className="px-3 py-2 text-center">{row.count}</td><td className="whitespace-nowrap px-3 py-2">{row.growth===null?"新增":`${row.growth>=0?"+":""}${(row.growth*100).toFixed(1)}%`}</td><td className="whitespace-nowrap px-3 py-2">{row.lastDate}</td><td className="max-w-52 px-3 py-2">{row.triggerRules.join("；")}</td><td className="px-3 py-2 text-center">{row.recordIds.length}</td><td className="px-3 py-2"><button onClick={()=>openComplaints(row)} className="whitespace-nowrap rounded-lg border border-line px-2 py-1 font-semibold hover:border-accent hover:text-accent">查看投诉</button></td></tr>)}</tbody></table>{!rows.length&&<div className="grid h-48 place-items-center rounded-xl bg-white text-sm text-neutral-500">当前筛选没有高风险问题组合</div>}</div></section></div>
}
function CustomerScope({customers}:{customers:string[]}){const [expanded,setExpanded]=useState(false);const preview=customers.slice(0,3).join("、");return <div className="min-w-52"><button type="button" aria-expanded={expanded} onClick={()=>setExpanded(value=>!value)} className="text-left leading-5 hover:text-accent"><b>涉及客户{customers.length}个：</b>{expanded?customers.join("、"):<>{preview}{customers.length>3?"等":""}</>}</button>{customers.length>3&&<div className="mt-0.5 text-[10px] font-semibold text-accent">{expanded?"收起名单":"展开完整名单"}</div>}</div>}
function MainMetric({label,value,detail,tone="default",onClick}:{label:string;value:string|number;detail:string;tone?:"default"|"warning"|"bad";onClick:()=>void}){const color={default:"text-ink",warning:"text-amber-600",bad:"text-red-600"}[tone];return <button onClick={onClick} className={`glass-surface flex h-[116px] min-w-0 flex-col justify-between p-4 text-left transition hover:border-orange-200 hover:shadow-md ${tone==="bad"?"glass-risk":tone==="warning"?"glass-attention":""}`}><div className="label">{label}</div><div className={`text-3xl font-bold tracking-tight ${color}`}>{value}</div><div className="truncate text-[11px] text-neutral-500" title={detail}>{detail}</div></button>}
function StatusMetric({classified,pending,unset,onClick}:{classified:number;pending:number;unset:number;onClick:()=>void}){return <button onClick={onClick} className="glass-surface glass-status-muted flex h-[116px] min-w-0 flex-col justify-between p-4 text-left transition hover:border-orange-200 hover:shadow-md"><div className="label">分类与处理状态</div><div className="grid grid-cols-3 divide-x divide-line"><MetricState label="待分类" value={classified} color={STATUS_COLORS["待分类"]}/><MetricState label="待处理" value={pending} color={STATUS_COLORS["待处理"]}/><MetricState label="未设置" value={unset} color={STATUS_COLORS["未设置状态"]}/></div></button>}
function MetricState({label,value,color}:{label:string;value:number;color:string}){return <span className="min-w-0 px-2 first:pl-0 last:pr-0"><span className="block truncate text-[10px] font-semibold text-neutral-500">{label}</span><span className="mt-1 flex items-center gap-1.5 text-xl font-bold tabular-nums"><i className="h-2 w-2 shrink-0 rounded-full" style={{background:color}}/>{value}</span></span>}
function Summary({label,value,detail,tone="default",className="",onClick}:{label:string;value:string|number;detail?:string;tone?:"default"|"bad";className?:string;onClick:()=>void}){return <button onClick={onClick} className={`min-w-0 p-3 text-left hover:bg-neutral-50 ${className}`}><div className="text-[11px] font-semibold text-neutral-500">{label}</div><div className={`mt-1 text-xl font-bold ${tone==="bad"?"text-red-600":"text-ink"}`}>{value}</div><div className="mt-0.5 truncate text-[10px] text-neutral-400">{detail||"当前筛选"}</div></button>}
function LineTrend({data,onClick}:{data:TrendPoint[];onClick:(point:TrendPoint)=>void}){if(!data.length)return <Empty text="当前范围暂无趋势数据"/>;const width=760,height=176,pad={x:30,y:22};const max=Math.max(1,...data.map(item=>item.value));const x=(index:number)=>pad.x+(data.length===1?0:index/(data.length-1))*(width-pad.x*2);const y=(value:number)=>height-pad.y-value/max*(height-pad.y*2);const points=data.map((item,index)=>`${x(index)},${y(item.value)}`).join(" ");const area=`${pad.x},${height-pad.y} ${points} ${x(data.length-1)},${height-pad.y}`;const labelEvery=Math.max(1,Math.ceil(data.length/8));return <div className="relative h-[190px] w-full min-w-0"><svg className="h-full w-full overflow-visible" viewBox={`0 0 ${width} ${height}`} preserveAspectRatio="none" role="img" aria-label="投诉趋势折线图"><line x1={pad.x} y1={height-pad.y} x2={width-pad.x} y2={height-pad.y} stroke="#e5e5e5"/><polygon points={area} fill="#f36b21" opacity=".10"/><polyline points={points} fill="none" stroke="#f36b21" strokeWidth="3" vectorEffect="non-scaling-stroke"/>{data.map((item,index)=><g key={`${item.from}-${item.to}`}><circle cx={x(index)} cy={y(item.value)} r="4.5" fill="white" stroke="#f36b21" strokeWidth="3" vectorEffect="non-scaling-stroke"/>{(index%labelEvery===0||index===data.length-1)&&<text x={x(index)} y={height-3} textAnchor="middle" fontSize="10" fill="#737373">{item.label}</text>}{item.value>0&&<text x={x(index)} y={Math.max(12,y(item.value)-9)} textAnchor="middle" fontSize="10" fontWeight="700" fill="#171717">{item.value}</text>}</g>)}</svg><div className="absolute inset-x-[4%] top-[8%] bottom-[12%] flex">{data.map(item=><button key={`${item.from}-${item.to}-hit`} onClick={()=>onClick(item)} title={`${item.label}：${item.value} 条`} aria-label={`${item.label} ${item.value} 条`} className="h-full min-w-0 flex-1 rounded hover:bg-orange-100/20"/>)}</div></div>}
function StatusDistribution({data,total,onClick}:{data:{name:string;count:number}[];total:number;onClick:(status:string)=>void}){if(!data.length)return <Empty text="当前范围暂无状态数据"/>;if(data.length===1){const item=data[0];return <div className="status-solid-layer grid h-[190px] place-items-center rounded-xl border border-line p-4 text-center"><div><i className="mx-auto mb-2 block h-3 w-3 rounded-full" style={{background:STATUS_COLORS[item.name]||STATUS_COLORS["未设置状态"]}}/><div className="text-sm font-semibold text-neutral-600">{item.name}</div><div className="mt-1 text-3xl font-bold tabular-nums">{item.count}</div><div className="mt-1 text-xs text-neutral-500">占比 {percent(item.count,total)}</div><button onClick={()=>onClick(item.name)} className="mt-3 text-xs font-semibold text-accent hover:underline">查看{item.name}投诉</button></div></div>}return <div className="space-y-3 py-1">{data.map(item=><button key={item.name} onClick={()=>onClick(item.name)} className="grid w-full grid-cols-[minmax(5.5rem,auto)_minmax(4rem,1fr)_3rem_3.5rem] items-center gap-3 rounded-lg px-1 py-1 text-left text-xs hover:bg-orange-50/40"><span className="flex min-w-0 items-center gap-2 font-semibold"><i className="h-2.5 w-2.5 shrink-0 rounded-full" style={{background:STATUS_COLORS[item.name]||STATUS_COLORS["未设置状态"]}}/><span className="truncate">{item.name}</span></span><span className="h-2 min-w-0 overflow-hidden rounded-full bg-neutral-100"><i className="block h-full rounded-full" style={{width:percent(item.count,total),background:STATUS_COLORS[item.name]||STATUS_COLORS["未设置状态"]}}/></span><b className="text-right tabular-nums">{item.count}</b><span className="text-right tabular-nums text-neutral-500">{percent(item.count,total)}</span></button>)}</div>}
function HorizontalRanking({data,total,color,onClick}:{data:{key:string;label:string;value:number}[];total:number;color:string;onClick:(key:string)=>void}){const max=Math.max(1,...data.map(item=>item.value));if(!data.length)return <Empty text="当前范围暂无问题类型数据"/>;return <div className="solid-data-layer space-y-1 rounded-xl p-2">{data.map((item,index)=><button key={item.key} onClick={()=>onClick(item.key)} className="ranking-row grid w-full min-w-0 grid-cols-[1.5rem_minmax(105px,1fr)_minmax(100px,1.25fr)_3rem_3.5rem] items-center gap-2 rounded-lg px-2 py-1 text-left text-xs"><span className="grid h-5 w-5 place-items-center rounded bg-orange-50 font-bold text-orange-800">{index+1}</span><span className="break-words font-semibold leading-4">{item.label}</span><span className="h-2 overflow-hidden rounded-full bg-neutral-100"><i className="ranking-progress block h-full rounded-full" style={{width:`${item.value/max*100}%`,background:color}}/></span><b className="text-right tabular-nums">{item.value}</b><span className="text-right tabular-nums text-neutral-500">{percent(item.value,total)}</span></button>)}</div>}
function SeriesRanking({data,total,onClick}:{data:{key:string;label:string;value:number}[];total:number;onClick:(key:string)=>void}){if(!data.length)return <Empty text="当前范围暂无系列数据"/>;const [leader,...rest]=data;const restMax=Math.max(1,...rest.map(item=>item.value));return <div><button onClick={()=>onClick(leader.key)} className="glass-attention mb-3 grid w-full grid-cols-[minmax(0,1fr)_auto_auto] items-center gap-4 rounded-xl border border-orange-200 p-3 text-left hover:border-orange-400"><span><small className="block text-[10px] font-bold text-accent">投诉最高系列</small><b className="mt-1 block truncate text-base">{leader.label}</b></span><b className="text-3xl text-accent tabular-nums">{leader.value}</b><b className="text-sm text-orange-700">{percent(leader.value,total)}</b></button><div className="solid-data-layer space-y-1 rounded-xl p-2">{rest.map((item,index)=><button key={item.key} onClick={()=>onClick(item.key)} className="ranking-row grid w-full grid-cols-[1.5rem_minmax(90px,1fr)_minmax(90px,1fr)_3rem_3.5rem] items-center gap-2 rounded-lg px-2 py-1 text-left text-xs"><span className="font-bold text-neutral-500">{index+2}</span><span className="truncate font-semibold">{item.label}</span><span className="h-2 overflow-hidden rounded-full bg-neutral-100"><i className="ranking-progress block h-full rounded-full bg-orange-700/65" style={{width:`${item.value/restMax*100}%`}}/></span><b className="text-right tabular-nums">{item.value}</b><span className="text-right tabular-nums text-neutral-500">{percent(item.value,total)}</span></button>)}</div></div>}
function RiskItem({label,value,tone="default",onClick}:{label:string;value:string|number;tone?:"default"|"bad";onClick:()=>void}){return <button onClick={onClick} className="flex min-w-0 items-center justify-between gap-3 px-3 py-2 text-left text-xs hover:bg-neutral-50 hover:text-accent"><span className="truncate text-neutral-600">{label}</span><span className={`shrink-0 text-base font-bold ${tone==="bad"?"text-red-600":"text-ink"}`}>{value}</span></button>}
function StatusPill({status}:{status:string}){return <StatusBadge tone={status==="待分类"||status==="待处理"?"warning":status==="已关闭"?"good":status==="处理中"?"info":"neutral"}><i className="mr-1 h-1.5 w-1.5 rounded-full" style={{background:STATUS_COLORS[status]||STATUS_COLORS["未设置状态"]}}/>{status}</StatusBadge>}
function Empty({text}:{text:string}){return <div className="grid h-44 place-items-center rounded-lg border border-dashed border-line bg-neutral-50 text-xs text-neutral-400">{text}</div>}
