"use client";
import { FormEvent,useEffect,useState } from "react";
import { useRouter } from "next/navigation";
import { useAuth } from "@/components/auth-provider";
import { EyeIcon,EyeSlashIcon,LockClosedIcon,UserIcon } from "@heroicons/react/24/outline";

export default function LoginPage(){
  const {user,login}=useAuth();const router=useRouter();const [loginName,setLoginName]=useState(""),[password,setPassword]=useState(""),[show,setShow]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState("");
  useEffect(()=>{if(user&&!user.mustChangePassword)router.replace("/dashboard")},[user,router]);
  const submit=async(event:FormEvent)=>{event.preventDefault();setBusy(true);setError("");try{const next=await login(loginName,password);if(!next.mustChangePassword)router.replace("/dashboard")}catch(reason){setError(reason instanceof Error?reason.message:"无法登录") }finally{setBusy(false)}};
  if(user?.mustChangePassword)return <FirstPasswordChange/>;
  return <LoginFrame><div className="mx-auto w-full max-w-sm"><div className="md:hidden"><div className="text-2xl font-black">Toy<span className="text-accent">QMS</span></div><div className="mt-1 text-[10px] tracking-[.15em] text-neutral-500">玩具质量管理系统</div></div><div className="mt-10 md:mt-0"><div className="text-xs font-bold uppercase tracking-[.18em] text-accent">账户登录</div><h2 className="mt-2 text-2xl font-bold">欢迎使用 ToyQMS</h2><p className="mt-2 text-sm text-neutral-500">请输入登录名称和密码。</p></div><form onSubmit={submit} className="mt-8 space-y-4"><label className="block"><span className="mb-1.5 block text-xs font-semibold text-neutral-600">登录名称</span><span className="relative block"><UserIcon className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-neutral-400"/><input autoFocus autoComplete="username" value={loginName} onChange={event=>setLoginName(event.target.value)} className="field h-11 w-full pl-10" placeholder="输入登录名称"/></span></label><label className="block"><span className="mb-1.5 block text-xs font-semibold text-neutral-600">密码</span><span className="relative block"><LockClosedIcon className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-neutral-400"/><input autoComplete="current-password" type={show?"text":"password"} value={password} onChange={event=>setPassword(event.target.value)} className="field h-11 w-full px-10" placeholder="输入密码"/><button type="button" onClick={()=>setShow(value=>!value)} className="absolute right-3 top-1/2 -translate-y-1/2 text-neutral-400" aria-label={show?"隐藏密码":"显示密码"}>{show?<EyeSlashIcon className="h-4 w-4"/>:<EyeIcon className="h-4 w-4"/>}</button></span></label>{error&&<div className="rounded-xl border border-red-200 bg-red-50 px-3 py-2 text-xs text-red-700">{error}</div>}<button disabled={busy||!loginName.trim()||!password} className="btn-accent h-11 w-full justify-center disabled:opacity-50">{busy?"正在登录…":"登录"}</button></form><p className="mt-6 text-center text-[11px] text-neutral-400">首次登录后必须修改初始密码。</p><StorageModeHint/></div></LoginFrame>
}

function LoginFrame({children}:{children:React.ReactNode}){return <main className="relative grid min-h-screen place-items-center overflow-hidden bg-[#f3f4f4] p-5"><div className="pointer-events-none absolute -left-40 -top-44 h-[34rem] w-[34rem] rounded-full bg-slate-300/45 blur-3xl"/><div className="pointer-events-none absolute -right-36 top-0 h-[30rem] w-[30rem] rounded-full bg-orange-200/45 blur-3xl"/><section className="relative grid w-full max-w-5xl overflow-hidden rounded-[28px] border border-white/80 bg-white/70 shadow-[0_24px_70px_rgba(15,23,42,.14)] backdrop-blur-2xl md:grid-cols-[1.05fr_.95fr]"><div className="hidden min-h-[560px] flex-col justify-between bg-[#141414] p-10 text-white md:flex"><div><div className="text-3xl font-black tracking-tight">Toy<span className="text-accent">QMS</span></div><div className="mt-1 text-xs tracking-[.18em] text-neutral-400">玩具质量管理系统</div></div><div><div className="h-1 w-14 rounded-full bg-accent"/><h1 className="mt-6 text-3xl font-bold leading-tight">让投诉、分析与质量行动<br/>在一个系统中闭环。</h1><p className="mt-4 max-w-sm text-sm leading-6 text-neutral-400">统一账户、统一数据与分级权限。登录后根据账户权限显示可用模块。</p></div><div className="text-xs text-neutral-500">ZURU · ToyQMS</div></div><div className="flex min-h-[560px] items-center p-7 sm:p-12">{children}</div></section></main>}
function StorageModeHint(){return <p className="mt-2 text-center text-[11px] text-neutral-400">账户与数据统一保存在后端数据库，所有设备共用同一份数据。</p>}
function FirstPasswordChange(){const {user,changeOwnPassword,logout}=useAuth();const router=useRouter();const [current,setCurrent]=useState(""),[next,setNext]=useState(""),[confirm,setConfirm]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false);const submit=async(event:FormEvent)=>{event.preventDefault();if(next!==confirm){setError("两次输入的新密码不一致。");return}setBusy(true);setError("");try{await changeOwnPassword(current,next);router.replace("/dashboard")}catch(reason){setError(reason instanceof Error?reason.message:"无法修改密码")}finally{setBusy(false)}};return <LoginFrame><div className="mx-auto w-full max-w-sm"><div className="text-xs font-bold uppercase tracking-[.18em] text-accent">首次登录安全设置</div><h2 className="mt-2 text-2xl font-bold">请修改初始密码</h2><p className="mt-2 text-sm text-neutral-500">{user?.name}，新密码至少 8 个字符。修改完成后才能进入系统。</p><form onSubmit={submit} className="mt-7 space-y-4">{[["当前密码",current,setCurrent,"current-password"],["新密码",next,setNext,"new-password"],["确认新密码",confirm,setConfirm,"new-password"]].map(([label,value,setter,auto])=><label key={String(label)} className="block"><span className="mb-1.5 block text-xs font-semibold text-neutral-600">{String(label)}</span><input type="password" autoComplete={String(auto)} value={String(value)} onChange={event=>(setter as (value:string)=>void)(event.target.value)} className="field h-11 w-full"/></label>)}{error&&<div className="rounded-xl border border-red-200 bg-red-50 px-3 py-2 text-xs text-red-700">{error}</div>}<button disabled={busy||!current||next.length<8||!confirm} className="btn-accent h-11 w-full justify-center disabled:opacity-50">{busy?"正在保存…":"保存新密码并进入系统"}</button><button type="button" onClick={logout} className="btn-secondary h-10 w-full justify-center">退出登录</button></form></div></LoginFrame>}
