"use client";
import { useEffect, useMemo, useState } from "react";
import { ArrowDownTrayIcon, MagnifyingGlassIcon, PlusIcon, XMarkIcon } from "@heroicons/react/24/outline";

export function PageTitle({description,action,secondary,onAction,onSecondary,secondaryContent}:{title?:string;description?:string;action?:string;secondary?:string;onAction?:()=>void;onSecondary?:()=>void;secondaryContent?:React.ReactNode}){
  return <div className={`mb-4 flex flex-col justify-between gap-3 md:flex-row md:items-center ${description?"":"md:justify-end"}`}>{description&&<p className="max-w-3xl text-xs text-neutral-500">{description}</p>}<div className="flex gap-2">{secondaryContent}{secondary&&onSecondary&&<button type="button" onClick={onSecondary} className="btn-secondary"><ArrowDownTrayIcon className="h-4 w-4"/>{secondary}</button>}{action&&onAction&&<button type="button" onClick={onAction} className="btn-accent"><PlusIcon className="h-4 w-4"/>{action}</button>}</div></div>
}
export function KpiCard({label,value,change,tone="default",detail,className=""}:{label:string;value:string;change?:string;tone?:"default"|"accent"|"good"|"bad";detail?:string;className?:string}){const color={default:"text-ink",accent:"text-accent",good:"text-emerald-600",bad:"text-red-600"}[tone];return <div className={`card p-4 ${className}`}><div className="label">{label}</div><div className={`mt-2 text-2xl font-bold tracking-tight ${color}`}>{value}</div><div className="mt-1 flex items-center justify-between text-[11px]"><span className={change?.startsWith("+")?"text-red-600":"text-emerald-600"}>{change}</span><span className="text-neutral-400">{detail}</span></div></div>}
export function StatusBadge({children,tone="neutral",className=""}:{children:React.ReactNode;tone?:"neutral"|"good"|"warning"|"bad"|"info";className?:string}){const cls={neutral:"bg-neutral-100 text-neutral-600",good:"bg-emerald-50 text-emerald-700",warning:"bg-orange-50 text-orange-700",bad:"bg-red-50 text-red-700",info:"bg-blue-50 text-blue-700"}[tone];return <span className={`inline-flex whitespace-nowrap rounded-full px-2 py-0.5 text-[11px] font-bold ${cls} ${className}`}>{children}</span>}

export type FilterGroup={label:string;values?:string[];options?:{value:string;label:string}[]};
export function Filters({placeholder="搜索记录…",groups=[],searchValue,onSearch,onFilter,singleRow=false}:{placeholder?:string;groups?:FilterGroup[];searchValue?:string;onSearch?:(value:string)=>void;onFilter?:(index:number,value:string)=>void;singleRow?:boolean}){
  const [localSearch,setLocalSearch]=useState(""); const value=searchValue??localSearch;
  return <div className={`mb-4 flex gap-2 ${singleRow?"flex-row overflow-x-auto pb-1":"flex-col sm:flex-row"}`}><label className={`relative min-w-0 flex-1 ${singleRow?"w-64 min-w-[220px] flex-none":""}`}><MagnifyingGlassIcon className="absolute left-3 top-2.5 h-4 w-4 text-neutral-400"/><input value={value} onChange={e=>{setLocalSearch(e.target.value);onSearch?.(e.target.value)}} className="field w-full pl-9" placeholder={placeholder}/></label>{groups.map((g,i)=><select key={`${g.label}-${g.options?.map(option=>option.value).join("|")||g.values?.join("|")||""}`} className="field min-w-36 shrink-0" defaultValue="" onChange={e=>onFilter?.(i,e.target.value)}><option value="">{g.label}</option>{g.options?.map(option=><option key={option.value} value={option.value}>{option.label}</option>)??g.values?.map(v=><option key={v} value={v}>{v}</option>)}</select>)}</div>
}

export function DataTable({columns,rows,rowKeys,pageSize=10,stickyHeader=false,stickyHeaderTop="8rem",containedScroll=false,page:controlledPage,onPageChange,extendedPagination=false,headerTone="default"}:{columns:React.ReactNode[];rows:React.ReactNode[][];rowKeys?:React.Key[];pageSize?:number;stickyHeader?:boolean;stickyHeaderTop?:string;containedScroll?:boolean;page?:number;onPageChange?:(page:number)=>void;extendedPagination?:boolean;headerTone?:"default"|"accent"|"softAccent"}){
  const [localPage,setLocalPage]=useState(1); const [jumpPage,setJumpPage]=useState(""); const pages=Math.max(1,Math.ceil(rows.length/pageSize)); const page=controlledPage??localPage;
  const changePage=(next:number)=>{const safe=Math.min(pages,Math.max(1,next));if(controlledPage!==undefined)onPageChange?.(safe);else setLocalPage(safe)};
  useEffect(()=>{if(page>pages)changePage(pages)},[page,pages]);
  const visibleStart=(page-1)*pageSize;const visible=useMemo(()=>rows.slice(visibleStart,page*pageSize),[rows,visibleStart,page,pageSize]);
  const blockSize=extendedPagination?10:5;const blockStart=extendedPagination?Math.floor((page-1)/blockSize)*blockSize+1:Math.max(1,Math.min(page-2,pages-blockSize+1));const blockEnd=Math.min(pages,blockStart+blockSize-1);const pageNumbers=Array.from({length:blockEnd-blockStart+1},(_,index)=>blockStart+index);
  const jump=()=>{const target=Number(jumpPage);if(Number.isInteger(target)&&target>=1&&target<=pages){changePage(target);setJumpPage("")}};
  const headClass=headerTone==="accent"?"bg-accent text-white":headerTone==="softAccent"?"bg-orange-100 text-orange-950":"bg-neutral-50 text-neutral-500";
  const headSize=headerTone==="accent"?"text-sm":headerTone==="softAccent"?"text-xs":"text-[10px]";
  const scrollClass=containedScroll?"max-h-[calc(100vh-5rem)] overflow-auto overscroll-contain":stickyHeader?"overflow-visible":"overflow-x-auto";
  const headerTop=containedScroll?0:stickyHeaderTop==="12.75rem"?"11.5rem":stickyHeaderTop;
  return <div className={`card ${containedScroll||!stickyHeader?"overflow-hidden":"overflow-visible"}`}><div className={scrollClass}><table className="w-full min-w-[760px] border-separate border-spacing-0 text-left text-sm"><thead style={stickyHeader?{top:headerTop}:undefined} className={`${stickyHeader?"sticky z-30":""} border-b ${headerTone==="accent"?"border-orange-700":headerTone==="softAccent"?"border-orange-200":"border-line"}`}><tr>{columns.map((c,i)=><th key={i} className={`${headClass} ${headSize} whitespace-nowrap border-b border-inherit px-4 py-2 font-bold uppercase tracking-wider ${stickyHeader?"shadow-[0_1px_0_rgba(0,0,0,.12)]":""}`}>{c}</th>)}</tr></thead><tbody>{visible.map((r,i)=><tr key={rowKeys?.[visibleStart+i]??`${page}-${i}`} className="transition hover:bg-orange-50/30">{r.map((c,j)=><td key={j} className="border-b border-line px-4 py-2.5 text-neutral-700">{c}</td>)}</tr>)}{!visible.length&&<tr><td colSpan={columns.length} className="px-4 py-8 text-center text-neutral-400">暂无数据</td></tr>}</tbody></table></div><div className="flex flex-wrap items-center justify-between gap-2 border-t border-line px-4 py-2 text-[11px] text-neutral-500"><span>共 {rows.length} 条 · 第 {page}/{pages} 页</span><div className="flex flex-wrap items-center justify-end gap-1"><button disabled={page===1} onClick={()=>changePage(page-1)} className="rounded border border-line px-2.5 py-1 disabled:cursor-not-allowed disabled:opacity-40">上一页</button>{extendedPagination&&blockStart>1&&<button onClick={()=>changePage(Math.max(1,blockStart-blockSize))} className="rounded border border-line px-2.5 py-1">前10页</button>}{pageNumbers.map(n=><button key={n} onClick={()=>changePage(n)} className={`rounded px-2 py-1 ${n===page?"bg-accent text-white":"border border-line"}`}>{n}</button>)}{extendedPagination&&blockEnd<pages&&<button onClick={()=>changePage(blockEnd+1)} className="rounded border border-line px-2.5 py-1">后10页</button>}<button disabled={page===pages} onClick={()=>changePage(page+1)} className="rounded border border-line px-2.5 py-1 disabled:cursor-not-allowed disabled:opacity-40">下一页</button>{extendedPagination&&<div className="ml-1 flex items-center gap-1"><span>跳至</span><input aria-label="跳转页码" type="number" min={1} max={pages} value={jumpPage} onChange={event=>setJumpPage(event.target.value)} onKeyDown={event=>{if(event.key==="Enter")jump()}} className="h-7 w-14 rounded border border-line bg-white px-2 text-center outline-none focus:border-accent"/><button onClick={jump} disabled={!jumpPage} className="rounded border border-line px-2.5 py-1 disabled:opacity-40">跳转</button></div>}</div></div></div>
}
export function BarChart({data,showValues=false,amplifySmallValues=false,onItemClick}:{data:{label:string;value:number;key?:string}[];showValues?:boolean;amplifySmallValues?:boolean;onItemClick?:(item:{label:string;value:number;key?:string})=>void}){const max=Math.max(1,...data.map(d=>d.value));const heightOf=(value:number)=>{const ratio=value/max;return Math.max(amplifySmallValues?4:6,(amplifySmallValues?Math.sqrt(ratio):ratio)*100)};return <div className={`flex items-end gap-2 border-b border-line px-2 pt-6 ${amplifySmallValues?"h-48":"h-40"}`}>{data.map(d=><button type="button" disabled={!onItemClick} onClick={()=>onItemClick?.(d)} key={d.key||d.label} className="group flex h-full min-w-0 flex-1 flex-col justify-end gap-1.5 disabled:cursor-default">{d.value>0?<div className="relative w-full rounded-t bg-accent transition group-hover:bg-orange-600" style={{height:`${heightOf(d.value)}%`}}><span className={`absolute -top-5 left-1/2 -translate-x-1/2 text-[10px] font-bold tabular-nums ${showValues?"opacity-100":"opacity-0 group-hover:opacity-100"}`}>{d.value}</span></div>:<div className="h-0"/>}<span className="w-full truncate text-center text-[10px] text-neutral-500">{d.label}</span></button>)}</div>}
export function Donut({value=68,label="已解决"}:{value?:number;label?:string}){return <div className="relative mx-auto h-40 w-40 rounded-full" style={{background:`conic-gradient(#f36b21 ${value}%, #eeeeeb 0)`}}><div className="absolute inset-5 grid place-items-center rounded-full bg-white text-center"><div><div className="text-2xl font-bold">{value}%</div><div className="text-[10px] uppercase text-neutral-500">{label}</div></div></div></div>}
export function PieChart({data,showCountColumn=false}:{data:{label:string;value:number}[];showCountColumn?:boolean}){const total=data.reduce((sum,item)=>sum+item.value,0);const colors=["#f36b21","#171717","#f59e0b","#10b981","#3b82f6","#8b5cf6","#ef4444","#64748b"];let cursor=0;const gradient=data.length?data.map((item,index)=>{const start=cursor;cursor+=total?item.value/total*100:0;return `${colors[index%colors.length]} ${start}% ${cursor}%`}).join(", "):"#eeeeeb 0 100%";return <div className="grid items-center gap-4 sm:grid-cols-[10rem_1fr]"> <div className="relative mx-auto h-40 w-40 rounded-full" style={{background:`conic-gradient(${gradient})`}}><div className="absolute inset-10 grid place-items-center rounded-full bg-white text-center"><div><div className="text-xl font-bold">{total}</div><div className="text-[10px] text-neutral-500">投诉</div></div></div></div><div className="space-y-2">{showCountColumn&&<div className="grid grid-cols-[minmax(0,1fr)_3.5rem_4rem] gap-2 border-b border-line pb-2 text-[10px] font-bold text-neutral-500"><span>缺陷类型</span><span className="text-center">数量</span><span className="text-right">占比</span></div>}{data.length?data.map((item,index)=>showCountColumn?<div key={item.label} className="grid grid-cols-[minmax(0,1fr)_3.5rem_4rem] items-center gap-2 text-xs"><span className="flex min-w-0 items-center gap-2"><i className="h-2.5 w-2.5 shrink-0 rounded-full" style={{backgroundColor:colors[index%colors.length]}}/><span className="truncate">{item.label}</span></span><b className="text-center tabular-nums">{item.value}</b><b className="text-right tabular-nums">{total?(item.value/total*100).toFixed(1):"0.0"}%</b></div>:<div key={item.label} className="flex items-center justify-between gap-3 text-xs"><span className="flex min-w-0 items-center gap-2"><i className="h-2.5 w-2.5 shrink-0 rounded-full" style={{backgroundColor:colors[index%colors.length]}}/><span className="truncate">{item.label}</span></span><b>{total?(item.value/total*100).toFixed(1):"0.0"}%</b></div>):<div className="text-center text-xs text-neutral-400">暂无问题类型数据</div>}</div></div>}
export function Panel({title,children}:{title:string;children:React.ReactNode}){const [open,setOpen]=useState(false);return <><button onClick={()=>setOpen(true)} className="btn-secondary">{title}</button>{open&&<div className="fixed inset-0 z-50 flex justify-end bg-black/30" onClick={()=>setOpen(false)}><section className="h-full w-full max-w-lg bg-white p-6 shadow-2xl" onClick={e=>e.stopPropagation()}><div className="flex items-center justify-between"><h2 className="text-xl font-bold">{title}</h2><button onClick={()=>setOpen(false)} aria-label="关闭"><XMarkIcon className="h-5 w-5"/></button></div><div className="mt-6">{children}</div></section></div>}</>}
export function ChartCard({title,subtitle,action,children,className="",headerClassName=""}:{title:string;subtitle?:string;action?:React.ReactNode;children:React.ReactNode;className?:string;headerClassName?:string}){return <section className={`card p-4 ${className}`}><div className={`mb-3 flex items-start justify-between gap-3 ${headerClassName}`}><div><h2 className="font-bold">{title}</h2>{subtitle&&<p className="mt-0.5 text-[11px] text-neutral-500">{subtitle}</p>}</div>{action&&<div className="shrink-0">{action}</div>}</div>{children}</section>}
