-- 印尼走货明细系统 — PostgreSQL 16 schema
-- 非破坏性初始化：只创建缺失对象，不删除或清空现有资料。

CREATE SCHEMA IF NOT EXISTS dbo;

CREATE TABLE IF NOT EXISTS dbo.users (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username        VARCHAR(64)  NOT NULL UNIQUE,
    passwordhash    VARCHAR(255) NOT NULL,
    displayname     VARCHAR(128) NOT NULL DEFAULT '',
    userbqrpower    CHAR(9)      NOT NULL DEFAULT '000000000',
    usereditpower   CHAR(9)      NOT NULL DEFAULT '000000000',
    isactive        BOOLEAN      NOT NULL DEFAULT TRUE,
    createdat       TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL
                    DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    CONSTRAINT ck_users_userbqrpower_binary
        CHECK (userbqrpower ~ '^[01]{9}$'),
    CONSTRAINT ck_users_usereditpower_binary
        CHECK (usereditpower ~ '^[01]{9}$')
);

CREATE TABLE IF NOT EXISTS dbo.customers (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(256) NOT NULL UNIQUE,
    created_at  TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL
                DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    active      BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS dbo.products (
    code        VARCHAR(64) NOT NULL PRIMARY KEY,
    name        VARCHAR(256),
    hs_cn       VARCHAR(64),
    hs_id       VARCHAR(64),
    customer    VARCHAR(256),
    moldings    TEXT,
    created_at  TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL
                DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    updated_at  TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL
                DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    active      BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT ck_products_moldings_json
        CHECK (moldings IS NULL OR jsonb_typeof(moldings::jsonb) IS NOT NULL)
);

CREATE TABLE IF NOT EXISTS dbo.materials (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_code        VARCHAR(64),
    item_no             VARCHAR(64),
    name_zh             VARCHAR(256),
    name_en             VARCHAR(256),
    spec                VARCHAR(256),
    category            VARCHAR(64),
    material_code       VARCHAR(64),
    hs_cn               VARCHAR(64),
    hs_id               VARCHAR(64),
    supplier            VARCHAR(256),
    customs_company     VARCHAR(256),
    unit_kg             VARCHAR(16) NOT NULL DEFAULT 'KGM',
    gross_per_pc        NUMERIC(18,6) NOT NULL DEFAULT 0,
    net_per_pc          NUMERIC(18,6) NOT NULL DEFAULT 0,
    length              NUMERIC(18,4) NOT NULL DEFAULT 0,
    width               NUMERIC(18,4) NOT NULL DEFAULT 0,
    height              NUMERIC(18,4) NOT NULL DEFAULT 0,
    qty_per_carton      NUMERIC(18,4) NOT NULL DEFAULT 0,
    weight_per_carton   NUMERIC(18,4) NOT NULL DEFAULT 0,
    image_id            VARCHAR(64),
    active              BOOLEAN NOT NULL DEFAULT TRUE,
    sort_order          INTEGER NOT NULL DEFAULT 0,
    usage_qty           NUMERIC(18,6),
    created_at          TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL
                        DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    CONSTRAINT fk_materials_products
        FOREIGN KEY (product_code) REFERENCES dbo.products(code) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS ix_materials_product ON dbo.materials(product_code);
CREATE INDEX IF NOT EXISTS ix_materials_name ON dbo.materials(name_zh);

CREATE TABLE IF NOT EXISTS dbo.images (
    id          VARCHAR(64) NOT NULL PRIMARY KEY,
    mime        VARCHAR(64),
    data_url    TEXT,
    created_at  TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL
                DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC')
);

CREATE TABLE IF NOT EXISTS dbo.dict_hs (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    keyword     VARCHAR(128) NOT NULL,
    hs_cn       VARCHAR(64),
    hs_id       VARCHAR(64),
    priority    INTEGER NOT NULL DEFAULT 100
);
CREATE INDEX IF NOT EXISTS ix_dict_hs_keyword ON dbo.dict_hs(keyword);

CREATE TABLE IF NOT EXISTS dbo.dict_supplier (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    keyword         VARCHAR(128) NOT NULL,
    full_name       VARCHAR(256),
    customs_company VARCHAR(256),
    priority        INTEGER NOT NULL DEFAULT 100
);
CREATE INDEX IF NOT EXISTS ix_dict_supplier_keyword ON dbo.dict_supplier(keyword);

CREATE TABLE IF NOT EXISTS dbo.schedules (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    week_label      VARCHAR(64) UNIQUE,
    upload_date     TIMESTAMP(0) WITHOUT TIME ZONE,
    raw_rows        TEXT,
    diff_from_prev  TEXT,
    created_at      TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL
                    DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    CONSTRAINT ck_schedules_raw_rows_json
        CHECK (raw_rows IS NULL OR jsonb_typeof(raw_rows::jsonb) IS NOT NULL),
    CONSTRAINT ck_schedules_diff_from_prev_json
        CHECK (diff_from_prev IS NULL OR jsonb_typeof(diff_from_prev::jsonb) IS NOT NULL)
);

CREATE TABLE IF NOT EXISTS dbo.purchase_orders (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    po_no           VARCHAR(64) UNIQUE,
    supplier        VARCHAR(256),
    status          VARCHAR(32) NOT NULL DEFAULT 'draft',
    order_date      DATE,
    delivery_date   DATE,
    notes           TEXT,
    created_at      TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL
                    DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC')
);

CREATE TABLE IF NOT EXISTS dbo.po_items (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    po_id           INTEGER NOT NULL,
    product_code    VARCHAR(64),
    material_id     INTEGER,
    material_name   VARCHAR(256),
    qty             NUMERIC(18,4),
    price           NUMERIC(18,4),
    currency        VARCHAR(8) NOT NULL DEFAULT '¥',
    notes           TEXT,
    category        VARCHAR(64),
    spec            VARCHAR(256),
    usage_qty       NUMERIC(18,6),
    ordered_qty     NUMERIC(18,4),
    material_qty    NUMERIC(18,4),
    spoilage_qty    NUMERIC(18,4),
    purchase_qty    NUMERIC(18,4),
    purchase_unit   VARCHAR(16),
    tomy_po         VARCHAR(64),
    ship_unit       VARCHAR(16),
    net_per_pc      NUMERIC(18,6),
    eta             VARCHAR(32),
    CONSTRAINT fk_po_items_po
        FOREIGN KEY (po_id) REFERENCES dbo.purchase_orders(id) ON DELETE CASCADE,
    CONSTRAINT fk_po_items_material
        FOREIGN KEY (material_id) REFERENCES dbo.materials(id)
);
CREATE INDEX IF NOT EXISTS ix_po_items_po ON dbo.po_items(po_id);

CREATE TABLE IF NOT EXISTS dbo.po_receipts (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    po_item_id      INTEGER NOT NULL,
    receipt_date    DATE NOT NULL,
    qty             NUMERIC(18,4) NOT NULL,
    batch_no        VARCHAR(64),
    notes           TEXT,
    created_at      TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL
                    DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    CONSTRAINT ck_po_receipts_qty_positive CHECK (qty > 0),
    CONSTRAINT fk_po_receipts_item
        FOREIGN KEY (po_item_id) REFERENCES dbo.po_items(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS ix_po_receipts_item ON dbo.po_receipts(po_item_id);
CREATE INDEX IF NOT EXISTS ix_po_receipts_date ON dbo.po_receipts(receipt_date);

CREATE TABLE IF NOT EXISTS dbo.outbound (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    po_item_id      INTEGER,
    po_no           VARCHAR(64),
    material_id     INTEGER,
    qty             NUMERIC(18,4),
    out_date        DATE,
    notes           TEXT,
    created_at      TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL
                    DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    CONSTRAINT fk_outbound_material
        FOREIGN KEY (material_id) REFERENCES dbo.materials(id),
    CONSTRAINT fk_outbound_po_item
        FOREIGN KEY (po_item_id) REFERENCES dbo.po_items(id)
);
ALTER TABLE dbo.outbound ADD COLUMN IF NOT EXISTS po_item_id INTEGER;
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_outbound_po_item'
          AND conrelid = 'dbo.outbound'::regclass
    ) THEN
        ALTER TABLE dbo.outbound
            ADD CONSTRAINT fk_outbound_po_item
            FOREIGN KEY (po_item_id) REFERENCES dbo.po_items(id);
    END IF;
END $$;
CREATE INDEX IF NOT EXISTS ix_outbound_po_no ON dbo.outbound(po_no);
CREATE INDEX IF NOT EXISTS ix_outbound_po_item ON dbo.outbound(po_item_id);
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'ck_outbound_qty_positive'
          AND conrelid = 'dbo.outbound'::regclass
    ) THEN
        ALTER TABLE dbo.outbound
            ADD CONSTRAINT ck_outbound_qty_positive CHECK (qty > 0) NOT VALID;
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS dbo.shipments (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer        VARCHAR(256),
    container_no    VARCHAR(64),
    container_count INTEGER NOT NULL DEFAULT 1,
    ship_date       DATE,
    load_date       DATE,
    bl_no           VARCHAR(64),
    rate            NUMERIC(10,4) NOT NULL DEFAULT 0.93,
    status          VARCHAR(32) NOT NULL DEFAULT 'draft',
    created_at      TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL
                    DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC')
);

CREATE TABLE IF NOT EXISTS dbo.shipment_items (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shipment_id         INTEGER NOT NULL,
    material_id         INTEGER,
    seq                 INTEGER,
    kg                  NUMERIC(18,4),
    qty                 NUMERIC(18,4),
    cartons             INTEGER,
    qty_per_carton      VARCHAR(64),
    pallet              VARCHAR(64),
    price               NUMERIC(18,4),
    currency            VARCHAR(8) NOT NULL DEFAULT '¥',
    po_no               VARCHAR(64),
    po_date             DATE,
    supplier            VARCHAR(256),
    customs_company     VARCHAR(256),
    bl_head             VARCHAR(256),
    contract_no         VARCHAR(64),
    contract_date       DATE,
    invoice_no          VARCHAR(64),
    invoice_date        DATE,
    invoice_price       NUMERIC(18,4),
    product_use         VARCHAR(256),
    formula_name        VARCHAR(256),
    outbound_id         INTEGER,
    CONSTRAINT fk_shipment_items_shipment
        FOREIGN KEY (shipment_id) REFERENCES dbo.shipments(id) ON DELETE CASCADE,
    CONSTRAINT fk_shipment_items_material
        FOREIGN KEY (material_id) REFERENCES dbo.materials(id),
    CONSTRAINT fk_shipment_items_outbound
        FOREIGN KEY (outbound_id) REFERENCES dbo.outbound(id)
);
ALTER TABLE dbo.shipment_items ADD COLUMN IF NOT EXISTS outbound_id INTEGER;
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_shipment_items_outbound'
          AND conrelid = 'dbo.shipment_items'::regclass
    ) THEN
        ALTER TABLE dbo.shipment_items
            ADD CONSTRAINT fk_shipment_items_outbound
            FOREIGN KEY (outbound_id) REFERENCES dbo.outbound(id);
    END IF;
END $$;
CREATE INDEX IF NOT EXISTS ix_shipment_items_shipment ON dbo.shipment_items(shipment_id);
CREATE INDEX IF NOT EXISTS ix_shipment_items_po_no ON dbo.shipment_items(po_no);
CREATE INDEX IF NOT EXISTS ix_shipment_items_outbound ON dbo.shipment_items(outbound_id);

CREATE TABLE IF NOT EXISTS dbo.audit_logs (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    occurred_at     TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL
                    DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    user_id         INTEGER,
    username        VARCHAR(64) NOT NULL DEFAULT '',
    module          VARCHAR(32) NOT NULL,
    action          VARCHAR(32) NOT NULL,
    entity_type     VARCHAR(64) NOT NULL,
    entity_id       VARCHAR(64) NOT NULL DEFAULT '',
    summary         VARCHAR(512) NOT NULL DEFAULT '',
    details         JSONB,
    ip_address      VARCHAR(64) NOT NULL DEFAULT ''
);
CREATE INDEX IF NOT EXISTS ix_audit_logs_time ON dbo.audit_logs(occurred_at DESC);
CREATE INDEX IF NOT EXISTS ix_audit_logs_entity ON dbo.audit_logs(entity_type, entity_id);
CREATE INDEX IF NOT EXISTS ix_audit_logs_user ON dbo.audit_logs(user_id, occurred_at DESC);

CREATE TABLE IF NOT EXISTS dbo.settings (
    "key"       VARCHAR(128) NOT NULL PRIMARY KEY,
    value       TEXT,
    updated_at  TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL
                DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC')
);

CREATE TABLE IF NOT EXISTS dbo.__rr_seed_history (
    version     VARCHAR(32) NOT NULL PRIMARY KEY,
    imported_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL
                DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC')
);
