# Generated by Django 5.2.12 on 2026-03-24 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='客户名称')),
                ('consignee', models.CharField(blank=True, default='', max_length=200, verbose_name='收货人')),
                ('consignee_code', models.CharField(blank=True, default='', max_length=50, verbose_name='收货人代码')),
                ('schedule_path', models.CharField(blank=True, default='', max_length=500, verbose_name='排期路径')),
                ('template_config', models.JSONField(blank=True, default=dict, verbose_name='模板配置')),
                ('is_brand_auto', models.BooleanField(default=False, verbose_name='是否自动匹配品牌')),
            ],
            options={
                'verbose_name': '客户',
                'verbose_name_plural': '客户',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FactoryMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_name', models.CharField(max_length=300, unique=True, verbose_name='英文名称')),
                ('chinese_short_name', models.CharField(max_length=50, verbose_name='中文简称')),
                ('is_local', models.BooleanField(default=True, verbose_name='是否本地工厂')),
            ],
            options={
                'verbose_name': '工厂映射',
                'verbose_name_plural': '工厂映射',
                'ordering': ['chinese_short_name'],
            },
        ),
        migrations.CreateModel(
            name='ProductMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=100, unique=True, verbose_name='产品代码')),
                ('product_name', models.CharField(blank=True, default='', max_length=200, verbose_name='产品名称')),
                ('toy_category', models.CharField(blank=True, default='', max_length=200, verbose_name='玩具类别')),
                ('gross_weight_per_box', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='每箱毛重(kg)')),
                ('net_weight_per_box', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='每箱净重(kg)')),
                ('source', models.CharField(blank=True, default='', max_length=100, verbose_name='数据来源')),
            ],
            options={
                'verbose_name': '货号映射',
                'verbose_name_plural': '货号映射',
                'ordering': ['product_code'],
            },
        ),
        migrations.CreateModel(
            name='TransportCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='公司名称')),
                ('short_name', models.CharField(max_length=50, verbose_name='简称')),
                ('contact', models.CharField(blank=True, default='', max_length=100, verbose_name='联系人')),
                ('phone', models.CharField(blank=True, default='', max_length=50, verbose_name='联系电话')),
            ],
            options={
                'verbose_name': '运输公司',
                'verbose_name_plural': '运输公司',
                'ordering': ['short_name'],
            },
        ),
    ]
