# Generated by Django 5.2.12 on 2026-03-26 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': '客户', 'verbose_name_plural': '客户'},
        ),
        migrations.AddField(
            model_name='customer',
            name='cabinet_seq',
            field=models.IntegerField(default=1000, verbose_name='柜号序列（当前值）'),
        ),
    ]
