# Generated by Django 5.2.12 on 2026-03-27 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0002_alter_customer_options_customer_cabinet_seq'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productmapping',
            options={'ordering': ['customer_name', 'product_code'], 'verbose_name': '货号映射', 'verbose_name_plural': '货号映射'},
        ),
        migrations.AddField(
            model_name='productmapping',
            name='customer_name',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='客户名称'),
        ),
        migrations.AlterField(
            model_name='productmapping',
            name='product_code',
            field=models.CharField(max_length=100, verbose_name='产品代码'),
        ),
        migrations.AlterUniqueTogether(
            name='productmapping',
            unique_together={('product_code', 'customer_name')},
        ),
    ]
