# Generated by Django 5.2.12 on 2026-03-27 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0003_alter_productmapping_options_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='productmapping',
            index=models.Index(fields=['customer_name'], name='master_data_custome_a7c3db_idx'),
        ),
        migrations.AddIndex(
            model_name='productmapping',
            index=models.Index(fields=['product_code'], name='master_data_product_897a9f_idx'),
        ),
        migrations.AddIndex(
            model_name='productmapping',
            index=models.Index(fields=['customer_name', 'product_code'], name='master_data_custome_f5af26_idx'),
        ),
    ]
