# Generated by Django 5.2.12 on 2026-04-08 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0004_productmapping_master_data_custome_a7c3db_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DestinationPortMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port_name', models.CharField(max_length=200, unique=True, verbose_name='原始目的港文本')),
                ('country_cn', models.CharField(max_length=50, verbose_name='中文国家名')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '目的港映射',
                'verbose_name_plural': '目的港映射',
            },
        ),
    ]
