# Generated by Django 5.2.12 on 2026-04-13 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0005_destinationportmapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmapping',
            name='factory_short',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='做货工厂'),
        ),
    ]
