# Generated by Django 5.2.12 on 2026-04-09 08:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMailboxConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imap_host', models.CharField(default='mail.hanson2.com', max_length=128)),
                ('imap_port', models.IntegerField(default=993)),
                ('email', models.CharField(max_length=254)),
                ('password_encrypted', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mailbox_config', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_usermailboxconfig',
            },
        ),
    ]
