# Generated by Django 5.2.12 on 2026-04-24 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_usermailboxconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermailboxconfig',
            name='imap_host',
            field=models.CharField(default='imaphz.qiye.163.com', max_length=128),
        ),
    ]
