// 主订单列（对应 刘方尧 sheet 的列结构）
export const ORDER_COLUMNS = [
  { data: 'supervisor',     title: '主管',       width: 70 },
  { data: 'line_name',      title: '拉名',       width: 70 },
  { data: 'worker_count',   title: '人数',       width: 50, type: 'numeric' },
  { data: 'factory_area',   title: '厂区',       width: 80 },
  { data: 'client',         title: '客名',       width: 80 },
  { data: 'order_date',     title: '来单日期',   width: 90 },
  { data: 'third_party',    title: '第三方客户名称', width: 180 },
  { data: 'country',        title: '国家',       width: 70 },
  { data: 'contract',       title: '合同',       width: 120 },
  { data: 'item_no',        title: '货号',       width: 130 },
  { data: 'product_name',   title: '产品名称',   width: 130 },
  { data: 'version',        title: '版本',       width: 70 },
  { data: 'quantity',       title: '数量',       width: 70, type: 'numeric' },
  { data: 'quantity_sum',   title: '合计',       width: 80, type: 'numeric', readOnly: true },
  { data: 'work_type',      title: '做工名称',   width: 70 },
  { data: 'production_count', title: '生产数',   width: 70, type: 'numeric' },
  { data: 'production_progress', title: '生产进度', width: 70, type: 'numeric' },
  { data: 'special_notes',  title: '特别备注',   width: 150 },
  { data: 'plastic_due',    title: '胶件复期',   width: 80 },
  { data: 'material_due',   title: '来料复期',   width: 80 },
  { data: 'carton_due',     title: '纸箱复期',   width: 80 },
  { data: 'packaging_due',  title: '包材复期',   width: 80 },
  { data: 'sticker',        title: '客贴纸',     width: 60 },
  { data: 'start_date',     title: '上拉日期',   width: 90 },
  { data: 'complete_date',  title: '完成日期',   width: 90 },
  { data: 'ship_date',      title: '走货期',     width: 90 },
  { data: 'target_time',    title: '目标数生产时间', width: 90, type: 'numeric' },
  { data: 'daily_target',   title: '每天目标数', width: 80, type: 'numeric' },
  { data: 'days',           title: '天数',       width: 50, type: 'numeric' },
  { data: 'unit_price',     title: '货价',       width: 70, type: 'numeric' },
  { data: 'process_value',  title: '加工产值',   width: 90, type: 'numeric' },
  { data: 'inspection_date', title: '行Q期',     width: 70 },
  { data: 'month',          title: '月份',       width: 50, type: 'numeric' },
  { data: 'warehouse_record', title: '入库记录', width: 80 },
  { data: 'output_value',   title: '产值',       width: 80, type: 'numeric' },
  { data: 'process_price',  title: '加工价',     width: 70, type: 'numeric' },
  { data: 'remark',         title: '备注',       width: 100 },
  ...Array.from({ length: 31 }, (_, i) => ({
    data: `day_${i + 1}`, title: `${i + 1}号`, width: 45, type: 'numeric'
  })),
];
