"use client";
import { useEffect, useRef, useState } from "react";
import * as Dialog from "@radix-ui/react-dialog";

const basePath = process.env.NEXT_PUBLIC_BASE_PATH || "";
const apiFetch = (path: string, init?: RequestInit) => fetch(`${basePath}${path}`, init);

type Mapping={id:number;englishName:string;chineseShortName:string;isLocal:boolean};
type Preview={rows:Mapping[];added:number;updated:number;total:number};
const empty:Mapping={id:0,englishName:"",chineseShortName:"",isLocal:false};
async function read<T>(response:Response):Promise<T>{const value=await response.json();if(!response.ok)throw new Error(value.error||"操作失败");return value;}
export function FactoryMappingManagement({onBack}:{onBack:()=>void}) {
  const [rows,setRows]=useState<Mapping[]>([]);const [query,setQuery]=useState("");const [draft,setDraft]=useState<Mapping>();
  const [preview,setPreview]=useState<Preview>();const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");
  const input=useRef<HTMLInputElement>(null);
  async function load(){try{setRows(await read<Mapping[]>(await apiFetch("/api/factory-mappings",{cache:"no-store"})));}catch(error){setMessage(error instanceof Error?error.message:"读取失败");}}
  useEffect(()=>{void load();},[]);
  async function save(){if(!draft)return;setBusy(true);setMessage("");try{await read(await apiFetch("/api/factory-mappings",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify(draft)}));setDraft(undefined);await load();setMessage("映射已保存，重新生成走柜表即可使用。");}catch(error){setMessage(error instanceof Error?error.message:"保存失败");}finally{setBusy(false);}}
  async function importFile(file?:File){if(!file)return;setBusy(true);setMessage("");setPreview(undefined);try{const form=new FormData();form.append("file",file);setPreview(await read<Preview>(await apiFetch("/api/factory-mappings/import",{method:"POST",body:form})));}catch(error){setMessage(error instanceof Error?error.message:"读取表格失败");}finally{setBusy(false);}}
  async function confirmImport(){if(!preview)return;setBusy(true);try{const result=await read<Preview>(await apiFetch("/api/factory-mappings/import",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({rows:preview.rows,preview:false})}));setPreview(undefined);await load();setMessage(`导入完成：新增${result.added}条，更新${result.updated}条。`);}catch(error){setMessage(error instanceof Error?error.message:"导入失败");}finally{setBusy(false);}}
  const visible=rows.filter(row=>`${row.englishName} ${row.chineseShortName}`.toLowerCase().includes(query.toLowerCase()));
  return <div className="content"><button className="back-button" onClick={onBack}>返回系统设置</button><div className="page-heading"><div><p className="eyebrow">基础资料</p><h1>工厂名映射</h1><p>兴信和华登共用。生成走柜表时，将生产工厂英文名转换为备注列中文简称。</p></div><div className="mapping-actions"><button className="ghost-button" disabled={busy} onClick={()=>setDraft({...empty})}>新增映射</button><button className="primary-button" disabled={busy} onClick={()=>input.current?.click()}>导入Excel</button><input ref={input} hidden type="file" accept=".xlsx,.xlsm" onChange={event=>{void importFile(event.target.files?.[0]);event.target.value="";}}/></div></div>{message&&<div className="notice">{message}</div>}
    <section className="panel"><div className="panel-title"><div><h2>共{rows.length}条映射</h2><p>Excel表头：英文名称、中文简称、本厂（是/否）。同名更新，新名称新增，其他记录保留。</p></div><input aria-label="搜索工厂" placeholder="搜索英文名称或中文简称" value={query} onChange={event=>setQuery(event.target.value)}/></div><table className="factory-mapping-table"><thead><tr><th>英文名称</th><th>中文简称</th><th>本厂</th><th>操作</th></tr></thead><tbody>{visible.map(row=><tr key={row.id}><td>{row.englishName}</td><td>{row.chineseShortName}</td><td>{row.isLocal?"是":"否"}</td><td><button className="ghost-button" disabled={busy} onClick={()=>setDraft({...row})}>编辑</button></td></tr>)}</tbody></table>{!visible.length&&<p className="mapping-empty">暂无映射，可导入Excel或新增。</p>}</section>
    <Dialog.Root open={Boolean(draft)} onOpenChange={open=>{if(!open&&!busy)setDraft(undefined);}}><Dialog.Portal><Dialog.Overlay className="mapping-modal-backdrop"/><Dialog.Content className="factory-mapping-dialog"><Dialog.Title>{draft?.id?"编辑工厂映射":"新增工厂映射"}</Dialog.Title><Dialog.Description>一个英文名称对应一个中文简称。</Dialog.Description>{message&&<div className="notice">{message}</div>}{draft&&<form onSubmit={event=>{event.preventDefault();void save();}}><label>英文名称<input required maxLength={300} value={draft.englishName} onChange={event=>setDraft({...draft,englishName:event.target.value})}/></label><label>中文简称<input required maxLength={50} value={draft.chineseShortName} onChange={event=>setDraft({...draft,chineseShortName:event.target.value})}/></label><label><input type="checkbox" checked={draft.isLocal} onChange={event=>setDraft({...draft,isLocal:event.target.checked})}/>本厂</label><div className="modal-actions"><button type="button" className="ghost-button" disabled={busy} onClick={()=>setDraft(undefined)}>取消</button><button className="primary-button" disabled={busy}>保存</button></div></form>}</Dialog.Content></Dialog.Portal></Dialog.Root>
    <Dialog.Root open={Boolean(preview)} onOpenChange={open=>{if(!open&&!busy)setPreview(undefined);}}><Dialog.Portal><Dialog.Overlay className="mapping-modal-backdrop"/><Dialog.Content className="factory-mapping-dialog"><Dialog.Title>确认导入工厂映射</Dialog.Title><Dialog.Description>新增{preview?.added}条，更新{preview?.updated}条，共{preview?.total}条。未出现在表格中的映射保留。</Dialog.Description>{message&&<div className="notice">{message}</div>}<div className="factory-preview"><table className="factory-mapping-table"><tbody>{preview?.rows.map((row,index)=><tr key={index}><td>{row.englishName}</td><td>{row.chineseShortName}</td><td>{row.isLocal?"是":"否"}</td></tr>)}</tbody></table></div><div className="modal-actions"><button className="ghost-button" disabled={busy} onClick={()=>setPreview(undefined)}>取消</button><button className="primary-button" disabled={busy} onClick={()=>void confirmImport()}>确认导入</button></div></Dialog.Content></Dialog.Portal></Dialog.Root>
  </div>;
}
