#!/usr/bin/env bash
set -euo pipefail
# ============================================================
# SSL Setup — Automated HTTPS via Let's Encrypt / Self-Signed
# ============================================================
# Configures nginx for HTTPS with automatic certificate renewal.
# Supports: Let's Encrypt (if domain available), self-signed (fallback).
#
# Usage: setup-ssl.sh <domain-or-ip> [--self-signed]
#
# Required environment variables:
#   DEPLOY_SERVER  — SSH target
# ============================================================

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(git rev-parse --show-toplevel)"

source "${SCRIPT_DIR}/utils/telegram.sh"
source "${SCRIPT_DIR}/utils/audit.sh"

TARGET="${1:?Usage: setup-ssl.sh <domain-or-ip> [--self-signed]}"
SELF_SIGNED="${2:-}"

if [[ -z "${DEPLOY_SERVER:-}" ]]; then
  echo "ERROR: DEPLOY_SERVER not set"
  exit 1
fi

COMPOSE_DIR="/opt/rr-portal"
CERT_DIR="${COMPOSE_DIR}/ssl"

echo "=== SSL SETUP ==="
echo "Target: ${TARGET}"
echo "Server: ${DEPLOY_SERVER}"

# Create SSL directory on server
ssh "${DEPLOY_SERVER}" "mkdir -p ${CERT_DIR}" 2>/dev/null

if [[ "$SELF_SIGNED" == "--self-signed" ]] || echo "$TARGET" | grep -qE '^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$'; then
  # --- Self-signed certificate (for IP addresses or dev) ---
  echo ""
  echo "Generating self-signed certificate for ${TARGET}..."

  ssh "${DEPLOY_SERVER}" "
    openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
      -keyout ${CERT_DIR}/server.key \
      -out ${CERT_DIR}/server.crt \
      -subj '/CN=${TARGET}/O=RR-Portal/C=CN' \
      -addext 'subjectAltName=IP:${TARGET}' 2>/dev/null
    chmod 600 ${CERT_DIR}/server.key
    echo 'Certificate generated'
  " 2>/dev/null

  echo "  [OK] Self-signed certificate created"
  echo "  NOTE: Browsers will show security warning (expected for IP-based certs)"

else
  # --- Let's Encrypt certificate (for domains) ---
  echo ""
  echo "Setting up Let's Encrypt for ${TARGET}..."

  # Install certbot if not present
  ssh "${DEPLOY_SERVER}" "
    if ! command -v certbot &>/dev/null; then
      apt-get update -qq && apt-get install -y -qq certbot 2>/dev/null
    fi
    echo 'certbot available'
  " 2>/dev/null

  # Stop nginx temporarily for standalone verification
  ssh "${DEPLOY_SERVER}" "
    cd ${COMPOSE_DIR} && docker compose -f docker-compose.cloud.yml stop nginx 2>/dev/null || true
    certbot certonly --standalone -d ${TARGET} --non-interactive --agree-tos --email admin@${TARGET} 2>&1 || echo 'CERTBOT_FAILED'
    cd ${COMPOSE_DIR} && docker compose -f docker-compose.cloud.yml start nginx 2>/dev/null || true
  " 2>/dev/null

  # Copy certs to our SSL directory
  ssh "${DEPLOY_SERVER}" "
    if [[ -d /etc/letsencrypt/live/${TARGET} ]]; then
      cp /etc/letsencrypt/live/${TARGET}/fullchain.pem ${CERT_DIR}/server.crt
      cp /etc/letsencrypt/live/${TARGET}/privkey.pem ${CERT_DIR}/server.key
      chmod 600 ${CERT_DIR}/server.key
      echo 'Certificates copied'
    else
      echo 'CERT_NOT_FOUND'
    fi
  " 2>/dev/null

  # Set up auto-renewal cron
  ssh "${DEPLOY_SERVER}" "
    if ! crontab -l 2>/dev/null | grep -q certbot; then
      (crontab -l 2>/dev/null; echo '0 3 * * * certbot renew --quiet && cp /etc/letsencrypt/live/${TARGET}/fullchain.pem ${CERT_DIR}/server.crt && cp /etc/letsencrypt/live/${TARGET}/privkey.pem ${CERT_DIR}/server.key && docker exec \$(docker ps -q -f name=nginx) nginx -s reload') | crontab -
      echo 'Auto-renewal cron installed'
    fi
  " 2>/dev/null

  echo "  [OK] Let's Encrypt certificate configured with auto-renewal"
fi

# --- Generate HTTPS nginx config ---
echo ""
echo "Generating HTTPS nginx configuration..."

# Create an HTTPS server block template
ssh "${DEPLOY_SERVER}" "cat > ${COMPOSE_DIR}/nginx/ssl.conf << 'SSLCONF'
# SSL Configuration (generated by setup-ssl.sh)
ssl_certificate     /etc/nginx/ssl/server.crt;
ssl_certificate_key /etc/nginx/ssl/server.key;
ssl_protocols       TLSv1.2 TLSv1.3;
ssl_ciphers         HIGH:!aNULL:!MD5;
ssl_prefer_server_ciphers on;
ssl_session_cache   shared:SSL:10m;
ssl_session_timeout 10m;

# HSTS (optional — uncomment if you want strict HTTPS)
# add_header Strict-Transport-Security \"max-age=31536000; includeSubDomains\" always;
SSLCONF
" 2>/dev/null

echo "  [OK] SSL config written to ${COMPOSE_DIR}/nginx/ssl.conf"
echo ""
echo "To enable HTTPS, update nginx.cloud.conf:"
echo "  1. Change 'listen 80;' to 'listen 443 ssl;'"
echo "  2. Add 'include /etc/nginx/ssl.conf;' inside server block"
echo "  3. Add HTTP->HTTPS redirect server block"
echo "  4. Mount ssl/ volume in docker-compose nginx service"
echo ""
echo "Or run: setup-ssl.sh ${TARGET} --apply  (TODO: auto-apply)"

audit_log "ssl-setup" "-" "SSL certificate configured for ${TARGET}"
send_telegram "SSL certificate configured for ${TARGET}"

echo "=== SSL SETUP COMPLETE ==="
