const test=require('node:test');
const assert=require('node:assert/strict');
const {calculate,matches}=require('../frontend/jazwares-freight');
const {addJazwaresFreightSheet}=require('../backend/services/jazwaresFreightExport');
test('JAZWARES follows provided manual-load formula and separates theoretical capacity',()=>{
 const m=calculate({}, {cuft:0.6084,qty:100},{fx_rmb_hkd:0.85});
 assert.ok(Math.abs(m.regions[0].perPiece-3500/0.85/6000)<1e-12);
 assert.equal(m.regions[0].usdMarkup.toFixed(3),'0.113');assert.equal(m.regions[0].usdPlain.toFixed(3),'0.090');
 assert.equal(m.regions[1].usdMarkup.toFixed(3),'0.055');assert.equal(m.regions[1].usdPlain.toFixed(3),'0.044');
 assert.ok(m.theoreticalQuantity>58000);assert.equal(m.regions[0].quantity,6000);
 assert.equal(calculate({zhejiang_quantity:0}).regions[0].perPiece,null);
 assert.equal(calculate({}, {}, {fx_rmb_hkd:0}).regions[0].hkd,null);
 assert.ok(matches('JAZWARES'));assert.ok(!matches('TOMY'));
});
test('Excel export preserves formulas and only adds sheet for JAZWARES',async()=>{
 const ExcelJS=require('exceljs'),wb=new ExcelJS.Workbook();
 addJazwaresFreightSheet(wb,{customer:'TOMY'},{},{});assert.equal(wb.worksheets.length,0);
 addJazwaresFreightSheet(wb,{customer:'JAZWARES'},{header:{fx_rmb_hkd:0.85}},{carton_calc:{cuft:0.6084,qty:100}});
 const re=new ExcelJS.Workbook();await re.xlsx.load(await wb.xlsx.writeBuffer());const s=re.worksheets[0];
 assert.match(s.getCell('B6').value.formula,/E2\*F2\*G2\/1728\/35.32/);
 assert.equal(s.getCell('B6').numFmt,'0.0000');
 assert.equal(s.getCell('B14').value.result,3500/0.85/6000);
 assert.match(s.getCell('B15').value.formula,/B14\/\$B\$4\*\$B\$5\/\$B\$3/);
 assert.equal(s.getCell('B15').value.result.toFixed(3),'0.113');
});
test('both destination quotes add marked-up freight independently after the original total', async()=>{
 const {buildWorkbook}=require('../backend/services/exportInternal');
 const sales={header:{fx_rmb_hkd:0.85,fx_hkd_usd:7.8},shipping:{markup_x:1.2,divisor:0.98,scenarios:[{name:'出厂价',is_factory:true},{name:'盐田40柜'}]}};
 const wb=await buildWorkbook({quote:{customer:'JAZWARES',quote_no:'FREIGHT',qty:1000},sections:[{dept:'sales',payload_json:JSON.stringify(sales)}]});
 const ws=wb.getWorksheet('报价明细');
 const find=label=>{let found;ws.eachRow(r=>{if(r.getCell(1).value===label)found=r;});return found;};
 const z=find('浙江合计 (USD)'),g=find('广东合计 (USD)');
 assert.ok(z);assert.ok(g);
 const details=[];ws.eachRow(r=>{if(r.getCell(6).value==='体积 CBM')details.push(r);});
 assert.equal(details.length,2);
 assert.equal(details[0].getCell(8).value.formula,`IF(ISNUMBER('JAZWARES运费'!B12),'JAZWARES运费'!B12,"待补参数")`);
 assert.equal(details[1].getCell(9).numFmt,'"每个 "0.0000');
 assert.ok(details[0].number < z.number);
 assert.equal(ws.getRow(details[0].number-3).getCell(6).value,'浙江');
 assert.equal(ws.getRow(details[1].number-3).getCell(6).value,'广东省');
 const zf=ws.getRow(z.number-1),gf=ws.getRow(g.number-1);
 assert.match(zf.getCell(2).value.formula,/'JAZWARES运费'!B15/);
 assert.match(gf.getCell(2).value.formula,/'JAZWARES运费'!B23/);
 const base=ws.getRow(z.number-2).getCell(2).value.result || 0;
 const m=calculate({}, {}, sales.header);
 assert.ok(Math.abs(z.getCell(2).value.result-base-m.regions[0].usdMarkup)<1e-12);
 assert.ok(Math.abs(g.getCell(2).value.result-base-m.regions[1].usdMarkup)<1e-12);
 assert.equal(z.getCell(2).value.formula.split('+')[0],g.getCell(2).value.formula.split('+')[0].replace(`B${gf.number}`,`B${zf.number}`));
});
