const test=require('node:test'),assert=require('node:assert/strict');
const ExcelJS=require('exceljs');
const {buildMixedWorkbook}=require('../backend/services/exportMixedQuotation');
test('混装导出沿用单品模板，封穴计算引用进入明细及最终汇总，序列化后保留公式',async()=>{
 const cfg={enabled:true,mode:'equal',units_per_pack:1,products:[{id:'a',code:'A',name:'A'},{id:'b',code:'B',name:'B'}]};
 const payloads={sales:{mixed_quote:cfg,header:{fx_hkd_usd:7.8,fx_rmb_hkd:.85},shipping:{markup_x:1,divisor:1},mixed_pricing:{surtax_pct:0}},molding:{parts_catalog:{version:1,parts:[{id:'a',name:'零件A',mold_no:'M',cavity:2,machine_price:360,target:1000,production_demand:4000,weight_g:0,material_unit_price:0},{id:'b',name:'零件B',mold_no:'M',cavity:4,machine_price:360,target:1000,production_demand:4000,weight_g:0,material_unit_price:0}],selections:{a:[{part_id:'a',usage:1}],b:[{part_id:'b',usage:1}]}}}};
 const w=await buildMixedWorkbook({consolidate:false,quote:{quote_no:'T',product_name:'test',qty:8000},sections:Object.entries(payloads).map(([dept,p])=>({dept,payload_json:JSON.stringify(p)}))});
 const copy=new ExcelJS.Workbook();await copy.xlsx.load(await w.xlsx.writeBuffer());
 const labor=copy.getWorksheet('封穴啤工计算');
 assert.ok(Math.abs(labor.getCell('J2').result-.12)<1e-10);
 assert.ok(Math.abs(labor.getCell('J3').result-.06)<1e-10);
 assert.ok(labor.getCell('J2').formula);
 assert.equal(copy.worksheets[0].name,'总报价表');
 const categories=copy.getWorksheet('内部分类汇总');
 assert.equal(copy.worksheets[1].name,'内部分类汇总');
 assert.equal(categories.getCell('E4').value,'啤工');
 assert.ok(Math.abs(categories.getCell('E8').result-.09)<1e-10);
 assert.match(categories.getCell('E8').formula,/SUMPRODUCT/);
 assert.match(copy.worksheets[0].getCell('C7').formula,/内部分类汇总/);
 assert.equal(copy.getWorksheet('啤机明细').getCell('I2').numFmt,'0.0000');
 assert.equal(copy.getWorksheet('啤机明细').getCell('A1').value,'模号');
 assert.equal(copy.getWorksheet('啤机明细').getCell('A2').value,'M');
 assert.ok(!copy.worksheets.some(s=>/^\d+-/.test(s.name)));
 const finalRow=copy.worksheets[0].getRows(1,40).find(r=>r.getCell(1).value==='TOTAL 报客价 USD');
 assert.ok(Math.abs(finalRow.getCell(3).result-.09/7.8)<1e-10);
 const template=copy.getWorksheet('工程及单款汇总');assert.ok(template);
 let links=0;copy.eachSheet(ws=>ws.eachRow(row=>row.eachCell(c=>{if(c.formula?.includes("'封穴啤工计算'!"))links++;assert.ok(!c.formula?.includes('#REF!'));})));
 assert.ok(links>=2);
 assert.match(copy.getWorksheet('混装报价汇总').getCell('E2').formula,/工程及单款汇总/);
 assert.ok(Math.abs(copy.getWorksheet('混装报价汇总').getCell('B9').result-.09/7.8)<1e-10);
 require('../backend/services/consolidateMixedWorkbook').consolidateMixedWorkbook(copy);
 const saved=new ExcelJS.Workbook();await saved.xlsx.load(await copy.xlsx.writeBuffer());
 assert.ok(saved.worksheets.filter(s=>s.state==='visible').every(s=>s.name==='总报价表'||s.name==='模具报价'||s.name.endsWith('明细')));
 assert.equal(saved.worksheets[0].name,'总报价表');
 assert.ok(saved.worksheets.every(s=>s.state==='visible'));
 assert.equal(saved.getWorksheet('内部计算源'),undefined);
 assert.ok(saved.getWorksheet('模具报价'));
 assert.ok(!saved.getWorksheet('总报价表').getColumn(1).values.some(v=>String(v).includes('一、模具部分')));
 assert.ok(!saved.getWorksheet('模具报价').getColumn(1).values.some(v=>String(v).includes('减税')));
 const total=saved.worksheets[0].getRows(1,100).find(r=>r.getCell(1).value==='TOTAL 报客价 USD');
 assert.ok(Math.abs(total.getCell(3).result-.09/7.8)<1e-10);
 saved.eachSheet(s=>s.eachRow(r=>r.eachCell(c=>{if(c.formula)assert.ok(!/内部计算源|内部报价计算源|内部啤工计算源|混装算价参数|零件用量|内部总表|内部分类汇总|混装报价汇总|小产品完整成本|工程及单款汇总|封穴啤工计算/.test(c.formula));})));
});
test('导出封穴阶段使用普通单元格公式扣除前段啤次，不依赖被 IFERROR 隐藏的数组公式',async()=>{
 const cfg={enabled:true,mode:'equal',units_per_pack:1,products:[{id:'a',code:'A',name:'A'},{id:'b',code:'B',name:'B'}]};
 const p={sales:{mixed_quote:cfg,shipping:{markup_x:1,divisor:1},mixed_pricing:{surtax_pct:0}},molding:{parts_catalog:{version:1,parts:[{id:'a',name:'A',mold_no:'M',cavity:2,machine_price:360,target:1000,production_demand:4000},{id:'b',name:'B',mold_no:'M',cavity:4,machine_price:360,target:1000,production_demand:4000}],selections:{a:[{part_id:'a',usage:1}],b:[{part_id:'b',usage:1}]}}}};
 const w=await buildMixedWorkbook({consolidate:false,quote:{qty:8000},sections:Object.entries(p).map(([dept,v])=>({dept,payload_json:JSON.stringify(v)}))});
 const s=w.getWorksheet('封穴啤工计算');
 const evaluate=(f,values)=>Function('MAX','IF','return '+f.replace(/G[23]/g,c=>String(values[c])))(Math.max,(c,a,b)=>c?a:b);
 assert.equal(evaluate(s.getCell('L2').formula,{G2:2000,G3:1000}),1000);
 assert.equal(evaluate(s.getCell('L2').formula,{G2:500,G3:1000}),0);
 assert.equal(evaluate(s.getCell('L3').formula,{G2:500,G3:1000}),500);
 assert.match(s.getCell('H2').formula,/G2-L2/);
 assert.ok(!s.getCell('H2').formula.includes('AGGREGATE'));
 assert.equal(s.getCell('H2').result,180);
 assert.equal(s.getCell('H3').result,60);
});

test('导出移除自动需求及生产配比表，保留用量和手填啤工需求',async()=>{
 const cfg={enabled:true,mode:'equal',na_direct:true,units_per_pack:6,products:[{id:'a',code:'A',name:'A',na_ratio:'.1'},{id:'b',code:'B',name:'B',na_ratio:'.2'}]};
 const payloads={sales:{mixed_quote:cfg,shipping:{markup_x:1,divisor:1},mixed_pricing:{surtax_pct:0}},molding:{parts_catalog:{version:1,parts:[{id:'a',name:'A',mold_no:'M',cavity:2,machine_price:360,target:1000,production_demand:3000},{id:'b',name:'B',mold_no:'M',cavity:4,machine_price:360,target:1000,production_demand:3000}],selections:{a:[{part_id:'a',usage:1}],b:[{part_id:'b',usage:1}]}}}};
 const w=await buildMixedWorkbook({consolidate:false,quote:{qty:1000},sections:Object.entries(payloads).map(([dept,p])=>({dept,payload_json:JSON.stringify(p)}))});
 const labor=w.getWorksheet('封穴啤工计算');
 assert.equal(labor.getCell('F2').value,3000);
 assert.equal(labor.getCell('F3').value,3000);
 assert.equal(labor.getCell('F2').formula,undefined);
 assert.equal(labor.getCell('G2').formula,'F2/E2');
 const bom=w.getWorksheet('零件用量');
 assert.equal(bom.columnCount,3);
 assert.equal(bom.getCell('C2').value,1);
 assert.equal(w.getWorksheet('生产配比'),undefined);
 w.eachSheet(ws=>ws.eachRow(row=>row.eachCell(cell=>{
   assert.ok(!cell.formula?.includes('生产配比'));
   assert.ok(!/零件用量'!\$?D/.test(cell.formula||''));
 })));
 assert.equal(w.getWorksheet('混装报价汇总').getCell('B6').value,1);
});
