const test=require('node:test'),assert=require('node:assert/strict');
const M=require('../frontend/mixed-molds');
const {calculateMixedQuote}=require('../backend/services/mixedQuotation');
const cfg={enabled:true,mode:'equal',units_per_pack:1,products:[{id:'a',code:'A',name:'A'},{id:'b',code:'B',name:'B'}]};
const part={name:'盒子',mold_no:'M1',weight_g:2,material:'PVC',material_unit_price:.1,shot_price:.2,machine_price:20,target:100,cavity:1,production_demand:100};
function root(){return {mixed_products:{a:{injection:[{...part}],injection_loss_pct:3},b:{injection:[{...part}],injection_loss_pct:3}},mixed_shared:{injection:[{...part,name:'球壳',mold_no:'SH'}],injection_loss_pct:0}};}
function calc(r){return calculateMixedQuote({qty:100},[{dept:'sales',payload_json:JSON.stringify({mixed_quote:cfg,shipping:{markup_x:1,divisor:1},mixed_pricing:{surtax_pct:0}})},{dept:'molding',payload_json:JSON.stringify(r)}],{strict:true});}
test('统一零件转换按机台参数计价，共用零件改价和用量乘算且球壳只计一次',()=>{const r=root(),before=calc(r);M.enableCatalog(r,cfg,100);assert.equal(r.parts_catalog.parts.length,2);assert.equal(calc(r).final_usd,before.final_usd);r.parts_catalog.parts[0].machine_price=60;const changed=calc(r);assert.equal(changed.products[0].components.injection_labor,.6);assert.equal(changed.products[1].components.injection_labor,.6);r.parts_catalog.selections.a[0].usage=2;assert.equal(calc(r).products[0].components.injection_labor,1.2);assert.equal(calc(r).common_components.injection_labor,.2);r.parts_catalog.selections.a=[];assert.equal(M.applyCatalog(r,cfg,100).mixed_products.a.injection.length,0);});
test('共模转换按封穴参数重算且不重复叠加旧分摊',()=>{const r=root();r.mixed_molds=[{mold_no:'M1',machine_price:20,target:100,parts:[{product_id:'a',name:'盒子',cavity:1,usage:1,demand:100}]}];M.enableCatalog(r,cfg,100);const value=calc(r);assert.equal(value.products[0].components.injection_labor,.1);assert.equal(value.products[1].components.injection_labor,.1);r.parts_catalog.parts.filter(p=>p.mold_no==='M1').forEach(p=>p.machine_price=40);assert.equal(calc(r).products[0].components.injection_labor,.2);assert.equal(calc(r).common_components.injection_labor,.2);});
test('拒绝无效用量、孤立引用和负数',()=>{const r=root();M.enableCatalog(r,cfg,100);r.parts_catalog.selections.a[0].usage=0;assert.throws(()=>M.catalogRows(r,cfg,100),/用量/);r.parts_catalog.selections.a=[{part_id:'missing',usage:1}];assert.throws(()=>M.catalogRows(r,cfg,100),/不存在/);r.parts_catalog.selections.a=[];r.parts_catalog.parts[0].machine_price=-1;assert.throws(()=>M.catalogRows(r,cfg,100),/机台日费用/);});
test('工程产品组成优先于旧啤机选用，物料及啤工按工程用量计算',()=>{const r=root();M.enableCatalog(r,cfg,100);const bom=JSON.parse(JSON.stringify(r.parts_catalog.selections));bom.a[0].usage=3;const sections=[{dept:'sales',payload_json:JSON.stringify({mixed_quote:cfg})},{dept:'engineering',payload_json:JSON.stringify({mixed_part_selections:bom})},{dept:'molding',payload_json:JSON.stringify(r)}];const result=calculateMixedQuote({qty:100},sections,{strict:true});assert.ok(Math.abs(result.products[0].components.injection_labor-.6)<1e-10);assert.ok(Math.abs(result.products[0].components.dom_mat-.618)<1e-10);assert.equal(result.products[1].components.injection_labor,.2);});
test('工程统一上传零件可选用，缺参数阻止完成，补齐后按参数计价',()=>{const r=root();M.enableCatalog(r,cfg,100);const engineering={mixed_imported_parts:[{id:'uploaded',name:'新盖子',weight_g:1,material:'PVC',material_unit_price:0,shot_price:0,machine_price:30,target:'',cavity:1,production_demand:100,price_pending:true}],mixed_part_selections:{a:[{part_id:'uploaded',usage:2}],b:r.parts_catalog.selections.b}};const sections=()=>[{dept:'sales',payload_json:JSON.stringify({mixed_quote:cfg})},{dept:'engineering',payload_json:JSON.stringify(engineering)},{dept:'molding',payload_json:JSON.stringify(r)}];assert.equal(calculateMixedQuote({qty:100},sections()).valid,false);const merged=M.engineeringCatalog(r,engineering);const newPart=merged.parts_catalog.parts.find(p=>p.id==='uploaded');newPart.price_pending=false;newPart.target=100;newPart.shot_price=999;r.parts_catalog=merged.parts_catalog;const result=calculateMixedQuote({qty:100},sections(),{strict:true});assert.equal(result.products[0].components.injection_labor,.6);});
