"""legacy baseline

Revision ID: 1fa27814b6c2
Revises:
Create Date: 2026-07-15 10:22:50.962405
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1fa27814b6c2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    expected = {'aql_rules', 'customers', 'defect_categories', 'products', 'settings', 'test_templates', 'users', 'audit_logs', 'purchase_orders', 'reports', 'defects', 'photos', 'report_versions', 'test_results'}
    existing = set(sa.inspect(op.get_bind()).get_table_names())
    present = expected & existing
    if present:
        missing = expected - existing
        if missing:
            raise RuntimeError(f"Legacy schema is incomplete; back up and repair missing tables before migration: {sorted(missing)}")
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aql_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('standard', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('inspection_level', sa.String(length=20), nullable=False),
    sa.Column('lot_min', sa.Integer(), nullable=False),
    sa.Column('lot_max', sa.Integer(), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('aql', sa.Float(), nullable=False),
    sa.Column('accept', sa.Integer(), nullable=False),
    sa.Column('reject', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('defect_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('default_severity', sa.String(length=20), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_no', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('size_mm', sa.String(length=120), nullable=False),
    sa.Column('net_weight_kg', sa.Float(), nullable=True),
    sa.Column('gross_weight_kg', sa.Float(), nullable=True),
    sa.Column('barcode', sa.String(length=120), nullable=False),
    sa.Column('age_grade', sa.String(length=40), nullable=False),
    sa.Column('origin', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_item_no'), 'products', ['item_no'], unique=True)
    op.create_table('settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('test_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('standard', sa.String(length=160), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('signature_path', sa.String(length=500), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=60), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('ip_address', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('purchase_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('po_no', sa.String(length=100), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('carton_count', sa.Integer(), nullable=False),
    sa.Column('case_pack', sa.Integer(), nullable=False),
    sa.Column('date_code', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_orders_po_no'), 'purchase_orders', ['po_no'], unique=True)
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_no', sa.String(length=100), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('po_id', sa.Integer(), nullable=False),
    sa.Column('inspector_id', sa.Integer(), nullable=False),
    sa.Column('product_snapshot', sa.Text(), nullable=False),
    sa.Column('packing_snapshot', sa.Text(), nullable=False),
    sa.Column('inspection_date', sa.Date(), nullable=False),
    sa.Column('inspection_status', sa.String(length=40), nullable=False),
    sa.Column('inspection_level', sa.String(length=20), nullable=False),
    sa.Column('completed_pct', sa.Integer(), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('inspected_qty', sa.Integer(), nullable=False),
    sa.Column('critical_count', sa.Integer(), nullable=False),
    sa.Column('major_count', sa.Integer(), nullable=False),
    sa.Column('minor_count', sa.Integer(), nullable=False),
    sa.Column('critical_aql', sa.Float(), nullable=False),
    sa.Column('major_aql', sa.Float(), nullable=False),
    sa.Column('minor_aql', sa.Float(), nullable=False),
    sa.Column('result', sa.String(length=20), nullable=False),
    sa.Column('result_reason', sa.Text(), nullable=False),
    sa.Column('manual_hold', sa.Boolean(), nullable=False),
    sa.Column('hold_reason', sa.Text(), nullable=False),
    sa.Column('master_carton_dimension', sa.String(length=120), nullable=False),
    sa.Column('master_carton_nw', sa.Float(), nullable=True),
    sa.Column('master_carton_gw', sa.Float(), nullable=True),
    sa.Column('outer_carton_barcode', sa.String(length=160), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=False),
    sa.Column('signature_path', sa.String(length=500), nullable=True),
    sa.Column('signed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finalized', sa.Boolean(), nullable=False),
    sa.Column('finalized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['inspector_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['reports.id'], ),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_report_no'), 'reports', ['report_no'], unique=False)
    op.create_table('defects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_defects_report_id'), 'defects', ['report_id'], unique=False)
    op.create_table('photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('caption', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_photos_report_id'), 'photos', ['report_id'], unique=False)
    op.create_table('report_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('template', sa.String(length=20), nullable=False),
    sa.Column('language', sa.String(length=20), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_path')
    )
    op.create_index(op.f('ix_report_versions_report_id'), 'report_versions', ['report_id'], unique=False)
    op.create_table('test_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('standard', sa.String(length=160), nullable=False),
    sa.Column('result', sa.String(length=40), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_results_report_id'), 'test_results', ['report_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_results_report_id'), table_name='test_results')
    op.drop_table('test_results')
    op.drop_index(op.f('ix_report_versions_report_id'), table_name='report_versions')
    op.drop_table('report_versions')
    op.drop_index(op.f('ix_photos_report_id'), table_name='photos')
    op.drop_table('photos')
    op.drop_index(op.f('ix_defects_report_id'), table_name='defects')
    op.drop_table('defects')
    op.drop_index(op.f('ix_reports_report_no'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_purchase_orders_po_no'), table_name='purchase_orders')
    op.drop_table('purchase_orders')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_table('test_templates')
    op.drop_table('settings')
    op.drop_index(op.f('ix_products_item_no'), table_name='products')
    op.drop_table('products')
    op.drop_table('defect_categories')
    op.drop_table('customers')
    op.drop_table('aql_rules')
    # ### end Alembic commands ###
