"""AI assisted QC workflow

Revision ID: 93bea73d873a
Revises: 1fa27814b6c2
Create Date: 2026-07-15 10:23:05.835789
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '93bea73d873a'
down_revision: Union[str, Sequence[str], None] = '1fa27814b6c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    expected = {'photo_checklist_templates', 'po_imports', 'po_items', 'ai_analysis_runs', 'extracted_fields', 'report_photo_slots', 'report_sources', 'ai_findings', 'ai_observations', 'photo_evidence', 'qc_decisions'}
    existing = set(sa.inspect(op.get_bind()).get_table_names())
    present = expected & existing
    if present:
        missing = expected - existing
        if missing:
            raise RuntimeError(f"AI workflow schema is incomplete; back up and repair missing tables before migration: {sorted(missing)}")
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photo_checklist_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('slot_key', sa.String(length=80), nullable=False),
    sa.Column('label', sa.String(length=180), nullable=False),
    sa.Column('instruction', sa.Text(), nullable=False),
    sa.Column('example_path', sa.String(length=500), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_photo_checklist_templates_customer_id'), 'photo_checklist_templates', ['customer_id'], unique=False)
    op.create_index(op.f('ix_photo_checklist_templates_product_id'), 'photo_checklist_templates', ['product_id'], unique=False)
    op.create_index(op.f('ix_photo_checklist_templates_slot_key'), 'photo_checklist_templates', ['slot_key'], unique=False)
    op.create_table('po_imports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('mime_type', sa.String(length=120), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('prompt_version', sa.String(length=40), nullable=False),
    sa.Column('schema_version', sa.String(length=40), nullable=False),
    sa.Column('request_id', sa.String(length=160), nullable=False),
    sa.Column('raw_result', sa.Text(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_po_imports_status'), 'po_imports', ['status'], unique=False)
    op.create_table('po_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('po_import_id', sa.Integer(), nullable=False),
    sa.Column('item_index', sa.Integer(), nullable=False),
    sa.Column('review_status', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['po_import_id'], ['po_imports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_po_items_po_import_id'), 'po_items', ['po_import_id'], unique=False)
    op.create_table('ai_analysis_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('prompt_version', sa.String(length=40), nullable=False),
    sa.Column('schema_version', sa.String(length=40), nullable=False),
    sa.Column('request_id', sa.String(length=160), nullable=False),
    sa.Column('raw_result', sa.Text(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_analysis_runs_report_id'), 'ai_analysis_runs', ['report_id'], unique=False)
    op.create_index(op.f('ix_ai_analysis_runs_status'), 'ai_analysis_runs', ['status'], unique=False)
    op.create_table('extracted_fields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('po_item_id', sa.Integer(), nullable=False),
    sa.Column('field_key', sa.String(length=100), nullable=False),
    sa.Column('raw_value', sa.Text(), nullable=False),
    sa.Column('normalized_value', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source_ref', sa.Text(), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['po_item_id'], ['po_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extracted_fields_field_key'), 'extracted_fields', ['field_key'], unique=False)
    op.create_index(op.f('ix_extracted_fields_po_item_id'), 'extracted_fields', ['po_item_id'], unique=False)
    op.create_table('report_photo_slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('template_slot_id', sa.Integer(), nullable=True),
    sa.Column('slot_key', sa.String(length=80), nullable=False),
    sa.Column('label', sa.String(length=180), nullable=False),
    sa.Column('instruction', sa.Text(), nullable=False),
    sa.Column('example_path', sa.String(length=500), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_slot_id'], ['photo_checklist_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_photo_slots_report_id'), 'report_photo_slots', ['report_id'], unique=False)
    op.create_index(op.f('ix_report_photo_slots_slot_key'), 'report_photo_slots', ['slot_key'], unique=False)
    op.create_table('report_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('po_item_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['po_item_id'], ['po_items.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_sources_po_item_id'), 'report_sources', ['po_item_id'], unique=False)
    op.create_index(op.f('ix_report_sources_report_id'), 'report_sources', ['report_id'], unique=True)
    op.create_table('ai_findings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_run_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('description_en', sa.String(length=255), nullable=False),
    sa.Column('suggested_severity', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence_photo_ids', sa.Text(), nullable=False),
    sa.Column('duplicate_group', sa.String(length=120), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('confirmed_defect_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['ai_analysis_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['confirmed_defect_id'], ['defects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_findings_analysis_run_id'), 'ai_findings', ['analysis_run_id'], unique=False)
    op.create_index(op.f('ix_ai_findings_status'), 'ai_findings', ['status'], unique=False)
    op.create_table('ai_observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_run_id', sa.Integer(), nullable=False),
    sa.Column('photo_id', sa.Integer(), nullable=True),
    sa.Column('slot_key', sa.String(length=80), nullable=False),
    sa.Column('clarity_status', sa.String(length=40), nullable=False),
    sa.Column('ocr_text', sa.Text(), nullable=False),
    sa.Column('barcode', sa.Text(), nullable=False),
    sa.Column('date_code', sa.Text(), nullable=False),
    sa.Column('consistency', sa.Text(), nullable=False),
    sa.Column('visible_state', sa.Text(), nullable=False),
    sa.Column('requires_retake', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['ai_analysis_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['photo_id'], ['photos.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_observations_analysis_run_id'), 'ai_observations', ['analysis_run_id'], unique=False)
    op.create_table('photo_evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('photo_id', sa.Integer(), nullable=False),
    sa.Column('slot_id', sa.Integer(), nullable=False),
    sa.Column('original_path', sa.String(length=500), nullable=False),
    sa.Column('processed_path', sa.String(length=500), nullable=False),
    sa.Column('original_checksum', sa.String(length=64), nullable=False),
    sa.Column('processed_checksum', sa.String(length=64), nullable=False),
    sa.Column('upload_source', sa.String(length=20), nullable=False),
    sa.Column('sample_ids', sa.Text(), nullable=False),
    sa.Column('defect_group', sa.String(length=120), nullable=False),
    sa.Column('quality_status', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['photo_id'], ['photos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['slot_id'], ['report_photo_slots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_photo_evidence_photo_id'), 'photo_evidence', ['photo_id'], unique=True)
    op.create_index(op.f('ix_photo_evidence_slot_id'), 'photo_evidence', ['slot_id'], unique=False)
    op.create_table('qc_decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('finding_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('before_json', sa.Text(), nullable=False),
    sa.Column('after_json', sa.Text(), nullable=False),
    sa.Column('affected_quantity', sa.Integer(), nullable=False),
    sa.Column('sample_ids', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['ai_findings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qc_decisions_finding_id'), 'qc_decisions', ['finding_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_qc_decisions_finding_id'), table_name='qc_decisions')
    op.drop_table('qc_decisions')
    op.drop_index(op.f('ix_photo_evidence_slot_id'), table_name='photo_evidence')
    op.drop_index(op.f('ix_photo_evidence_photo_id'), table_name='photo_evidence')
    op.drop_table('photo_evidence')
    op.drop_index(op.f('ix_ai_observations_analysis_run_id'), table_name='ai_observations')
    op.drop_table('ai_observations')
    op.drop_index(op.f('ix_ai_findings_status'), table_name='ai_findings')
    op.drop_index(op.f('ix_ai_findings_analysis_run_id'), table_name='ai_findings')
    op.drop_table('ai_findings')
    op.drop_index(op.f('ix_report_sources_report_id'), table_name='report_sources')
    op.drop_index(op.f('ix_report_sources_po_item_id'), table_name='report_sources')
    op.drop_table('report_sources')
    op.drop_index(op.f('ix_report_photo_slots_slot_key'), table_name='report_photo_slots')
    op.drop_index(op.f('ix_report_photo_slots_report_id'), table_name='report_photo_slots')
    op.drop_table('report_photo_slots')
    op.drop_index(op.f('ix_extracted_fields_po_item_id'), table_name='extracted_fields')
    op.drop_index(op.f('ix_extracted_fields_field_key'), table_name='extracted_fields')
    op.drop_table('extracted_fields')
    op.drop_index(op.f('ix_ai_analysis_runs_status'), table_name='ai_analysis_runs')
    op.drop_index(op.f('ix_ai_analysis_runs_report_id'), table_name='ai_analysis_runs')
    op.drop_table('ai_analysis_runs')
    op.drop_index(op.f('ix_po_items_po_import_id'), table_name='po_items')
    op.drop_table('po_items')
    op.drop_index(op.f('ix_po_imports_status'), table_name='po_imports')
    op.drop_table('po_imports')
    op.drop_index(op.f('ix_photo_checklist_templates_slot_key'), table_name='photo_checklist_templates')
    op.drop_index(op.f('ix_photo_checklist_templates_product_id'), table_name='photo_checklist_templates')
    op.drop_index(op.f('ix_photo_checklist_templates_customer_id'), table_name='photo_checklist_templates')
    op.drop_table('photo_checklist_templates')
    # ### end Alembic commands ###
