"use client";

import { useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { useComplaintData } from "@/components/data-provider";
import { useAuth } from "@/components/auth-provider";
import { ChartCard, DataTable, KpiCard, PageTitle, PieChart, StatusBadge } from "@/components/ui";
import { groupCount, percent } from "@/lib/stats";

type IssueSummary={label:string;value:number};
type SeriesSummary={name:string;label:string;count:number;share:string;issues:IssueSummary[]};
const ALL_SERIES="__all__";
const escapeHtml=(value:unknown)=>String(value??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;");
const exportDate=()=>new Date().toISOString().slice(0,10);

export default function SeriesAnalysis(){
  const router=useRouter();
  const {can}=useAuth();
  const {records,issueTypeLabel,primarySeriesLabel,secondarySeriesDefinitions}=useComplaintData();
  const [periodMode,setPeriodMode]=useState<"year"|"month">("year");
  const [yearChoice,setYearChoice]=useState<number|null>(null);
  const [monthChoice,setMonthChoice]=useState<number|null>(null);
  const [seriesChoice,setSeriesChoice]=useState(ALL_SERIES);
  const [exporting,setExporting]=useState(false);
  const years=useMemo(()=>[...new Set(records.map(r=>Number(r.contactDate.slice(0,4))).filter(Boolean))].sort((a,b)=>b-a),[records]);
  const selectedYear=yearChoice??years[0]??new Date().getFullYear();
  const months=useMemo(()=>[...new Set(records.filter(r=>r.contactDate.startsWith(`${selectedYear}-`)).map(r=>Number(r.contactDate.slice(5,7))).filter(Boolean))].sort((a,b)=>b-a),[records,selectedYear]);
  const selectedMonth=monthChoice??months[0]??new Date().getMonth()+1;
  const periodRecords=useMemo(()=>records.filter(r=>periodMode==="year"?r.contactDate.startsWith(`${selectedYear}-`):r.contactDate.startsWith(`${selectedYear}-${String(selectedMonth).padStart(2,"0")}`)),[records,periodMode,selectedYear,selectedMonth]);
  const primary=useMemo(()=>groupCount(periodRecords,r=>r.primarySeries),[periodRecords]);
  const secondary=useMemo(()=>groupCount(periodRecords,r=>r.secondarySeries),[periodRecords]);
  const summaries=useMemo<SeriesSummary[]>(()=>primary.map(series=>({name:series.name,label:primarySeriesLabel(series.name),count:series.count,share:percent(series.count,periodRecords.length),issues:groupCount(periodRecords.filter(record=>record.primarySeries===series.name),record=>record.issueType?issueTypeLabel(record.issueType):null).map(item=>({label:item.name==="Unspecified"?"未分类":item.name,value:item.count}))})),[primary,periodRecords,primarySeriesLabel,issueTypeLabel]);
  const selectedSummary=seriesChoice===ALL_SERIES?null:summaries.find(item=>item.name===seriesChoice)??null;
  const selectedCount=selectedSummary?.count??periodRecords.length;
  const selectedLabel=selectedSummary?.label??"全部系列";
  const selectedShare=selectedSummary?percent(selectedSummary.count,periodRecords.length):percent(periodRecords.length,periodRecords.length);
  const periodLabel=periodMode==="year"?`${selectedYear} 年`:`${selectedYear} 年 ${selectedMonth} 月`;
  const dataMonths=[...new Set(periodRecords.map(record=>record.contactDate.slice(0,7)).filter(value=>/^\d{4}-\d{2}$/.test(value)))].sort();
  const monthName=(value:string)=>{const [year,month]=value.split("-");return `${year} 年 ${Number(month)} 月`};
  const coverageLabel=!dataMonths.length?"当前范围暂无数据":dataMonths.length===1?`数据月份 ${monthName(dataMonths[0])}`:`数据月份 ${monthName(dataMonths[0])} 至 ${monthName(dataMonths.at(-1)!)}`;
  const periodControls=<div className="flex flex-wrap items-center gap-2"><div className="flex overflow-hidden rounded-lg border border-line bg-white" aria-label="统计周期"><button aria-pressed={periodMode==="year"} onClick={()=>setPeriodMode("year")} className={`h-9 px-4 text-sm font-semibold ${periodMode==="year"?"bg-ink text-white":"text-neutral-600"}`}>年度</button><button aria-pressed={periodMode==="month"} onClick={()=>setPeriodMode("month")} className={`h-9 border-l border-line px-4 text-sm font-semibold ${periodMode==="month"?"bg-ink text-white":"text-neutral-600"}`}>月度</button></div><select aria-label="年份" value={selectedYear} onChange={e=>{setYearChoice(Number(e.target.value));setMonthChoice(null)}} className="field">{(years.length?years:[selectedYear]).map(year=><option key={year} value={year}>{year} 年</option>)}</select>{periodMode==="month"&&<select aria-label="月份" value={selectedMonth} onChange={e=>setMonthChoice(Number(e.target.value))} className="field">{(months.length?months:Array.from({length:12},(_,index)=>index+1)).map(month=><option key={month} value={month}>{month} 月</option>)}</select>}</div>;

  async function exportPdf(){
    if(!can("export_reports"))return;
    setExporting(true);
    const host=document.createElement("div");host.style.cssText="position:fixed;left:-20000px;top:0;width:1120px;background:#fff;z-index:-1";document.body.appendChild(host);
    try{
      const [{default:html2canvas},{jsPDF}]=await Promise.all([import("html2canvas"),import("jspdf")]);await document.fonts.ready;
      const detailGroups:SeriesSummary[][]=[];let currentGroup:SeriesSummary[]=[];let currentIssueRows=0;
      for(const summary of summaries){const rows=Math.max(1,summary.issues.length);if(currentGroup.length&&(currentGroup.length>=3||currentIssueRows+rows>24)){detailGroups.push(currentGroup);currentGroup=[];currentIssueRows=0}currentGroup.push(summary);currentIssueRows+=rows}if(currentGroup.length)detailGroups.push(currentGroup);
      const groups=detailGroups.length?detailGroups:[[]];const pages=1+groups.length;
      const pdf=new jsPDF({orientation:"landscape",unit:"mm",format:"a4",compress:true});
      const renderPage=async(body:string,pageNumber:number)=>{
        const section=document.createElement("section");section.style.cssText="box-sizing:border-box;width:1120px;height:790px;padding:30px 36px;background:#fff;color:#171717;font-family:-apple-system,BlinkMacSystemFont,'PingFang SC','Microsoft YaHei',sans-serif";
        section.innerHTML=`<header style="display:flex;justify-content:space-between;align-items:flex-end;border-bottom:3px solid #f36b21;padding-bottom:10px"><div><div style="font-size:24px;font-weight:800">ZURU ToyQMS 投诉（系列与类型）分析报告</div><div style="margin-top:5px;font-size:12px;color:#666">统计周期 ${escapeHtml(periodLabel)} · ${escapeHtml(coverageLabel)} · 共 ${periodRecords.length} 条投诉 · ${summaries.length} 个系列 · 导出日期 ${exportDate()}</div></div><div style="font-size:12px;color:#777">第 ${pageNumber} / ${pages} 页</div></header>${body}`;
        host.replaceChildren(section);void section.offsetHeight;await new Promise<void>(resolve=>window.requestAnimationFrame(()=>window.requestAnimationFrame(()=>resolve())));
        const canvas=await html2canvas(section,{scale:2.2,width:1120,height:790,windowWidth:1120,windowHeight:790,scrollX:0,scrollY:0,backgroundColor:"#ffffff",logging:false,useCORS:true});
        if(pageNumber>1)pdf.addPage("a4","landscape");pdf.addImage(canvas.toDataURL("image/png"),"PNG",0,0,297,210,undefined,"FAST");host.replaceChildren();
      };
      const leader=summaries[0];const remaining=summaries.slice(1);const restMax=Math.max(1,...remaining.map(item=>item.count));
      const summaryRows=remaining.map((item,index)=>`<div style="display:grid;grid-template-columns:30px 180px minmax(0,1fr) 54px 62px;align-items:center;gap:10px;min-height:35px;border-bottom:1px solid #e5e5e2;font-size:12px"><b style="color:#777">${index+2}</b><b>${escapeHtml(item.label)}</b><div style="height:9px;border-radius:99px;background:#e7e7e4;overflow:hidden"><div style="height:100%;width:${Math.max(2,item.count/restMax*100)}%;background:#f36b21;border-radius:99px"></div></div><b style="text-align:right;font-variant-numeric:tabular-nums">${item.count}</b><span style="text-align:right;color:#555;font-variant-numeric:tabular-nums">${item.share}</span></div>`).join("");
      const leaderCard=leader?`<div style="display:grid;grid-template-columns:minmax(0,1fr) 180px;align-items:center;gap:18px;margin-top:12px;border:1px solid #f6b38e;background:#fff0e5;border-radius:13px;padding:15px 18px"><div><div style="font-size:11px;font-weight:800;color:#f36b21">投诉最高系列</div><div style="margin-top:4px;font-size:22px;font-weight:800">${escapeHtml(leader.label)}</div><div style="margin-top:10px;height:10px;border-radius:99px;background:#ffd8c2;overflow:hidden"><div style="height:100%;width:100%;background:#f36b21;border-radius:99px"></div></div></div><div style="text-align:right"><b style="font-size:34px;color:#f36b21;font-variant-numeric:tabular-nums">${leader.count}</b><span style="margin-left:12px;font-size:16px;font-weight:800">${leader.share}</span></div></div>`:"";
      await renderPage(`<section style="margin-top:18px;border:1px solid #dcdcd8;background:#f7f7f5;border-radius:14px;padding:18px 20px"><div style="display:flex;align-items:flex-end;justify-content:space-between"><div><div style="font-size:18px;font-weight:800">各系列投诉数量</div><div style="margin-top:4px;font-size:11px;color:#666">${escapeHtml(periodLabel)} · ${escapeHtml(coverageLabel)} · 所有系列均保留数量与占比</div></div><div style="text-align:right;font-size:12px;color:#666">投诉总数 <b style="margin-left:6px;font-size:22px;color:#171717">${periodRecords.length}</b>　系列 <b style="margin-left:4px;font-size:18px;color:#171717">${summaries.length}</b></div></div>${leaderCard}<div style="margin-top:10px">${summaryRows||(!leader?'<div style="padding:120px 0;text-align:center;color:#999">当前周期暂无系列数据</div>':'')}</div></section>`,1);
      for(let groupIndex=0;groupIndex<groups.length;groupIndex++){
        const blocks=groups[groupIndex].map((series,slot)=>{const issueMax=Math.max(1,...series.issues.map(item=>item.value));const issueRows=series.issues.map((issue,index)=>`<div style="display:grid;grid-template-columns:22px 190px minmax(0,1fr) 42px 58px;align-items:center;gap:10px;min-height:15px;font-size:9.5px"><span style="color:#777;font-weight:700">${index+1}</span><span>${escapeHtml(issue.label)}</span><span style="height:7px;border-radius:99px;background:#dededb;overflow:hidden"><span style="display:block;height:100%;width:${Math.max(3,issue.value/issueMax*100)}%;background:#f36b21;border-radius:99px"></span></span><b style="text-align:right;font-variant-numeric:tabular-nums">${issue.value}</b><span style="text-align:right;color:#555;font-variant-numeric:tabular-nums">${percent(issue.value,series.count)}</span></div>`).join("");return `<section style="box-sizing:border-box;border:1px solid ${slot?"#d4d4d0":"#f2b18c"};background:${slot?"#f0f1f1":"#fff1e7"};border-radius:14px;padding:9px 16px"><div style="display:flex;align-items:flex-end;justify-content:space-between;border-bottom:1px solid #d9d9d5;padding-bottom:5px"><div><div style="font-size:17px;font-weight:800">${escapeHtml(series.label)}</div><div style="margin-top:1px;font-size:10px;color:#666">问题类型 ${series.issues.length} 项 · 比例以本系列投诉数为分母</div></div><div style="text-align:right"><b style="font-size:22px;color:#f36b21">${series.count}</b><span style="margin-left:8px;font-size:12px;font-weight:700">${series.share}</span></div></div><div style="display:grid;gap:1px;margin-top:5px">${issueRows||'<div style="padding:24px 0;text-align:center;color:#888;font-size:11px">暂无问题类型数据</div>'}</div></section>`}).join("");
        await renderPage(`<div style="margin-top:10px"><div style="margin-bottom:7px;font-size:18px;font-weight:800">系列问题类型明细</div><div style="display:grid;gap:9px">${blocks}</div></div>`,groupIndex+2);
      }
      pdf.save(`ZURU-ToyQMS-投诉系列与类型分析报告-${exportDate()}.pdf`);
    }finally{host.remove();setExporting(false)}
  }

  return <><PageTitle title="系列分析" description="主要系列来自工作表名称；次要系列按已配置的系列层级检查数据情况。" action="查看投诉" secondary={exporting?"正在生成PDF…":"导出PDF"} onAction={()=>router.push("/complaints")} onSecondary={()=>void exportPdf()}/><div className="mb-3 flex justify-end">{periodControls}</div><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><KpiCard label="全系投诉数量" value={String(periodRecords.length)} detail={periodLabel}/><KpiCard label="筛选系列投诉数量" value={String(selectedCount)} detail={selectedLabel}/><KpiCard label="次要系列" value={String(secondary.filter(s=>s.name!=="Unspecified").length)} detail="已识别系列值"/><KpiCard label="筛选系列投诉占比" value={selectedShare} tone="bad" detail={selectedLabel}/></div><div className="mt-3 grid gap-3 xl:grid-cols-[1.35fr_1fr]"><ChartCard title="各系列投诉数量" subtitle={`${periodLabel} · 所有系列均显示数量、占比和比例条`}><SeriesComparison data={primary} total={periodRecords.length} labelOf={primarySeriesLabel} onSelect={name=>router.push(`/complaints?series=${encodeURIComponent(name)}`)}/></ChartCard><ChartCard title="系列问题类型" subtitle={`${periodLabel} · ${selectedSummary?selectedSummary.label:"全部系列明细"}`} action={<select aria-label="选择系列" value={seriesChoice} onChange={e=>setSeriesChoice(e.target.value)} className="field min-w-40"><option value={ALL_SERIES}>全部系列</option>{primary.map(item=><option key={item.name} value={item.name}>{primarySeriesLabel(item.name)}</option>)}</select>}>{selectedSummary?<PieChart data={selectedSummary.issues} showCountColumn/>:<AllSeriesIssues summaries={summaries}/>}</ChartCard></div><div className="mt-3"><DataTable columns={["主要系列","投诉数","投诉占比","次要系列数据情况","状态"]} rows={primary.map(s=>{const configured=secondarySeriesDefinitions.some(item=>item.primarySeriesName===s.name);const covered=periodRecords.filter(r=>r.primarySeries===s.name&&r.secondarySeries).length;const missing=s.count-covered;if(!configured)return [<b key={s.name}>{primarySeriesLabel(s.name)}</b>,s.count,percent(s.count,periodRecords.length),"—",<StatusBadge key="status" tone="neutral">无次要系列</StatusBadge>];return [<b key={s.name}>{primarySeriesLabel(s.name)}</b>,s.count,percent(s.count,periodRecords.length),percent(covered,s.count),<StatusBadge key="status" tone={missing?"warning":"good"}>{missing?`缺失 ${missing} 条`:"完整"}</StatusBadge>]})}/></div></>;
}

function AllSeriesIssues({summaries}:{summaries:SeriesSummary[]}){if(!summaries.length)return <div className="grid min-h-64 place-items-center text-sm text-neutral-400">当前周期暂无系列问题类型数据</div>;return <div className="max-h-[34rem] space-y-3 overflow-y-auto pr-1">{summaries.map(series=><section key={series.name} className="rounded-xl border border-line bg-white p-3"><div className="flex items-end justify-between gap-3 border-b border-line pb-2"><div><h3 className="font-bold">{series.label}</h3><p className="text-[10px] text-neutral-500">占全部投诉 {series.share}</p></div><div className="text-right"><b className="text-lg tabular-nums text-accent">{series.count}</b><span className="ml-1 text-xs text-neutral-500">条</span></div></div><div className="mt-2 space-y-1.5">{series.issues.map((issue,index)=><div key={issue.label} className="grid grid-cols-[1.5rem_minmax(6rem,1fr)_minmax(5rem,1fr)_2.5rem_3.5rem] items-center gap-2 text-xs"><span className="font-bold text-neutral-400">{index+1}</span><span className="truncate">{issue.label}</span><span className="h-1.5 overflow-hidden rounded-full bg-neutral-100"><span className="block h-full rounded-full bg-orange-400" style={{width:`${Math.max(3,issue.value/series.count*100)}%`}}/></span><b className="text-right tabular-nums">{issue.value}</b><span className="text-right tabular-nums text-neutral-500">{percent(issue.value,series.count)}</span></div>)}</div></section>)}</div>}

function SeriesComparison({data,total,labelOf,onSelect}:{data:{name:string;count:number}[];total:number;labelOf:(name:string)=>string;onSelect:(name:string)=>void}){const [leader,...rest]=data;const restMax=Math.max(1,...rest.map(item=>item.count));if(!leader)return <div className="grid min-h-64 place-items-center text-sm text-neutral-400">当前周期暂无系列数据</div>;return <div className="space-y-4"><button type="button" onClick={()=>onSelect(leader.name)} className="group grid w-full gap-3 rounded-xl border border-orange-200 bg-orange-50/80 p-4 text-left transition hover:border-accent sm:grid-cols-[minmax(0,1fr)_auto] sm:items-center"><div><div className="text-[11px] font-bold uppercase tracking-wider text-accent">投诉最高系列</div><div className="mt-1 text-xl font-bold text-ink">{labelOf(leader.name)}</div><div className="mt-3 h-2 overflow-hidden rounded-full bg-orange-100"><div className="h-full w-full rounded-full bg-accent"/></div></div><div className="sm:text-right"><div className="text-3xl font-bold tabular-nums text-accent">{leader.count}</div><div className="text-xs text-neutral-500">{percent(leader.count,total)}</div></div></button><div><div className="mb-2 flex items-center justify-between text-[11px] text-neutral-500"><span>其他系列增强对比</span><span>数值、占比和比例条全部保留</span></div><div className="space-y-2">{rest.map((item,index)=><button type="button" key={item.name} onClick={()=>onSelect(item.name)} className="group grid w-full grid-cols-[1.5rem_minmax(6rem,1fr)_minmax(7rem,2fr)_3.5rem_3.5rem] items-center gap-2 rounded-lg px-2 py-1.5 text-left hover:bg-orange-50"><span className="text-xs font-bold text-neutral-400">{index+2}</span><span className="truncate text-sm font-semibold">{labelOf(item.name)}</span><span className="h-2 overflow-hidden rounded-full bg-neutral-100"><span className="block h-full rounded-full bg-orange-400 transition group-hover:bg-accent" style={{width:`${Math.max(5,item.count/restMax*100)}%`}}/></span><b className="text-right text-sm tabular-nums">{item.count}</b><span className="text-right text-xs tabular-nums text-neutral-500">{percent(item.count,total)}</span></button>)}</div></div></div>}
