"use client";
import { useRef, useState, type DragEvent } from "react";
import { CheckCircleIcon, DocumentArrowUpIcon, ExclamationTriangleIcon } from "@heroicons/react/24/outline";
import { DataTable, KpiCard, PageTitle, StatusBadge } from "@/components/ui";
import { useComplaintData } from "@/components/data-provider";
import { parseExcelFile } from "@/lib/excel";
import type { ImportPreview, ImportSummary } from "@/lib/types";

export default function ImportCenter(){
  const input=useRef<HTMLInputElement>(null); const {records,confirmImport,issueTypeLabel,primarySeriesLabel,secondarySeriesLabel}=useComplaintData();
  const [preview,setPreview]=useState<ImportPreview|null>(null); const [summary,setSummary]=useState<ImportSummary|null>(null);
  const [busy,setBusy]=useState(false); const [error,setError]=useState(""); const [tab,setTab]=useState<"preview"|"duplicates"|"invalid">("preview"); const [dragActive,setDragActive]=useState(false);
  async function select(file?:File){if(!file)return;setBusy(true);setError("");setSummary(null);try{if(!file.name.toLowerCase().endsWith(".xlsx"))throw new Error("仅支持 .xlsx 文件");setPreview(await parseExcelFile(file,records));}catch(e){setError(e instanceof Error?e.message:"无法解析工作簿")}finally{setBusy(false);if(input.current)input.current.value=""}}
  function dropFile(event:DragEvent<HTMLDivElement>){event.preventDefault();setDragActive(false);void select(event.dataTransfer.files?.[0])}
  async function commit(){if(!preview)return;setBusy(true);try{setSummary(await confirmImport(preview));setPreview(null)}finally{setBusy(false)}}
  return <><PageTitle title="导入中心" description="上传累计 Excel 投诉文件，预览规范化记录、比较重复项并确认导入新记录。" action="导入历史"/>
    {!preview&&!summary&&<div onDragEnter={event=>{event.preventDefault();setDragActive(true)}} onDragOver={event=>{event.preventDefault();event.dataTransfer.dropEffect="copy";setDragActive(true)}} onDragLeave={event=>{if(event.currentTarget===event.target)setDragActive(false)}} onDrop={dropFile} className={`card grid min-h-80 place-items-center border-2 border-dashed p-8 text-center transition ${dragActive?"border-accent bg-orange-100":"border-orange-200 bg-white"}`}><div><DocumentArrowUpIcon className="mx-auto h-12 w-12 text-accent"/><h2 className="mt-4 text-xl font-bold">将投诉工作簿拖放到这里</h2><p className="mt-2 text-sm text-neutral-500">每个工作表作为主要系列 · Range Name 作为次要系列</p><label aria-disabled={busy} className={`btn-accent relative mt-5 overflow-hidden ${busy?"pointer-events-none opacity-60":"cursor-pointer"}`}><span>{busy?"正在解析工作簿…":"选择 .xlsx 文件"}</span><input id="complaint-import-file" ref={input} type="file" accept=".xlsx,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" disabled={busy} className="absolute inset-0 h-full w-full cursor-pointer opacity-0" onChange={event=>void select(event.target.files?.[0])}/></label>{error&&<p className="mt-4 text-sm text-red-600">{error}</p>}</div></div>}
    {preview&&<><div className="mb-5 grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><KpiCard label="总行数" value={String(preview.totalRows)}/><KpiCard label="新记录" value={String(preview.newRows.length)} tone="good"/><KpiCard label="重复记录" value={String(preview.duplicateRows.length)} tone="accent"/><KpiCard label="无效记录" value={String(preview.invalidRows.length)} tone={preview.invalidRows.length?"bad":"good"}/><KpiCard label="已导入" value="0" detail="等待确认"/></div>
      <div className="card mb-5 p-5"><div className="flex flex-col justify-between gap-4 md:flex-row md:items-center"><div><div className="label">导入预览</div><h2 className="mt-1 font-bold">{preview.fileName}</h2><p className="mt-1 text-xs text-neutral-500">共 {preview.worksheets.length} 个工作表：{preview.worksheets.join("、")}</p></div><div className="flex gap-2"><button onClick={()=>setPreview(null)} className="btn-secondary">取消</button><button disabled={busy} onClick={()=>void commit()} className="btn-accent">确认导入 {preview.newRows.length} 条新记录</button></div></div></div>
      <div className="mb-4 flex gap-2">{([['preview',`新记录（${preview.newRows.length}）`],['duplicates',`重复记录（${preview.duplicateRows.length}）`],['invalid',`无效记录（${preview.invalidRows.length}）`]] as const).map(([id,label])=><button key={id} onClick={()=>setTab(id)} className={tab===id?"btn-primary":"btn-secondary"}>{label}</button>)}</div>
      {tab==="preview"&&<DataTable columns={["来源行","主要系列","次要系列","联络日期","SKU","国家","问题类型"]} rows={preview.newRows.map(r=>[`${r.sourceWorksheetName} · 第 ${r.sourceRowNumber} 行`,<b key="p">{primarySeriesLabel(r.primarySeries)}</b>,secondarySeriesLabel(r.secondarySeries,r.primarySeries),r.contactDate,r.productSku,r.country,r.issueType?issueTypeLabel(r.issueType):<StatusBadge key="u" tone="warning">未分类</StatusBadge>])}/>} 
      {tab==="duplicates"&&(preview.duplicateRows.length?<DataTable columns={["新记录","匹配现有记录","主要系列","SKU","联络日期","处理结果"]} rows={preview.duplicateRows.map(d=>[`${d.incoming.sourceWorksheetName} · 第 ${d.incoming.sourceRowNumber} 行`,`${d.existing.sourceFileName} · 第 ${d.existing.sourceRowNumber} 行`,primarySeriesLabel(d.incoming.primarySeries),d.incoming.productSku,d.incoming.contactDate,<StatusBadge key="skip" tone="warning">自动跳过</StatusBadge>])}/>:<Empty text="未检测到重复记录"/>)}
      {tab==="invalid"&&(preview.invalidRows.length?<DataTable columns={["工作表","行号","校验问题","结果"]} rows={preview.invalidRows.map(r=>[r.worksheet,r.rowNumber,r.reasons.join("；"),<StatusBadge key="invalid" tone="bad">不导入</StatusBadge>])}/>:<Empty text="未检测到无效记录"/>)}
    </>}
    {summary&&<div className="card p-8 text-center"><CheckCircleIcon className="mx-auto h-14 w-14 text-emerald-500"/><h2 className="mt-4 text-2xl font-bold">导入完成</h2><p className="mt-2 text-sm text-neutral-500">已导入 {summary.importedRows} 条 · 跳过 {summary.duplicateRows} 条重复记录 · 排除 {summary.invalidRows} 条无效记录</p><div className="mx-auto mt-6 grid max-w-3xl gap-4 sm:grid-cols-5"><Mini n={summary.totalRows} l="总数"/><Mini n={summary.newRows} l="新增"/><Mini n={summary.duplicateRows} l="重复"/><Mini n={summary.invalidRows} l="无效"/><Mini n={summary.importedRows} l="已导入"/></div><button onClick={()=>setSummary(null)} className="btn-accent mt-6">继续导入文件</button></div>}
    <div className="mt-5 flex gap-3 rounded-xl border border-orange-200 bg-orange-50 p-4 text-sm text-orange-900"><ExclamationTriangleIcon className="h-5 w-5 shrink-0"/><p><b>累计文件去重规则：</b>规范化匹配联络日期、产品 SKU、投诉内容、国家、店铺、批次代码和主要系列。重复记录会展示对比并自动跳过。</p></div>
  </>}
function Empty({text}:{text:string}){return <div className="card p-10 text-center text-sm text-neutral-500">{text}</div>}
function Mini({n,l}:{n:number;l:string}){return <div className="rounded-lg bg-neutral-50 p-3"><b className="text-xl">{n}</b><div className="text-xs text-neutral-500">{l}</div></div>}
