using System.Data;
using System.Text.Json;
using IndoShipping.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;

namespace IndoShipping.Api.Features.Bootstrap;

/// <summary>
/// Applies one-time, idempotent corrections to existing production data.
/// Each migration records a marker in settings so user edits made afterwards
/// are not overwritten on every application restart.
/// </summary>
public static class DataMigrations
{
    private const string ReplaceHsDictionaryKey =
        "data_migration:2026-08-13-replace-hs-dictionary-v1";

    public static async Task ApplyAsync(AppDbContext db, ILogger logger)
    {
        var connection = db.Database.GetDbConnection();
        if (connection.State != ConnectionState.Open)
            await connection.OpenAsync();

        // This is deliberately outside the one-time HS migration below: older databases
        // must receive the translation-memory table even when the HS marker already exists.
        await using (var ensureTranslations = connection.CreateCommand())
        {
            ensureTranslations.CommandText = """
                CREATE TABLE IF NOT EXISTS dict_translation (
                    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    keyword VARCHAR(256) NOT NULL,
                    english_name VARCHAR(512) NOT NULL,
                    active BOOLEAN NOT NULL DEFAULT TRUE,
                    source VARCHAR(32) NOT NULL DEFAULT 'manual',
                    priority INT NOT NULL DEFAULT 100,
                    updated_at TIMESTAMP(0) NOT NULL DEFAULT now(),
                    CONSTRAINT "UQ_dict_translation_keyword" UNIQUE (keyword)
                );
                CREATE INDEX IF NOT EXISTS "IX_dict_translation_active"
                    ON dict_translation(active, priority);

                INSERT INTO dict_translation(keyword, english_name, source, priority)
                SELECT trim(name_zh), min(trim(name_en)), 'existing-material', 100
                FROM materials
                WHERE trim(COALESCE(name_zh, '')) <> '' AND trim(COALESCE(name_en, '')) <> ''
                GROUP BY trim(name_zh)
                HAVING COUNT(DISTINCT lower(trim(name_en))) = 1
                ON CONFLICT (keyword) DO NOTHING;
                """;
            await ensureTranslations.ExecuteNonQueryAsync();
        }

        await using var transaction = await connection.BeginTransactionAsync(IsolationLevel.Serializable);

        await using var claim = connection.CreateCommand();
        claim.Transaction = transaction;
        claim.CommandText = $"""
            INSERT INTO settings ("key", value, updated_at)
            VALUES ('{ReplaceHsDictionaryKey}', 'running', now())
            ON CONFLICT ("key") DO NOTHING
            RETURNING 1;
            """;

        if (await claim.ExecuteScalarAsync() is null)
        {
            await transaction.RollbackAsync();
            return;
        }

        var entries = await LoadHsDictionaryAsync();
        if (entries.Count == 0)
            throw new InvalidOperationException("Bundled HS dictionary is empty; refusing to replace existing data.");
        if (entries.Any(entry => entry.HsId.Length != 8 || !entry.HsId.All(char.IsDigit)))
            throw new InvalidOperationException("Every Indonesian HS code must contain exactly eight digits.");
        if (entries.GroupBy(entry => entry.Keyword, StringComparer.OrdinalIgnoreCase).Any(group => group.Count() > 1))
            throw new InvalidOperationException("Bundled HS dictionary contains duplicate keywords.");

        await using var replace = connection.CreateCommand();
        replace.Transaction = transaction;
        replace.CommandText = "DELETE FROM dict_hs;";
        await replace.ExecuteNonQueryAsync();

        await using var insert = connection.CreateCommand();
        insert.Transaction = transaction;
        insert.CommandText = """
            INSERT INTO dict_hs (keyword, hs_cn, hs_id, priority)
            VALUES (@keyword, @hs_cn, @hs_id, @priority);
            """;
        var keyword = insert.CreateParameter(); keyword.ParameterName = "keyword"; insert.Parameters.Add(keyword);
        var hsCn = insert.CreateParameter(); hsCn.ParameterName = "hs_cn"; insert.Parameters.Add(hsCn);
        var hsId = insert.CreateParameter(); hsId.ParameterName = "hs_id"; insert.Parameters.Add(hsId);
        var priority = insert.CreateParameter(); priority.ParameterName = "priority"; insert.Parameters.Add(priority);

        foreach (var entry in entries)
        {
            keyword.Value = entry.Keyword;
            hsCn.Value = entry.HsCn;
            hsId.Value = entry.HsId;
            priority.Value = entry.Priority;
            await insert.ExecuteNonQueryAsync();
        }

        await using var complete = connection.CreateCommand();
        complete.Transaction = transaction;
        complete.CommandText = $"""
            UPDATE settings
            SET value = 'applied', updated_at = now()
            WHERE "key" = '{ReplaceHsDictionaryKey}';
            """;
        await complete.ExecuteNonQueryAsync();
        await transaction.CommitAsync();

        logger.LogInformation("Replaced HS dictionary with {Count} validated entries.", entries.Count);
    }

    private static async Task<IReadOnlyList<HsDictionaryEntry>> LoadHsDictionaryAsync()
    {
        var path = Path.Combine(AppContext.BaseDirectory, "seed", "hs-dictionary.json");
        if (!File.Exists(path))
            throw new FileNotFoundException($"Bundled HS dictionary not found: {path}");

        await using var stream = File.OpenRead(path);
        return await JsonSerializer.DeserializeAsync<List<HsDictionaryEntry>>(
                   stream,
                   new JsonSerializerOptions { PropertyNameCaseInsensitive = true })
               ?? [];
    }

    private sealed record HsDictionaryEntry(string Keyword, string HsCn, string HsId, int Priority);
}
