"use client";
import { useEffect,useMemo,useRef,useState,type DragEvent } from "react";
import { ChevronLeftIcon,ChevronRightIcon,DocumentArrowUpIcon,XMarkIcon } from "@heroicons/react/24/outline";
import { useComplaintData } from "@/components/data-provider";
import { DataTable, Filters, KpiCard, PageTitle, StatusBadge } from "@/components/ui";
import type { ComplaintRecord, TranslationStatus } from "@/lib/types";
import { previewTranslationWorkbook } from "@/lib/translation-import";

const statusLabels:Record<TranslationStatus,string>={pending:"待翻译",translated:"待审核",reviewed:"已确认",failed:"翻译失败"};
const statusTones:Record<TranslationStatus,"neutral"|"good"|"warning"|"bad"|"info">={pending:"warning",translated:"info",reviewed:"good",failed:"bad"};
const chineseOf=(record:ComplaintRecord)=>record.complaintMessageZhFinal||record.complaintMessageZhMachine||"";

export default function Translation(){
  const {records,primarySeriesLabel,updateComplaintTranslation,importTranslations,confirmTranslations,resetOfflineTranslations}=useComplaintData();
  const translationFileRef=useRef<HTMLInputElement>(null);
  const resetMigrationRef=useRef(false);
  const [search,setSearch]=useState("");const [status,setStatus]=useState("");const [series,setSeries]=useState("");const [editingId,setEditingId]=useState<string|null>(null);const [notice,setNotice]=useState("");const [selected,setSelected]=useState<Set<string>>(new Set());const [busy,setBusy]=useState(false);const [tablePage,setTablePage]=useState(1);const [dragActive,setDragActive]=useState(false);const [importOpen,setImportOpen]=useState(false);const [importBusy,setImportBusy]=useState(false);const pageSize=20;
  const seriesOptions=useMemo(()=>[...new Set(records.map(record=>record.primarySeries).filter(Boolean))].sort((a,b)=>primarySeriesLabel(a).localeCompare(primarySeriesLabel(b),"zh-CN")),[records,primarySeriesLabel]);
  const counts=useMemo(()=>({pending:records.filter(record=>record.translationStatus==="pending").length,translated:records.filter(record=>record.translationStatus==="translated").length,reviewed:records.filter(record=>record.translationStatus==="reviewed").length,failed:records.filter(record=>record.translationStatus==="failed").length}),[records]);
  const filtered=useMemo(()=>records.filter(record=>{const query=search.trim().toLowerCase();const matches=!query||[record.sourceSubmissionId,record.productSku,record.primarySeries,primarySeriesLabel(record.primarySeries),record.complaintMessageOriginal,chineseOf(record)].some(value=>value?.toLowerCase().includes(query));return matches&&(!status||record.translationStatus===status)&&(!series||record.primarySeries===series)}),[records,search,status,series,primarySeriesLabel]);
  const reviewQueue=useMemo(()=>filtered.filter(record=>Boolean(chineseOf(record))),[filtered]);
  const editing=records.find(record=>record.id===editingId)||null;const editingIndex=editing?reviewQueue.findIndex(record=>record.id===editing.id):-1;
  const badOfflineCount=records.filter(record=>record.translationProvider==="codex-offline"&&record.translationModel==="argos-en-zh").length;
  const reviewTotal=counts.translated+counts.reviewed;const progress=reviewTotal?Math.round(counts.reviewed/reviewTotal*100):0;
  const selectableFiltered=filtered.filter(record=>record.translationStatus!=="reviewed"&&Boolean(chineseOf(record))).map(record=>record.id);
  const currentPageRecords=filtered.slice((tablePage-1)*pageSize,tablePage*pageSize);const selectableCurrentPage=currentPageRecords.filter(record=>record.translationStatus!=="reviewed"&&Boolean(chineseOf(record))).map(record=>record.id);const allCurrentPageSelected=selectableCurrentPage.length>0&&selectableCurrentPage.every(id=>selected.has(id));
  const flash=(message:string)=>{setNotice(message);window.setTimeout(()=>setNotice(""),3600)};
  useEffect(()=>{const valid=new Set(records.map(record=>record.id));setSelected(current=>new Set([...current].filter(id=>valid.has(id))))},[records]);
  useEffect(()=>setTablePage(1),[search,status,series]);
  useEffect(()=>{if(resetMigrationRef.current||!badOfflineCount)return;resetMigrationRef.current=true;void resetOfflineTranslations().then(count=>{setSelected(new Set());setEditingId(null);flash(`已自动清除 ${count} 条错误离线译文；英文原文、投诉和分类数据均已保留。`)})},[badOfflineCount,resetOfflineTranslations]);
  const openFirstReview=()=>{const first=reviewQueue.find(record=>record.translationStatus!=="reviewed")||reviewQueue[0];if(first)setEditingId(first.id);else flash("当前筛选范围内没有可审核的中文译文。");};
  const toggle=(id:string)=>setSelected(current=>{const next=new Set(current);if(next.has(id))next.delete(id);else next.add(id);return next});
  const toggleCurrentPage=()=>setSelected(current=>{const next=new Set(current);if(allCurrentPageSelected)selectableCurrentPage.forEach(id=>next.delete(id));else selectableCurrentPage.forEach(id=>next.add(id));return next});
  const handleTranslationFile=async(file:File)=>{setImportBusy(true);try{setNotice("正在读取并匹配译文…");const preview=await previewTranslationWorkbook(file);const summary=await importTranslations(preview.validRows,preview.invalidRows);setImportOpen(false);flash(`译文导入完成：成功 ${summary.importedRows} 条，未匹配 ${summary.unmatchedRows} 条，无效 ${summary.invalidRows} 条。`)}catch(reason){flash(reason instanceof Error?reason.message:"译文文件无法读取。")}finally{setImportBusy(false);if(translationFileRef.current)translationFileRef.current.value=""}};
  const acceptTranslationFile=(file:File|undefined)=>{if(!file)return;if(!file.name.toLowerCase().endsWith(".xlsx")){flash("仅支持 .xlsx 格式的译文文件。");return}void handleTranslationFile(file)};
  const dropTranslationFile=(event:DragEvent<HTMLDivElement>)=>{event.preventDefault();setDragActive(false);acceptTranslationFile(event.dataTransfer.files[0])};
  const batchConfirm=async()=>{const ids=[...selected].filter(id=>{const record=records.find(item=>item.id===id);return record&&record.translationStatus!=="reviewed"&&Boolean(chineseOf(record))});if(!ids.length){flash("请先选择至少一条有中文译文的待审核记录。");return}if(!window.confirm(`即将批量确认 ${ids.length} 条中文译文。确认后这些记录会标记为“已确认”，是否继续？`))return;setBusy(true);try{const count=await confirmTranslations(ids);setSelected(new Set());flash(`已批量确认 ${count} 条中文译文。`)}finally{setBusy(false)}};
  const resetBadTranslations=async()=>{if(!badOfflineCount){flash("没有检测到本批错误离线译文。");return}if(!window.confirm(`将清除 ${badOfflineCount} 条由错误离线模型生成的中文译文，并恢复为“待翻译”。英文原文和投诉数据不会删除。是否继续？`))return;setBusy(true);try{const count=await resetOfflineTranslations();setSelected(new Set());setEditingId(null);flash(`已清除 ${count} 条错误离线译文，英文原文和投诉数据均已保留。`)}finally{setBusy(false)}};
  const saveEditor=async(text:string,mode:"draft"|"reviewed"|"next")=>{if(!editing)return;const nextId=editingIndex>=0?reviewQueue[editingIndex+1]?.id:null;await updateComplaintTranslation(editing.id,{complaintMessageZhMachine:text,complaintMessageZhFinal:mode==="draft"?null:text,translationStatus:mode==="draft"?"translated":"reviewed",translationProvider:"manual-local",translationModel:null});if(mode==="next"&&nextId){setEditingId(nextId);flash("译文已确认，已进入下一条。")}else{setEditingId(null);flash(mode==="draft"?"译文已保存并保持待审核状态。":"中文译文已确认。")}};
  return <><PageTitle title="翻译中心" description="审核工作台：英文投诉原文永久保留，中文译文经人工确认后成为最终版本。" action="开始审核" secondary="导入译文" onAction={openFirstReview} onSecondary={()=>setImportOpen(true)}/>
    <div className="mb-3 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><KpiCard className="border-sky-200 bg-sky-100" label="英文原文" value={String(records.length)}/><KpiCard className="border-amber-200 bg-amber-100" label="待翻译" value={String(counts.pending+counts.failed)} tone="accent"/><KpiCard className="border-orange-200 bg-orange-100" label="待审核" value={String(counts.translated)} tone="accent"/><KpiCard className="border-emerald-200 bg-emerald-100" label="已确认" value={String(counts.reviewed)} tone="good"/></div>
    <section className="mb-3 rounded-xl border border-orange-200 bg-orange-50 p-3"><div className="flex flex-wrap items-center justify-between gap-3 text-sm"><div><b>审核进度：</b>{counts.reviewed} / {reviewTotal} 条已确认（{progress}%）</div><div className="flex flex-wrap gap-2"><button disabled={busy||!selectableFiltered.length} onClick={()=>setSelected(new Set(selectableFiltered))} className="btn-secondary">选择当前筛选结果</button><button disabled={busy||!selected.size} onClick={()=>setSelected(new Set())} className="btn-secondary">取消选择</button><button disabled={busy||!selected.size} onClick={()=>void batchConfirm()} className="btn-accent">批量确认（{selected.size}）</button><button disabled={busy||!badOfflineCount} onClick={()=>void resetBadTranslations()} className="rounded-lg border border-red-300 bg-white px-3 py-2 text-xs font-semibold text-red-700 disabled:opacity-40">清除错误译文（{badOfflineCount}）</button></div></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-white"><div className="h-full rounded-full bg-accent transition-all" style={{width:`${progress}%`}}/></div></section>
    {notice&&<div className="mb-3 rounded-lg bg-neutral-900 p-3 text-sm text-white">{notice}</div>}
    <div className="sticky top-14 z-20 -mx-1 bg-[#f5f5f3] px-1 pt-1"><Filters searchValue={search} onSearch={setSearch} onFilter={(index,value)=>index===0?setStatus(value):setSeries(value)} placeholder="搜索 SKU、投诉编号、系列或中英文关键词…" groups={[{label:"全部翻译状态",options:(Object.keys(statusLabels) as TranslationStatus[]).map(value=>({value,label:statusLabels[value]}))},{label:"全部系列",options:seriesOptions.map(value=>({value,label:primarySeriesLabel(value)}))}]}/></div>
    <DataTable page={tablePage} onPageChange={setTablePage} pageSize={pageSize} extendedPagination headerTone="accent" stickyHeader stickyHeaderTop="6rem" columns={[<label key="page-select" className="inline-flex cursor-pointer items-center gap-2 whitespace-nowrap"><input type="checkbox" aria-label="选择当前页面" disabled={!selectableCurrentPage.length} checked={allCurrentPageSelected} onChange={toggleCurrentPage} className="h-4 w-4 accent-orange-500"/><span>选择</span></label>,"投诉编号","SKU","系列","英文原文","中文译文","状态","操作"]} rows={filtered.map(record=>[<input key="select" type="checkbox" aria-label={`选择 ${record.sourceSubmissionId||record.productSku}`} checked={selected.has(record.id)} disabled={record.translationStatus==="reviewed"||!chineseOf(record)} onChange={()=>toggle(record.id)} className="h-4 w-4 accent-orange-500"/>,<span key="id" className="whitespace-nowrap">{record.sourceSubmissionId||record.id.slice(0,8)}</span>,<span key="sku" className="whitespace-nowrap">{record.productSku}</span>,<span key="series" className="whitespace-nowrap font-semibold">{primarySeriesLabel(record.primarySeries)}</span>,<span className="clamp-3 block max-w-xl whitespace-pre-wrap break-words leading-6" key="original">{record.complaintMessageOriginal}</span>,<span className={`clamp-3 block max-w-xl whitespace-pre-wrap break-words leading-6 ${chineseOf(record)?"":"text-neutral-400"}`} key="translation">{chineseOf(record)||"暂无中文译文"}</span>,<StatusBadge key="status" tone={statusTones[record.translationStatus]}>{statusLabels[record.translationStatus]}</StatusBadge>,<button onClick={()=>setEditingId(record.id)} className="whitespace-nowrap font-semibold text-accent hover:underline" key="action">{record.translationStatus==="pending"||record.translationStatus==="failed"?"录入译文":"审核译文"}</button>])}/>
    {importOpen&&<div className="fixed inset-0 z-50 grid place-items-center bg-black/45 p-4" onClick={()=>{if(!importBusy)setImportOpen(false)}}><section className="w-full max-w-2xl rounded-2xl bg-white p-5 shadow-2xl" onClick={event=>event.stopPropagation()}><div className="flex items-start justify-between gap-4"><div><div className="label">导入中文译文</div><h2 className="mt-1 text-lg font-bold">选择或拖放译文工作簿</h2><p className="mt-1 text-xs text-neutral-500">仅支持 .xlsx 文件；系统会按投诉记录匹配译文，不会覆盖英文原文。</p></div><button type="button" disabled={importBusy} onClick={()=>setImportOpen(false)} aria-label="关闭导入译文弹窗"><XMarkIcon className="h-5 w-5"/></button></div><div onDragEnter={event=>{event.preventDefault();setDragActive(true)}} onDragOver={event=>{event.preventDefault();event.dataTransfer.dropEffect="copy";setDragActive(true)}} onDragLeave={event=>{if(event.currentTarget===event.target)setDragActive(false)}} onDrop={dropTranslationFile} className={`mt-5 grid min-h-52 place-items-center rounded-xl border-2 border-dashed p-6 text-center transition ${dragActive?"border-accent bg-orange-100":"border-orange-200 bg-orange-50"}`}><div><DocumentArrowUpIcon className="mx-auto h-11 w-11 text-accent"/><div className="mt-3 text-base font-bold text-orange-950">将译文 Excel 文件拖放到这里</div><div className="mt-1 text-xs text-orange-700">或从电脑中选择文件</div><label aria-disabled={importBusy} className={`btn-accent relative mt-4 overflow-hidden ${importBusy?"pointer-events-none opacity-60":"cursor-pointer"}`}><span>{importBusy?"正在导入译文…":"选择 .xlsx 文件"}</span><input id="translation-import-file" ref={translationFileRef} type="file" accept=".xlsx,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" disabled={importBusy} className="absolute inset-0 h-full w-full cursor-pointer opacity-0" onChange={event=>acceptTranslationFile(event.target.files?.[0])}/></label></div></div></section></div>}
    {editing&&<TranslationEditor key={editing.id} record={editing} seriesLabel={primarySeriesLabel(editing.primarySeries)} index={editingIndex} total={reviewQueue.length} hasPrevious={editingIndex>0} hasNext={editingIndex>=0&&editingIndex<reviewQueue.length-1} close={()=>setEditingId(null)} navigate={delta=>{const target=reviewQueue[editingIndex+delta];if(target)setEditingId(target.id)}} save={saveEditor}/>} 
  </>
}

function TranslationEditor({record,seriesLabel,index,total,hasPrevious,hasNext,close,navigate,save}:{record:ComplaintRecord;seriesLabel:string;index:number;total:number;hasPrevious:boolean;hasNext:boolean;close:()=>void;navigate:(delta:number)=>void;save:(text:string,mode:"draft"|"reviewed"|"next")=>Promise<void>}){
  const original=chineseOf(record);const [text,setText]=useState(original);const [busy,setBusy]=useState(false);const [error,setError]=useState("");const dirty=text.trim()!==original.trim();
  const move=(delta:number)=>{if(dirty&&!window.confirm("当前译文尚未保存，切换记录将丢失修改。是否继续？"))return;navigate(delta)};
  useEffect(()=>{const handler=(event:KeyboardEvent)=>{if(!event.altKey)return;if(event.key==="ArrowLeft"&&hasPrevious){event.preventDefault();move(-1)}if(event.key==="ArrowRight"&&hasNext){event.preventDefault();move(1)}};window.addEventListener("keydown",handler);return()=>window.removeEventListener("keydown",handler)});
  const submit=async(mode:"draft"|"reviewed"|"next")=>{const clean=text.trim();if(!clean){setError("请先填写中文译文。");return}setBusy(true);setError("");try{await save(clean,mode)}catch(reason){setError(reason instanceof Error?reason.message:"无法保存译文");setBusy(false)}};
  return <div className="fixed inset-0 z-50 grid place-items-center bg-black/45 p-4" onClick={close}><section className="max-h-[94vh] w-full max-w-6xl overflow-y-auto rounded-2xl bg-white p-5 shadow-2xl" onClick={event=>event.stopPropagation()}><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="label">翻译审核工作台</div><h2 className="mt-1 text-lg font-bold">{record.sourceSubmissionId||record.productSku}</h2><p className="mt-1 text-xs text-neutral-500">{seriesLabel} · {record.contactDate} · SKU {record.productSku}</p></div><div className="flex items-center gap-2"><span className="rounded-full bg-orange-50 px-3 py-1 text-xs font-semibold text-orange-800">第 {index>=0?index+1:1} / {total||1} 条</span><button onClick={close} aria-label="关闭翻译编辑"><XMarkIcon className="h-5 w-5"/></button></div></div>
    <div className="mt-4 flex items-center justify-between"><button onClick={()=>move(-1)} disabled={!hasPrevious||busy} className="btn-secondary"><ChevronLeftIcon className="mr-1 inline h-4 w-4"/>上一条</button><span className="text-xs text-neutral-500">快捷键：Option/Alt + ← 或 →</span><button onClick={()=>move(1)} disabled={!hasNext||busy} className="btn-secondary">下一条<ChevronRightIcon className="ml-1 inline h-4 w-4"/></button></div>
    <div className="mt-4 grid gap-4 lg:grid-cols-2"><section><div className="mb-2 text-sm font-semibold">英文原文（只读）</div><div className="min-h-64 whitespace-pre-wrap break-words rounded-xl bg-neutral-50 p-4 text-sm leading-7 text-neutral-700">{record.complaintMessageOriginal}</div></section><label><span className="mb-2 block text-sm font-semibold">中文译文</span><textarea autoFocus value={text} onChange={event=>setText(event.target.value)} rows={12} className="min-h-64 w-full resize-y rounded-xl border border-line p-4 text-sm leading-7 outline-none focus:border-accent focus:ring-2 focus:ring-orange-100" placeholder="在这里录入或修订中文译文…"/><span className="mt-2 block text-xs text-neutral-500">英文原文不会被覆盖。确认后仍可重新打开并修订中文。</span></label></div>
    {error&&<div className="mt-4 rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</div>}<div className="mt-4 flex flex-wrap justify-end gap-2"><button onClick={close} disabled={busy} className="btn-secondary">关闭</button><button onClick={()=>void submit("draft")} disabled={busy} className="btn-primary">保存待审核</button><button onClick={()=>void submit("reviewed")} disabled={busy} className="btn-secondary">确认并关闭</button><button onClick={()=>void submit("next")} disabled={busy} className="btn-accent">确认并审核下一条</button></div>
  </section></div>
}
