CREATE TABLE IF NOT EXISTS factories (
  code TEXT PRIMARY KEY,
  name_cn TEXT NOT NULL,
  sort_order INTEGER NOT NULL DEFAULT 0,
  active SMALLINT NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS departments (
  code TEXT PRIMARY KEY,
  name_cn TEXT NOT NULL,
  sort_order INTEGER NOT NULL DEFAULT 0,
  pin_staff TEXT NOT NULL,
  pin_supervisor TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS quotes (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  quote_no TEXT NOT NULL,
  product_name TEXT NOT NULL,
  customer TEXT,
  qty INTEGER,
  created_by_dept TEXT NOT NULL DEFAULT 'sales',
  created_by_name TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  status TEXT NOT NULL DEFAULT 'drafting',
  version TEXT,
  factory_code TEXT NOT NULL DEFAULT 'qingxi' REFERENCES factories(code),
  UNIQUE(factory_code, quote_no)
);

CREATE TABLE IF NOT EXISTS quote_sections (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  quote_id INTEGER NOT NULL REFERENCES quotes(id) ON DELETE CASCADE,
  dept TEXT NOT NULL REFERENCES departments(code),
  payload_json TEXT NOT NULL DEFAULT '{}',
  status TEXT NOT NULL DEFAULT 'empty',
  filled_by TEXT,
  filled_at TIMESTAMPTZ,
  reviewed_by TEXT,
  reviewed_at TIMESTAMPTZ,
  review_comment TEXT,
  UNIQUE(quote_id, dept)
);
CREATE INDEX IF NOT EXISTS idx_sections_quote ON quote_sections(quote_id);
CREATE INDEX IF NOT EXISTS idx_sections_dept_status ON quote_sections(dept, status);

CREATE TABLE IF NOT EXISTS audit_log (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  quote_id INTEGER,
  dept TEXT,
  actor TEXT,
  action TEXT NOT NULL,
  detail TEXT,
  at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_audit_quote ON audit_log(quote_id);

CREATE TABLE IF NOT EXISTS ref_tables (
  key TEXT PRIMARY KEY,
  data_json TEXT NOT NULL DEFAULT '[]',
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by TEXT
);

CREATE TABLE IF NOT EXISTS app_migrations (
  key TEXT PRIMARY KEY,
  applied_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS factory_ref_tables (
  factory_code TEXT NOT NULL REFERENCES factories(code),
  key TEXT NOT NULL,
  data_json TEXT NOT NULL DEFAULT '[]',
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by TEXT,
  PRIMARY KEY (factory_code, key)
);

CREATE TABLE IF NOT EXISTS users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT UNIQUE NOT NULL,
  password_hash TEXT NOT NULL,
  display_name TEXT NOT NULL,
  dept TEXT NOT NULL REFERENCES departments(code),
  role TEXT NOT NULL DEFAULT 'staff',
  factory_code TEXT NOT NULL DEFAULT 'qingxi' REFERENCES factories(code),
  locked_until TIMESTAMPTZ,
  login_fails INTEGER NOT NULL DEFAULT 0,
  last_login TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_users_dept ON users(dept);
CREATE INDEX IF NOT EXISTS idx_users_factory ON users(factory_code);
CREATE INDEX IF NOT EXISTS idx_quotes_factory ON quotes(factory_code);

CREATE TABLE IF NOT EXISTS user_factories (
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  factory_code TEXT NOT NULL REFERENCES factories(code),
  PRIMARY KEY (user_id, factory_code)
);

CREATE TABLE IF NOT EXISTS user_customers (
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  customer TEXT NOT NULL,
  PRIMARY KEY (user_id, customer)
);

CREATE TABLE IF NOT EXISTS user_perms (
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  menu TEXT NOT NULL,
  can_view SMALLINT NOT NULL DEFAULT 0,
  can_edit SMALLINT NOT NULL DEFAULT 0,
  can_review SMALLINT NOT NULL DEFAULT 0,
  can_admin SMALLINT NOT NULL DEFAULT 0,
  PRIMARY KEY (user_id, menu)
);
