"use client";
import { useEffect,useState } from "react";
import { useComplaintData } from "@/components/data-provider";
import { DataTable, KpiCard, PageTitle, StatusBadge } from "@/components/ui";

export default function SeriesManagement(){
  const {records,primarySeriesDefinitions,secondarySeriesDefinitions,primarySeriesLabel,setSeriesChineseName}=useComplaintData();const [tab,setTab]=useState<"primary"|"secondary">("primary");const translatedPrimary=primarySeriesDefinitions.filter(item=>item.chineseName!==item.name).length;const translatedSecondary=secondarySeriesDefinitions.filter(item=>item.chineseName!==item.name).length;
  const primaryRows=primarySeriesDefinitions.map(item=>[item.name,<SeriesNameEditor key={item.name} definition={item} save={setSeriesChineseName}/>,records.filter(record=>record.primarySeries===item.name).length,<StatusBadge key="status" tone={item.chineseName===item.name?"warning":"good"}>{item.chineseName===item.name?"待设置中文名":"已设置"}</StatusBadge>]);
  const secondaryRows=secondarySeriesDefinitions.map(item=>[item.name,primarySeriesLabel(item.primarySeriesName),<SeriesNameEditor key={`${item.primarySeriesName}-${item.name}`} definition={item} save={setSeriesChineseName}/>,records.filter(record=>record.primarySeries===item.primarySeriesName&&record.secondarySeries===item.name).length,<StatusBadge key="status" tone={item.chineseName===item.name?"warning":"good"}>{item.chineseName===item.name?"待设置中文名":"已设置"}</StatusBadge>]);
  return <><PageTitle title="系列管理" description="保留 Excel 原始系列名称，单独维护全站显示使用的中文名称。" action="新增系列" secondary="导出字典"/><div className="mb-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><KpiCard label="主要系列" value={String(primarySeriesDefinitions.length)} detail="来自工作表名称"/><KpiCard label="主要系列已中文化" value={String(translatedPrimary)} tone="good" detail={`${translatedPrimary} / ${primarySeriesDefinitions.length}`}/><KpiCard label="次要系列" value={String(secondarySeriesDefinitions.length)} detail="来自 Range Name"/><KpiCard label="次要系列已中文化" value={String(translatedSecondary)} tone="accent" detail={`${translatedSecondary} / ${secondarySeriesDefinitions.length}`}/></div><div className="mb-3 flex gap-2"><button onClick={()=>setTab("primary")} className={tab==="primary"?"btn-primary":"btn-secondary"}>主要系列</button><button onClick={()=>setTab("secondary")} className={tab==="secondary"?"btn-primary":"btn-secondary"}>次要系列</button></div>{tab==="primary"?<DataTable columns={["原始主要系列","对应中文名称","投诉数","状态"]} rows={primaryRows}/>:<DataTable columns={["原始次要系列","所属主要系列","对应中文名称","投诉数","状态"]} rows={secondaryRows}/>}</>
}

function SeriesNameEditor({definition,save}:{definition:{name:string;chineseName:string;kind:"primary"|"secondary";primarySeriesName:string|null};save:(kind:"primary"|"secondary",name:string,chineseName:string,primarySeriesName?:string|null)=>Promise<void>}){
  const [draft,setDraft]=useState(definition.chineseName);const [busy,setBusy]=useState(false);const [saved,setSaved]=useState(false);useEffect(()=>setDraft(definition.chineseName),[definition.chineseName]);
  return <div className="flex min-w-[230px] items-center gap-2"><input aria-label={`${definition.name}的中文名称`} value={draft} onChange={event=>{setDraft(event.target.value);setSaved(false)}} className="field min-w-0 flex-1"/><button disabled={busy||!draft.trim()||draft.trim()===definition.chineseName} onClick={async()=>{setBusy(true);await save(definition.kind,definition.name,draft,definition.primarySeriesName);setBusy(false);setSaved(true)}} className="rounded bg-ink px-2.5 py-1.5 text-xs font-semibold text-white disabled:cursor-not-allowed disabled:opacity-35">{busy?"保存中":saved?"已保存":"保存"}</button></div>
}
