-- 印尼走货明细系统 — PostgreSQL 16 Schema (schema: indo_shipping)
-- 由 db/rebuild_schema.sql (SQL Server T-SQL, 已废弃) 翻译而来；
-- 表名/列名以 src/IndoShipping.Infrastructure/Persistence/AppDbContext.cs 的 EF 映射为准
-- ("Users" 及其列为 PascalCase 带双引号，其余表/列全小写)。
--
-- 运行方式（幂等，可重复执行）:
--   docker cp postgres_schema.sql rr-portal-db-1:/tmp/
--   docker exec rr-portal-db-1 psql -U rrportal -d rrportal -v ON_ERROR_STOP=1 -f /tmp/postgres_schema.sql
--
-- 方言转换对照:
--   INT IDENTITY(1,1)                  → INT GENERATED BY DEFAULT AS IDENTITY
--   NVARCHAR(n) / NVARCHAR(MAX)        → VARCHAR(n) / TEXT
--   DATETIME2(0) DEFAULT SYSUTCDATETIME() → TIMESTAMP(0) DEFAULT now()
--   BIT DEFAULT 1/0                    → BOOLEAN DEFAULT true/false
--   ISJSON() CHECK                     → 列类型直接改 JSONB（去掉 CHECK）
--   T-SQL LIKE '[01]...' CHECK         → 正则 ~ '^[01]{9}$'
--   N'...' 前缀 / [key] / GO           → 去掉 / "key" / 删除

CREATE SCHEMA IF NOT EXISTS indo_shipping;
SET search_path TO indo_shipping;

-- ============ 身份与权限 ============
CREATE TABLE IF NOT EXISTS "Users" (
    "Id"              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Username"        VARCHAR(64)  NOT NULL,
    "PasswordHash"    VARCHAR(255) NOT NULL,
    "DisplayName"     VARCHAR(128) NOT NULL DEFAULT '',
    "Userbqrpower"    CHAR(9)      NOT NULL DEFAULT '000000000',
    "Usereditpower"   CHAR(9)      NOT NULL DEFAULT '000000000',
    "IsActive"        BOOLEAN      NOT NULL DEFAULT true,
    "CreatedAt"       TIMESTAMP(0) NOT NULL DEFAULT now(),
    CONSTRAINT "UQ_Users_Username" UNIQUE ("Username"),
    CONSTRAINT "CK_Users_Userbqrpower_Binary" CHECK ("Userbqrpower" ~ '^[01]{9}$'),
    CONSTRAINT "CK_Users_Usereditpower_Binary" CHECK ("Usereditpower" ~ '^[01]{9}$')
);

-- Bootstrap-only disabled admin; IndoShipping.Bootstrap replaces this hash from the environment.
-- 幂等：已存在 admin 时不覆盖（不碰现有密码哈希）。
INSERT INTO "Users" ("Username", "PasswordHash", "DisplayName", "Userbqrpower", "Usereditpower")
VALUES ('admin', '$2a$11$m559Cb68j1R4cHfTHJ5tV.z3oeYQyjPGL/mIlkhdltC70AnKNsLyi',
        '管理员', '111111111', '111111111')
ON CONFLICT ("Username") DO NOTHING;

-- ============ 主数据 ============
CREATE TABLE IF NOT EXISTS customers (
    id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(256) NOT NULL,
    created_at  TIMESTAMP(0) NOT NULL DEFAULT now(),
    active      BOOLEAN      NOT NULL DEFAULT true,
    CONSTRAINT "UQ_customers_name" UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS products (
    code        VARCHAR(64)  NOT NULL PRIMARY KEY,
    name        VARCHAR(256) NULL,
    hs_cn       VARCHAR(64)  NULL,
    hs_id       VARCHAR(64)  NULL,
    customer    VARCHAR(256) NULL,
    moldings    JSONB        NULL,   -- JSON: 排模表（T-SQL 原为 NVARCHAR(MAX) + ISJSON CHECK）
    created_at  TIMESTAMP(0) NOT NULL DEFAULT now(),
    updated_at  TIMESTAMP(0) NOT NULL DEFAULT now(),
    active      BOOLEAN      NOT NULL DEFAULT true
);

CREATE TABLE IF NOT EXISTS materials (
    id                  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_code        VARCHAR(64)  NULL,
    item_no             VARCHAR(64)  NULL,
    name_zh             VARCHAR(256) NULL,
    name_en             VARCHAR(256) NULL,
    spec                VARCHAR(256) NULL,
    category            VARCHAR(64)  NULL,
    material_code       VARCHAR(64)  NULL,
    hs_cn               VARCHAR(64)  NULL,
    hs_id               VARCHAR(64)  NULL,
    supplier            VARCHAR(256) NULL,
    customs_company     VARCHAR(256) NULL,
    unit_kg             VARCHAR(16)  NOT NULL DEFAULT 'KGM',
    gross_per_pc        DECIMAL(18,6) NOT NULL DEFAULT 0,
    net_per_pc          DECIMAL(18,6) NOT NULL DEFAULT 0,
    length              DECIMAL(18,4) NOT NULL DEFAULT 0,
    width               DECIMAL(18,4) NOT NULL DEFAULT 0,
    height              DECIMAL(18,4) NOT NULL DEFAULT 0,
    qty_per_carton      DECIMAL(18,4) NOT NULL DEFAULT 0,
    weight_per_carton   DECIMAL(18,4) NOT NULL DEFAULT 0,
    image_id            VARCHAR(64)  NULL,
    active              BOOLEAN      NOT NULL DEFAULT true,
    sort_order          INT          NOT NULL DEFAULT 0,
    usage_qty           DECIMAL(18,6) NULL,
    created_at          TIMESTAMP(0) NOT NULL DEFAULT now(),
    CONSTRAINT "FK_materials_products" FOREIGN KEY (product_code)
        REFERENCES products(code) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS "IX_materials_product" ON materials(product_code);
CREATE INDEX IF NOT EXISTS "IX_materials_name"    ON materials(name_zh);

CREATE TABLE IF NOT EXISTS images (
    id          VARCHAR(64)  NOT NULL PRIMARY KEY,
    mime        VARCHAR(64)  NULL,
    data_url    TEXT         NULL,   -- base64 dataURL，大字段
    created_at  TIMESTAMP(0) NOT NULL DEFAULT now()
);

-- ============ 字典 ============
CREATE TABLE IF NOT EXISTS dict_hs (
    id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    keyword     VARCHAR(128) NOT NULL,
    hs_cn       VARCHAR(64)  NULL,
    hs_id       VARCHAR(64)  NULL,
    priority    INT          NOT NULL DEFAULT 100
);
CREATE INDEX IF NOT EXISTS "IX_dict_hs_keyword" ON dict_hs(keyword);

CREATE TABLE IF NOT EXISTS dict_supplier (
    id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    keyword         VARCHAR(128) NOT NULL,
    full_name       VARCHAR(256) NULL,
    customs_company VARCHAR(256) NULL,
    priority        INT          NOT NULL DEFAULT 100
);
CREATE INDEX IF NOT EXISTS "IX_dict_supplier_keyword" ON dict_supplier(keyword);

-- ============ 排期 ============
CREATE TABLE IF NOT EXISTS schedules (
    id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    week_label      VARCHAR(64)  NULL,
    upload_date     TIMESTAMP(0) NULL,
    raw_rows        JSONB        NULL,   -- JSON（T-SQL 原为 NVARCHAR(MAX) + ISJSON CHECK）
    diff_from_prev  JSONB        NULL,   -- JSON（同上）
    created_at      TIMESTAMP(0) NOT NULL DEFAULT now(),
    CONSTRAINT "UQ_schedules_week_label" UNIQUE (week_label)
);

-- ============ 采购 ============
CREATE TABLE IF NOT EXISTS purchase_orders (
    id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    po_no           VARCHAR(64)  NULL,
    supplier        VARCHAR(256) NULL,
    status          VARCHAR(32)  NOT NULL DEFAULT 'draft',
    order_date      DATE         NULL,
    delivery_date   DATE         NULL,
    notes           TEXT         NULL,
    created_at      TIMESTAMP(0) NOT NULL DEFAULT now(),
    CONSTRAINT "UQ_purchase_orders_po_no" UNIQUE (po_no)
);

CREATE TABLE IF NOT EXISTS po_items (
    id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    po_id           INT          NOT NULL,
    product_code    VARCHAR(64)  NULL,
    material_id     INT          NULL,
    material_name   VARCHAR(256) NULL,
    qty             DECIMAL(18,4) NULL,
    price           DECIMAL(18,4) NULL,
    currency        VARCHAR(8)   NOT NULL DEFAULT '¥',
    notes           TEXT         NULL,
    category        VARCHAR(64)  NULL,
    spec            VARCHAR(256) NULL,
    usage_qty       DECIMAL(18,6) NULL,
    ordered_qty     DECIMAL(18,4) NULL,
    material_qty    DECIMAL(18,4) NULL,
    spoilage_qty    DECIMAL(18,4) NULL,
    purchase_qty    DECIMAL(18,4) NULL,
    purchase_unit   VARCHAR(16)  NULL,
    tomy_po         VARCHAR(64)  NULL,   -- 来源排期行的 TOMY PO，用于排期「已下单」精确关联
    ship_unit       VARCHAR(16)  NULL,
    net_per_pc      DECIMAL(18,6) NULL,
    eta             VARCHAR(32)  NULL,
    CONSTRAINT "FK_po_items_po"       FOREIGN KEY (po_id)       REFERENCES purchase_orders(id) ON DELETE CASCADE,
    CONSTRAINT "FK_po_items_material" FOREIGN KEY (material_id) REFERENCES materials(id)
);
CREATE INDEX IF NOT EXISTS "IX_po_items_po" ON po_items(po_id);

-- ============ 出库 ============
CREATE TABLE IF NOT EXISTS outbound (
    id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    po_no           VARCHAR(64)  NULL,
    material_id     INT          NULL,
    qty             DECIMAL(18,4) NULL,
    out_date        DATE         NULL,
    notes           TEXT         NULL,
    created_at      TIMESTAMP(0) NOT NULL DEFAULT now(),
    CONSTRAINT "FK_outbound_material" FOREIGN KEY (material_id) REFERENCES materials(id)
);
CREATE INDEX IF NOT EXISTS "IX_outbound_po_no" ON outbound(po_no);

-- ============ 走货明细 ============
CREATE TABLE IF NOT EXISTS shipments (
    id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer        VARCHAR(256) NULL,
    container_no    VARCHAR(64)  NULL,
    container_count INT          NOT NULL DEFAULT 1,
    ship_date       DATE         NULL,
    load_date       DATE         NULL,
    bl_no           VARCHAR(64)  NULL,
    rate            DECIMAL(10,4) NOT NULL DEFAULT 0.93,
    status          VARCHAR(32)  NOT NULL DEFAULT 'draft',
    created_at      TIMESTAMP(0) NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS shipment_items (
    id                  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shipment_id         INT          NOT NULL,
    material_id         INT          NULL,
    seq                 INT          NULL,
    kg                  DECIMAL(18,4) NULL,
    qty                 DECIMAL(18,4) NULL,
    cartons             INT          NULL,
    qty_per_carton      VARCHAR(64)  NULL,
    pallet              VARCHAR(64)  NULL,
    price               DECIMAL(18,4) NULL,
    currency            VARCHAR(8)   NOT NULL DEFAULT '¥',
    po_no               VARCHAR(64)  NULL,
    po_date             DATE         NULL,
    supplier            VARCHAR(256) NULL,
    customs_company     VARCHAR(256) NULL,
    bl_head             VARCHAR(256) NULL,
    contract_no         VARCHAR(64)  NULL,
    contract_date       DATE         NULL,
    invoice_no          VARCHAR(64)  NULL,
    invoice_date        DATE         NULL,
    invoice_price       DECIMAL(18,4) NULL,
    product_use         VARCHAR(256) NULL,
    formula_name        VARCHAR(256) NULL,
    CONSTRAINT "FK_shipment_items_shipment" FOREIGN KEY (shipment_id) REFERENCES shipments(id) ON DELETE CASCADE,
    CONSTRAINT "FK_shipment_items_material" FOREIGN KEY (material_id) REFERENCES materials(id)
);
CREATE INDEX IF NOT EXISTS "IX_shipment_items_shipment" ON shipment_items(shipment_id);
CREATE INDEX IF NOT EXISTS "IX_shipment_items_po_no"    ON shipment_items(po_no);

-- ============ 设置 ============
CREATE TABLE IF NOT EXISTS settings (
    "key"       VARCHAR(128) NOT NULL PRIMARY KEY,
    value       TEXT         NULL,
    updated_at  TIMESTAMP(0) NOT NULL DEFAULT now()
);

-- ============ 自增列说明 ============
-- 以下表使用 INT GENERATED BY DEFAULT AS IDENTITY（允许迁移时显式插入旧 id）:
--   "Users"("Id"), customers(id), materials(id), dict_hs(id), dict_supplier(id),
--   schedules(id), purchase_orders(id), po_items(id), outbound(id),
--   shipments(id), shipment_items(id)
-- 数据迁移完成后需对每张飞自增序列执行 setval 对齐到 MAX(id)，
-- 该步骤由 .github/workflows/indo-pg-migrate.yml 统一处理，本文件不负责。
