#!/usr/bin/env bash
# ============================================================
# QC-12: Environment Variable Validation
# ============================================================
# Ensures .env.example exists with all required variables,
# and creates .env from .env.example if missing.
# Also validates that no secrets are hardcoded in .env.example.
#
# Usage: check-env-vars.sh <app-directory>
# Exit 0: No issues found
# Exit 1: Issues found and fixed
# ============================================================

set -euo pipefail

APP_DIR="${1:?Usage: check-env-vars.sh <app-directory>}"

if [[ ! -d "$APP_DIR" ]]; then
  echo "[QC-12] ERROR: Directory not found: $APP_DIR"
  exit 1
fi

APP_NAME="$(basename "$APP_DIR")"
FIXES_MADE=0

echo "[QC-12] Validating environment variables for: $APP_DIR"

# --- Find the server directory ---
SERVER_DIR="$APP_DIR"
if [[ -d "$APP_DIR/server" ]]; then
  SERVER_DIR="$APP_DIR/server"
fi

# --- Detect stack ---
STACK="unknown"
if [[ -f "$SERVER_DIR/package.json" ]]; then
  STACK="node"
elif [[ -f "$SERVER_DIR/requirements.txt" || -f "$SERVER_DIR/pyproject.toml" ]]; then
  STACK="python"
fi

# --- Scan source files for env var references ---
ENV_EXAMPLE="${SERVER_DIR}/.env.example"

discover_env_vars() {
  local vars=""

  if [[ "$STACK" == "node" ]]; then
    vars=$(grep -rhoE 'process\.env\.\w+' "$SERVER_DIR" \
      --include='*.js' --include='*.ts' --include='*.mjs' \
      2>/dev/null | sed 's/process\.env\.//' | sort -u || true)
  elif [[ "$STACK" == "python" ]]; then
    vars=$(grep -rhoE "os\.environ\.(get\()?['\"][A-Z_]+['\"]" "$SERVER_DIR" \
      --include='*.py' 2>/dev/null | grep -oE "[A-Z_]+" | sort -u || true)
  fi

  echo "$vars"
}

DISCOVERED_VARS="$(discover_env_vars)"

if [[ -z "$DISCOVERED_VARS" ]]; then
  echo "[QC-12] PASS: No environment variables found in source code"
  exit 0
fi

echo "[QC-12] Found env vars in source: $(echo "$DISCOVERED_VARS" | wc -l | tr -d ' ')"

# --- Create .env.example if it doesn't exist ---
if [[ ! -f "$ENV_EXAMPLE" ]]; then
  echo "# Environment variables for ${APP_NAME}" > "$ENV_EXAMPLE"
  echo "# Generated by QC-12" >> "$ENV_EXAMPLE"
  echo "" >> "$ENV_EXAMPLE"

  while IFS= read -r var; do
    [[ -z "$var" ]] && continue

    # Provide sensible defaults
    local default_val="CHANGE_ME"
    case "$var" in
      PORT)           default_val="3000" ;;
      NODE_ENV)       default_val="production" ;;
      JWT_SECRET)     default_val="CHANGE_ME_BEFORE_DEPLOY" ;;
      JWT_EXPIRES_IN) default_val="8h" ;;
      CORS_ORIGIN)    default_val="*" ;;
      LOG_LEVEL)      default_val="info" ;;
      DATABASE_URL)   default_val="postgresql://postgres:password@db:5432/portal" ;;
      REDIS_URL)      default_val="redis://redis:6379" ;;
      MONGODB_URL)    default_val="mongodb://localhost:27017/app" ;;
    esac

    echo "${var}=${default_val}" >> "$ENV_EXAMPLE"
  done <<< "$DISCOVERED_VARS"

  echo "[QC-12] FIXED: created .env.example with $(echo "$DISCOVERED_VARS" | wc -l | tr -d ' ') variable(s)"
  FIXES_MADE=$((FIXES_MADE + 1))
else
  # Check if all discovered vars are in .env.example
  while IFS= read -r var; do
    [[ -z "$var" ]] && continue
    if ! grep -q "^${var}=" "$ENV_EXAMPLE" 2>/dev/null; then
      echo "${var}=CHANGE_ME" >> "$ENV_EXAMPLE"
      echo "[QC-12] FIXED: added missing var ${var} to .env.example"
      FIXES_MADE=$((FIXES_MADE + 1))
    fi
  done <<< "$DISCOVERED_VARS"
fi

# --- Create .env from .env.example if missing ---
ENV_FILE="${SERVER_DIR}/.env"
if [[ ! -f "$ENV_FILE" ]]; then
  cp "$ENV_EXAMPLE" "$ENV_FILE"
  echo "[QC-12] FIXED: created .env from .env.example"
  FIXES_MADE=$((FIXES_MADE + 1))
fi

# --- Check for real secrets in .env.example (should only have placeholders) ---
while IFS= read -r line; do
  [[ -z "$line" || "$line" == \#* ]] && continue

  var_name="${line%%=*}"
  var_value="${line#*=}"

  # Flag if a secret-looking variable has a real-looking value
  if echo "$var_name" | grep -qiE '(SECRET|PASSWORD|KEY|TOKEN)'; then
    if [[ -n "$var_value" && "$var_value" != "CHANGE_ME" && "$var_value" != "CHANGE_ME_BEFORE_DEPLOY" && ${#var_value} -gt 10 ]]; then
      echo "[QC-12] WARN: ${var_name} in .env.example may contain a real secret — replace with placeholder"
    fi
  fi
done < "$ENV_EXAMPLE"

# --- Result ---
if [[ "$FIXES_MADE" -gt 0 ]]; then
  echo "[QC-12] RESULT: Fixed ${FIXES_MADE} env var issue(s)"
  exit 1
else
  echo "[QC-12] PASS: env vars properly configured"
  exit 0
fi
