# Generated by Django 5.2.12 on 2026-03-25 00:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master_data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_type', models.CharField(choices=[('normal', '正常柜单'), ('warehouse', '入仓(车)'), ('customer_load', '客上柜'), ('qingxi', '清溪物流园')], max_length=20, verbose_name='出货类型')),
                ('si_deadline', models.DateTimeField(blank=True, null=True, verbose_name='SI截止时间')),
                ('so_number', models.CharField(blank=True, max_length=100, verbose_name='SO号')),
                ('cutoff_date', models.DateTimeField(blank=True, null=True, verbose_name='截关时间')),
                ('container_type', models.CharField(blank=True, max_length=50, verbose_name='柜型')),
                ('port', models.CharField(blank=True, max_length=50, verbose_name='港口')),
                ('ship_date', models.DateField(blank=True, null=True, verbose_name='装船日期')),
                ('container_number', models.CharField(blank=True, max_length=50, verbose_name='柜号')),
                ('seal_number', models.CharField(blank=True, max_length=50, verbose_name='封条号')),
                ('container_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='柜重')),
                ('main_factory', models.CharField(blank=True, max_length=100, verbose_name='主要工厂')),
                ('customs_broker', models.CharField(blank=True, max_length=200, verbose_name='报关行')),
                ('delivery_address', models.CharField(blank=True, max_length=500, verbose_name='送货地址')),
                ('special_requirements', models.TextField(blank=True, verbose_name='特殊要求')),
                ('remarks', models.TextField(blank=True, verbose_name='备注')),
                ('warehouse', models.CharField(blank=True, max_length=200, verbose_name='仓库')),
                ('customs_cutoff', models.DateTimeField(blank=True, null=True, verbose_name='报关截止时间')),
                ('source_email_id', models.CharField(blank=True, max_length=100, verbose_name='来源邮件ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.customer', verbose_name='客户')),
            ],
            options={
                'verbose_name': '出货单',
                'verbose_name_plural': '出货单',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factory_remark', models.CharField(blank=True, max_length=200, verbose_name='工厂备注')),
                ('seq_number', models.IntegerField(default=0, verbose_name='序号')),
                ('trading_company', models.CharField(blank=True, max_length=200, verbose_name='贸易公司')),
                ('contract_number', models.CharField(blank=True, max_length=100, verbose_name='合同号')),
                ('product_code', models.CharField(blank=True, max_length=100, verbose_name='产品代码')),
                ('product_name', models.CharField(blank=True, max_length=200, verbose_name='产品名称')),
                ('spec', models.CharField(blank=True, max_length=200, verbose_name='规格')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='国家')),
                ('toy_category', models.CharField(blank=True, max_length=200, verbose_name='玩具类别')),
                ('quantity', models.IntegerField(blank=True, null=True, verbose_name='数量')),
                ('pieces', models.IntegerField(blank=True, null=True, verbose_name='件数')),
                ('gross_weight_per_box', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='每箱毛重(kg)')),
                ('net_weight_per_box', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='每箱净重(kg)')),
                ('gross_weight', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='总毛重(kg)')),
                ('net_weight', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='总净重(kg)')),
                ('volume', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='体积(CBM)')),
                ('customer_po', models.CharField(blank=True, max_length=100, verbose_name='客户PO')),
                ('customer_po_item_no', models.CharField(blank=True, max_length=50, verbose_name='客户PO项号')),
                ('total_pieces_per_order', models.IntegerField(blank=True, null=True, verbose_name='订单总件数')),
                ('brand', models.CharField(blank=True, max_length=100, verbose_name='品牌')),
                ('pallet_count', models.IntegerField(blank=True, null=True, verbose_name='栈板数')),
                ('box_dimensions', models.CharField(blank=True, max_length=100, verbose_name='箱规')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shipments.shipment', verbose_name='出货单')),
            ],
            options={
                'verbose_name': '出货明细',
                'verbose_name_plural': '出货明细',
                'ordering': ['seq_number'],
            },
        ),
    ]
