# Generated by Django 5.2.12 on 2026-03-27 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentSubItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, default='', max_length=200, verbose_name='产品名称')),
                ('quantity', models.IntegerField(default=0, verbose_name='数量')),
                ('spec', models.CharField(blank=True, default='', max_length=200, verbose_name='规格')),
                ('toy_category', models.CharField(blank=True, default='', max_length=200, verbose_name='玩具类别')),
                ('country', models.CharField(blank=True, default='', max_length=100, verbose_name='国家')),
                ('pieces', models.IntegerField(default=0, verbose_name='件数')),
                ('volume', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='体积(CBM)')),
                ('order_index', models.IntegerField(default=0, verbose_name='排序')),
                ('parent_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_items', to='shipments.shipmentitem', verbose_name='父明细')),
            ],
            options={
                'verbose_name': '混合装子行',
                'verbose_name_plural': '混合装子行',
                'ordering': ['order_index'],
            },
        ),
    ]
