# Generated by Django 5.2.12 on 2026-04-07 00:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0002_shipmentsubitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillOfLadingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=200, verbose_name='文件名')),
                ('email_subject', models.CharField(blank=True, max_length=500, verbose_name='邮件主题')),
                ('items_snapshot', models.JSONField(default=list, verbose_name='明细快照')),
                ('total_cbm', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='总CBM')),
                ('total_pieces', models.IntegerField(blank=True, null=True, verbose_name='总件数')),
                ('verified', models.BooleanField(default=False, verbose_name='已核对')),
                ('verify_discrepancies', models.JSONField(blank=True, null=True, verbose_name='核对差异')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('shipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bl_records', to='shipments.shipment', verbose_name='关联出货单')),
            ],
            options={
                'verbose_name': '提单记录',
                'verbose_name_plural': '提单记录',
                'ordering': ['-created_at'],
            },
        ),
    ]
