# Generated by Django 5.2.12 on 2026-04-07 02:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0003_add_bill_of_lading_record'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('created', '已创建'), ('pending_qc', '待验货'), ('pending_loading', '待装柜'), ('shipped', '已出货')], default='created', max_length=20, verbose_name='状态'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('status_change', '状态变更'), ('qc_result', 'QC结果')], max_length=20, verbose_name='通知类型')),
                ('message', models.CharField(max_length=500, verbose_name='消息')),
                ('is_read', models.BooleanField(default=False, verbose_name='已读')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='接收人')),
                ('shipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='shipments.shipment', verbose_name='关联出货单')),
            ],
            options={
                'verbose_name': '通知',
                'verbose_name_plural': '通知',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QCInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('pass', '通过'), ('fail', '不通过'), ('partial', '部分通过')], max_length=10, verbose_name='验货结果')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='验货时间')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='qc_inspections', to=settings.AUTH_USER_MODEL, verbose_name='验货人')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qc_inspections', to='shipments.shipment', verbose_name='出货单')),
            ],
            options={
                'verbose_name': 'QC验货记录',
                'verbose_name_plural': 'QC验货记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QCPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='qc_photos/%Y%m/', verbose_name='照片')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='shipments.qcinspection', verbose_name='验货记录')),
            ],
            options={
                'verbose_name': 'QC照片',
                'verbose_name_plural': 'QC照片',
            },
        ),
    ]
