# Generated by Django 5.2.12 on 2026-04-24 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0004_shipment_status_notification_qcinspection_qcphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='shipment_type',
            field=models.CharField(choices=[('normal', '正常柜单'), ('warehouse', '入仓(车)'), ('customer_load', '客上柜'), ('customer_truck', '客上车'), ('qingxi', '清溪物流园')], max_length=20, verbose_name='出货类型'),
        ),
    ]
