using Microsoft.EntityFrameworkCore;

namespace StitchCostPro.Api.Shared;

public static class DatabaseCompatibility
{
    public static async Task EnsureAsync(AppDbContext db)
    {
        if (!db.Database.IsRelational()) return;

        if (db.Database.IsNpgsql())
        {
            await EnsurePostgreSqlSchemaAsync(db);
            return;
        }

        await db.Database.ExecuteSqlRawAsync("""
            IF COL_LENGTH(N'dbo.purchase_order_line', N'contract_no') IS NULL
                ALTER TABLE dbo.purchase_order_line ADD contract_no NVARCHAR(100) NULL;

            IF OBJECT_ID(N'dbo.product_import_alias', N'U') IS NULL
            BEGIN
                CREATE TABLE dbo.product_import_alias
                (
                    alias_id INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_product_import_alias PRIMARY KEY,
                    product_code NVARCHAR(50) NOT NULL,
                    external_name NVARCHAR(200) NOT NULL,
                    product_id INT NOT NULL,
                    created_by INT NULL,
                    created_at DATETIME2 NOT NULL CONSTRAINT DF_product_import_alias_created_at DEFAULT SYSUTCDATETIME(),
                    updated_by INT NULL,
                    updated_at DATETIME2 NULL,
                    CONSTRAINT FK_product_import_alias_product FOREIGN KEY(product_id) REFERENCES dbo.product(product_id),
                    CONSTRAINT UX_product_import_alias_name UNIQUE(product_code, external_name)
                );
            END
            """);
    }

    private static async Task EnsurePostgreSqlSchemaAsync(AppDbContext db)
    {
        await using var connection = db.Database.GetDbConnection();
        if (connection.State != System.Data.ConnectionState.Open)
            await connection.OpenAsync();

        await using var checkCommand = connection.CreateCommand();
        checkCommand.CommandText = """
            SELECT EXISTS (
                SELECT 1
                FROM information_schema.tables
                WHERE table_schema = 'stitch_cost'
                  AND table_name = 'dept'
            )
            """;
        var schemaExists = (bool)(await checkCommand.ExecuteScalarAsync() ?? false);
        if (schemaExists)
        {
            await db.Database.ExecuteSqlRawAsync("""
                ALTER TABLE stitch_cost.purchase_order_line
                    ADD COLUMN IF NOT EXISTS contract_no character varying(100);

                -- 总部集成同步：订单头/明细行加总部字段（幂等键 + updated_at 快照）
                ALTER TABLE stitch_cost.purchase_order
                    ADD COLUMN IF NOT EXISTS ext_main_id character varying(50);
                ALTER TABLE stitch_cost.purchase_order
                    ADD COLUMN IF NOT EXISTS source_updated_at timestamp with time zone;
                ALTER TABLE stitch_cost.purchase_order_line
                    ADD COLUMN IF NOT EXISTS ext_main_id character varying(50);
                ALTER TABLE stitch_cost.purchase_order_line
                    ADD COLUMN IF NOT EXISTS source_updated_at timestamp with time zone;

                -- 同一订单号可拆分给不同加工厂：order_no 单列唯一（若历史建过）替换为 (order_no, supplier_id) 复合唯一
                ALTER TABLE stitch_cost.purchase_order DROP CONSTRAINT IF EXISTS uq_purchase_order_no;
                CREATE UNIQUE INDEX IF NOT EXISTS ux_purchase_order_no_supplier
                    ON stitch_cost.purchase_order (order_no, supplier_id);
                CREATE UNIQUE INDEX IF NOT EXISTS ux_purchase_order_ext_main_id
                    ON stitch_cost.purchase_order (ext_main_id) WHERE ext_main_id IS NOT NULL;
                CREATE UNIQUE INDEX IF NOT EXISTS ux_purchase_order_line_ext_main_id
                    ON stitch_cost.purchase_order_line (ext_main_id) WHERE ext_main_id IS NOT NULL;
                CREATE UNIQUE INDEX IF NOT EXISTS ux_supplier_ext_main_id
                    ON stitch_cost.supplier (ext_main_id) WHERE ext_main_id IS NOT NULL;

                -- 同步游标 / 同步日志
                CREATE TABLE IF NOT EXISTS stitch_cost.integration_sync_state (
                    source                 character varying(40)   NOT NULL,
                    resource_type          character varying(40)   NOT NULL,
                    last_cursor_updated_at character varying(40)   NULL,
                    last_cursor_id         character varying(64)   NULL,
                    last_success_at        timestamp with time zone NULL,
                    last_error             character varying(1000) NULL,
                    updated_at             timestamp with time zone NOT NULL DEFAULT now(),
                    CONSTRAINT pk_integration_sync_state PRIMARY KEY (source, resource_type)
                );
                CREATE TABLE IF NOT EXISTS stitch_cost.integration_sync_log (
                    id             integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    started_at     timestamp with time zone NOT NULL,
                    finished_at    timestamp with time zone NULL,
                    resource_type  character varying(40)   NOT NULL,
                    received_count integer NOT NULL DEFAULT 0,
                    created_count  integer NOT NULL DEFAULT 0,
                    updated_count  integer NOT NULL DEFAULT 0,
                    skipped_count  integer NOT NULL DEFAULT 0,
                    failed_count   integer NOT NULL DEFAULT 0,
                    status         character varying(20)   NOT NULL,
                    error_message  character varying(2000) NULL
                );
                """);
            return;
        }

        // RR-Portal 的 PostgreSQL 是共享数据库，EnsureCreated 会因其他系统已有表而跳过。
        // 仅当本系统 schema 尚未建立时执行 EF 生成的完整建表脚本。
        await db.Database.ExecuteSqlRawAsync(db.Database.GenerateCreateScript());
    }
}
